### ISSUE TITLE
onAspectRatioChange not called when going from unset/false to set

### ISSUE THREAD

**Issue by billneff79** [DominicTobias/react-image-crop#101]
onAspectRatioChange is not being called when going from a falsey value to a truthy value, but is fired when going from a truthy value to another truthy value or to a falsey value. 

Was that intentional or not?  If not, it would be useful for our application to also fire onAspectRatioChanged when going from unset to set as we would like to update a preview of the crop that we are showing when the aspect ratio changes from freehand to a specific aspect ratio.

**Comment by DominicTobias** [comment]
Thanks this isn't intentional and your way makes sense. I'm away with just
a phone until the end of May though so won't be able to address this until
then.

**Comment by billneff79** [comment]
Thanks. Not a hurry. End of the moth would be great.

**Comment by DominicTobias** [comment]
Released in 2.0.5
