### ISSUE TITLE
Preact issue

### ISSUE THREAD

**Issue by borlaym** [DominicTobias/react-image-crop#104]
When you use Preact instead of React, a fixed aspect ratio causes the following issue:

![cropper](https://cloud.githubusercontent.com/assets/5425530/26353131/1f1af818-3fbf-11e7-9ea1-80610dade04a.gif)

Steps to reproduce on the demo page bundled with this repo:
- Install `preact` and `preact-compat`
- Add the following to the webpack config:
```
resolve: {
	alias: {
		react: 'preact-compat',
		'react-dom': 'preact-compat'
	}
}
```
- Set a fixed aspect ratio (I used 16 / 9)
- Set the state on change
```
onCropChange(crop) {
     this.setState({
	crop
     });
}
```
- Open a large image
- Adjust the window size so the image is scaled down

The same setup works with React.

**Comment by DominicTobias** [comment]
Interesting! Looks like a tricky but interesting one to figure out, may take a little while for me to get around to looking into it

**Comment by DominicTobias** [comment]
I think this issue may have been fixed in preact as I can't replicate it using 8.2.5. Please let me know if you still experience this issue.
