### ISSUE TITLE
Getting the cropped base64 image

### ISSUE THREAD

**Issue by tomhalley** [DominicTobias/react-image-crop#105]
Am I just imagining this, or is this "react image cropper" literally just drawing a crop selector over my image and then giving me back the dimensions of said crop selector? How do I actually get the cropped image back out?

**Comment by DominicTobias** [comment]
You are correct, it's also what most other cropping libraries do. In a typical scenario you want to save a cropped version of the image on the server - it makes more sense for the server to create the cropped image in this case. There are some ways to create cropped images on the client but it's dependent on modern browser features - see https://github.com/DominicTobias/react-image-crop#what-about-showing-the-crop-on-the-client
