### ISSUE TITLE
onImageLoaded called twice

### ISSUE THREAD

**Issue by tarikakyol** [DominicTobias/react-image-crop#107]
Hi,

Just wondering if there's a schedule to fix the bug below

[ReactCrop.js#L186](https://github.com/DominicTobias/react-image-crop/blob/266dd2763982a5396f9d698d0915e71d6dd20a91/lib/ReactCrop.js#L186)

**Comment by DominicTobias** [comment]
@tarikakyol Are you experiencing a double load? I'm trying to remember how to reproduce a case where this conditional happens - `this.imageRef.complete || this.imageRef.readyState` (in normal cases that doesn't actually seem to happen despite the comment)

**Comment by DominicTobias** [comment]
I've removed this comment as I think the double load is no longer happening

**Comment by mkadin** [comment]
Can we open this back up?  I can reproduce it with something simple like:

```
 <ReactCrop
            onImageLoaded={() => console.log("normal remote image")}
            src="https://cdn.vox-cdn.com/thumbor/HGTK_2UXYn3szdSim2gP6d-YZNU=/0x0:3200x2128/1200x800/filters:focal(1344x808:1856x1320)/cdn.vox-cdn.com/uploads/chorus_image/image/58121353/GettyImages_870730432.0.jpg"
          />
```

The console log is printed 2x

**Comment by DominicTobias** [comment]
@mkadin Can you make a reproducible example? As you can see here it's being called once - https://codesandbox.io/s/k37l20rp15

**Comment by mkadin** [comment]
Hmm, our example is part of a much more complicated component that I can't share.  Give me some time to try and boil it down.

**Comment by mkadin** [comment]
Turns out to be a bug on our end...sorry for the trouble.

**Comment by DominicTobias** [comment]
Ok good ;) glad figured it out
