### ISSUE TITLE
Support for rotation?

### ISSUE THREAD

**Issue by kyleramirez** [DominicTobias/react-image-crop#112]
This is simply the best most simple implementation of cropping out there for React, hands down. Thanks for keeping it simple.

Speaking of simple, and I don't mean to sound ironic, but in order to use this in my project, I need to support rotation during cropping. If you have a suggestion of how you'd approach it, I will complete it.

Big fan of this, please let me know.

**Comment by DominicTobias** [comment]
Sorry for the slow reply was on vacation. Hm sounds tricky to implement, I'd imagine you would manipulate the css `transform: rotate` property as the mouse is being dragged but there are probably various difficulties - e.g. the X point could either be the top or bottom corner depending on the rotation position (which is sticking furthest out) and same with Y. And also what to do if they rotate the shape outside the bounds of the image - partial detection of if the shape exceeds the bounds? Sounds like this would be tricky to implement!

**Comment by DominicTobias** [comment]
I'm going to close this as it's not really an issue I can fix, I think rotation would be very tricky to accomplish. I'd think about css rotation but the edge detection would be hard and x,y, width and height wouldn't work either, the callbacks would have to give back all 4 points. I think a bespoke library would be better suited to this, and possibly doing the crop selection as an SVG if css wasn't good enough.
