### ISSUE TITLE
p tags cannot contain div tags

### ISSUE THREAD

**Issue by mikaturk** [DominicTobias/react-image-crop#113]
Hey,

I was trying to use react-image-crop but it gave me this error:
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>. See App > p > ... > ReactCrop > div.

steps to reproduce: use create-react-app with react-image-crop

Greetings,
Mika

**Comment by DominicTobias** [comment]
Hi,

It's advising that you shouldn't put a div in a p, ReactCrop has divs in it
and you put it in a paragraph tag

**Comment by mikaturk** [comment]
oh wait yes it put it in the main element of the demo which is a p tag, thanks for the reply it works now :)
