### ISSUE TITLE
Support for no-resize and no new crop?

### ISSUE THREAD

**Issue by BrockWills** [DominicTobias/react-image-crop#114]
Firstly, great stuff on this project - really useful and simple!

My personal use-case is to have a predefined crop size, and then have moving that around be the only option for the user (ie. no resizing of the crop area, and no dragging to create a new crop area).

I had to fork the repo to implement this functionality, but wondering if that's something you'd be interested in for this repo? If so I can PR those changes in.

Thanks - love your work!

**Comment by DominicTobias** [comment]
Hi Brock, thanks for the kind words! I'd be interested how you did it,
however I've been meaning for some time to change this to be more in line
with the general react philosophy of passing the responsibility of mainting
state upwards and to make this a controlled component. In other words
removing internal crop state and relying on the parent (which it is already
semi doing anyway). That way the parent has more control over what to do.

There is already an option to disable the ability to make a new crop,
though I think there isn't one for resizing (apart from hiding the resize
handles with css)

**Comment by DominicTobias** [comment]
* that could be an option (disabling resizing), though I'm not sure what
the point of the handles would be without it so perhaps it's just be a case
of not rendering them out

**Comment by BrockWills** [comment]
Yeah I noticed when I first read the documentation it struck me as operating like a controller component but doesn't work fully like that in practice.

What is the option for disabling new crop? I guessed either keepSelection or disabled was supposed to do that but didn't work for me when I gave it a try (perhaps I did it wrong - will give it another go).

And yeah my of disabling the resizing in my fork was as you said, just not rendering the handles. May be a better way to do that though?

**Comment by DominicTobias** [comment]
Not rendering the handles seems like the best way, and yep keepSelection is
supposed to stop you from drawing a new crop, I hope it's not broken!

**Comment by BrockWills** [comment]
Yeah I thought that was the point of keepSelection but it isn't working for me.

The way I fixed it in my fork was, in the `onComponentMouseTouchDown` function, turn `if (this.props.disabled) return` into `if (this.props.disabled || this.props.keepSelection) return`, because you don't want to do anything when dragging on the component if you don't want to create a new crop, correct?

Also, I added a new class so that you don't have `cursor: crosshair` if you can't create a new crop.

**Comment by DominicTobias** [comment]
Ah I remember now - keepSelection only prevents clicks rather than drags for making a new crop. Curious what your use case is for not just using the disabled prop, is it to hide the resize handles? I was thinking they should probably be hidden as they serve not purpose in disabled mode. Also you already can't click or drag to make a new crop in disabled mode

**Comment by BrockWills** [comment]
Right yeah that's what I observed.

My use case is basically that I want to be able to create a crop from a prop, but then have dragging that crop around to be the only option - so no resize, and no new crop from dragging. The disabled prop wouldn't allow me to drag the crop around so that's why I implemented the props for no resize and no drag new in my fork.

**Comment by DominicTobias** [comment]
Ah ok got you, I think though that it's a bit of a niche option to add, unless someone else brings it up!

**Comment by BrockWills** [comment]
Yeah that's a fair point - still interested in implementing no handles, and no crosshair cursor, when disabled? Can PR you something if so.

**Comment by DominicTobias** [comment]
Thanks I've pushed up no handles already (not published yet) and good idea
re no crosshairs will do that too

**Comment by BrockWills** [comment]
Oh perfect...thanks for all your help 👍

**Comment by DominicTobias** [comment]
v3 has been released with a better behaving `keepSelection` fyi

**Comment by deepakkumardewani** [comment]
Hi @BrockWills. I happen to have the same scenario as you had of just allowing the user to drag the crop and no new crop and resizing. Would you be able to share the code that you implemented in your fork to achieve that? Thanks.

**Comment by DominicTobias** [comment]
In the next release there will be a `locked` property which allows dragging but disables resizing - https://github.com/DominicTobias/react-image-crop#locked-optional

**Comment by deepakkumardewani** [comment]
Hey @DominicTobias. Thank you for that and I really appreciate the great work of yours. When are you planning the next release?

**Comment by DominicTobias** [comment]
@deepakkumardewani thanks I'll publish it later today

**Comment by DominicTobias** [comment]
@deepakkumardewani Released in 6.0.10

**Comment by deepakkumardewani** [comment]
@DominicTobias Just updated the module. Working as expected. Thanks for the quick update!

**Comment by 2manoj1** [comment]
When locked: true able to resize and new corp add. How Can I restrict corp as 700 X 500? No one can change but adjust the corp postion.

**Comment by DominicTobias** [comment]
I just tried it on the sandbox demo and it appears to work fine?

![Screenshot 2020-06-04 at 09 10 34](https://user-images.githubusercontent.com/760314/83703920-5d815c80-a643-11ea-929f-7f69b3ba622f.png)

**Comment by 2manoj1** [comment]
Okay will check again

**Comment by ptucky** [comment]
> I just tried it on the sandbox demo and it appears to work fine?
> 
> ![Screenshot 2020-06-04 at 09 10 34](https://user-images.githubusercontent.com/760314/83703920-5d815c80-a643-11ea-929f-7f69b3ba622f.png)

Great, it work for me. Thanks
