### ISSUE TITLE
require('./dist/CropSelection')

### ISSUE THREAD

**Issue by Schnueggel** [DominicTobias/react-image-crop#119]
the file is actually in lib folder

**Comment by MatteCarra** [comment]
+1

**Comment by Schnueggel** [comment]
Ok it seems the file is not build somehow. Still its missing in the dist folder

**Comment by DominicTobias** [comment]
Thanks, I'm going to revert the HOC changes and move on to another branch until I can get this resolved. Will publish a fix soon.

**Comment by DominicTobias** [comment]
Should be reverted now, please try 2.1.1

**Comment by Schnueggel** [comment]
thx works for me
