### ISSUE TITLE
onImageLoaded called with undefined with odd conditions

### ISSUE THREAD

**Issue by samsch** [DominicTobias/react-image-crop#121]
onImageLoaded is first called with undefined when the ReactCrop component is initially rendered with a src value, seemingly when **re**built with Webpack. It's fairly consistent in Firefox, only seems to happen sometimes in Chrome.

Test case here: [https://codesandbox.io/s/lo9no1mkm](https://codesandbox.io/s/lo9no1mkm).

1. Turn OFF Preview On Edit in codesandbox.io settings.
1. Open browser console
1. Comment out or uncomment the final line (`render('');`) in `index.js`, and save (which rebuilds).
1. Select image with file input

The codesandbox.io output will show the React POV with a cross origin error due to the top level event being an image input event, but in the console you can see either "image is undefined` in Firefox or Chrome complain about accessing properties of undefined.

I'm not entirely certain about the possible cases. In a project I am working on which uses webpack-dev-server (not CRA), it always calls onImageLoaded with undefined in Firefox unless rendered with a blank value first.

I don't have any particularly good guesses about the cause, but I am wondering if perhaps there is an odd interaction happening which involves webpack-dev-server.

-EDIT-
There is a very simple workaround for this, which is to simply add `if (!image) { return; }` to the top of your onImageLoaded handler.

**Comment by DominicTobias** [comment]
Thanks there is a bug introduced with v3 in the case where the image has been cached by the browser, just published `3.0.1` which should fix this issue.

**Comment by samsch** [comment]
3.0.1 seems to fix the issue, which is no longer happening in my project, nor can I get it to happen again in codesandbox. My first test in codesandbox with the new version still had the issue, but I think it may just been because the old version was still cached in the build process.

**Comment by DominicTobias** [comment]
Phew! Thanks for checking 👍
