### ISSUE TITLE
Pixel crop should be calculated on naturalWidth and naturalHeight

### ISSUE THREAD

**Issue by MatteCarra** [DominicTobias/react-image-crop#122]
I think that it would be more useful to calculate pixelCrop on naturalWidth and naturalHeight

**Comment by DominicTobias** [comment]
Thanks, merged. I'll just wait a couple of days to publish to see if any issues come up from v3 in that time

**Comment by kjanoudi** [comment]
@DominicTobias this was the source of one of or major issues the past few days, so hoping we can get a deploy of 3.0.2 with this PR merged into it

**Comment by DominicTobias** [comment]
Hi, I'll see if I can publish this on my work machine today, otherwise I'll
publish this evening (GMT) at the latest

**Comment by DominicTobias** [comment]
Didn't test it but published, I hope this works even when the image is squashed out of shape!

**Comment by kjanoudi** [comment]
Thanks a lot it works well for us now!
