### ISSUE TITLE
Cropper frame is invisible

### ISSUE THREAD

**Issue by ibraback** [DominicTobias/react-image-crop#124]
I'm trying to use this package and with testing it the ``<ReactCrop />`` component displays the images without the actual selection frame that selects the portion to crop.

**Comment by DominicTobias** [comment]
Hi have you included either dist/ReactCrop.css or ReactCrop.scss?

**Comment by ibraback** [comment]
I created the app using [create-react-app](https://github.com/facebookincubator/create-react-app), in my dev environment I don't have any **dist** folder at least for now because I didn't build the app yet, for the .scss file it's missing too, but I did a trick by finding the [ReactCrop.scss](https://github.com/DominicTobias/react-image-crop/blob/master/lib/ReactCrop.scss) file in the repo, converting it to .css and import it into the component where I used the cropper.

I suggest that this part gets some clarifications since the CSS errors doesn't show in the browser's logs.

**Comment by DominicTobias** [comment]
Hi,

Are you including the css?

**Comment by ibraback** [comment]
Yes, I imported it as I said by converting the .scss file from the repo manually, it works now.

**Comment by DominicTobias** [comment]
Strange, there should be a dist folder with the css when you do an npm
install
