### ISSUE TITLE
How to store the selected part to crop in a variable

### ISSUE THREAD

**Issue by AlaDouagi** [DominicTobias/react-image-crop#127]
Hello, I want to store the selected part from the picture in a variable as a Blob/Base64 after triggering some event by clicking a button for example, I can't find any solution in the docs, help please.

**Comment by DominicTobias** [comment]
Hi, this is a little out of the scope of the package but I explained it in the readme here: https://github.com/DominicTobias/react-image-crop#what-about-showing-the-crop-on-the-client

This is pseudo code but it's something along these lines:

```js
onImageLoaded(image) {
	this.setState({ image });
}

onComplete(crop, pixelCrop) {
	var canvas = document.createElement('canvas');
	canvas.width = cropWidth;
	canvas.height = cropHeight;
	var ctx = canvas.getContext('2d');

	ctx.drawImage(
		this.state.image,
		pixelCrop.x,
		pixelCrop.y,
		pixelCrop.width,
		pixelCrop.height,
		0,
		0,
		pixelCrop.width,
		pixelCrop.height
	);

	const someImageOnYourPage = document.querySelector('.some-image');
	someImageOnYourPage.src = canvas.toDataURL('image/jpeg');
}
```

**Comment by ibraback** [comment]
Thanks for the response, I tried the code but it didn't work directly, so I did some research to find the ideal solution for everyone that has the same problem as mine.
my solution is based on the code above but it crops the part selected from the original image as it is with the maximum resolution/quality available:

```js
  onImageLoaded(image) {
    this.setState(state => ({ ...state, image }));
  }

 // My recommended reference for "canvas API" (the method 'drawImage' used in this code)
 // https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage

  onComplete(crop, pixelCrop) {
    const sX = this.state.image.naturalWidth * (crop.x / 100);
    const sY = this.state.image.naturalHeight * (crop.y / 100);
    const croppedImgWidth = this.state.image.naturalWidth * (crop.width / 100);
    const croppedImgHeight = this.state.image.naturalHeight * (crop.height / 100);

    const canvas = document.createElement('canvas');
    canvas.width = croppedImgWidth;
    canvas.height = croppedImgHeight;
    const ctx = canvas.getContext('2d');

    ctx.drawImage(
      this.state.image,
      sX,
      sY,
      croppedImgWidth,
      croppedImgHeight,
      0,
      0,
      croppedImgWidth,
      croppedImgHeight
    );

    // Base64
    const base64Image = canvas.toDataURL('image/jpeg');

    // As a blob
    canvas.toBlob(blob => {
      console.log(blob);
    }, 'image/jpeg');
  }
```
**PS**: please leave this issue open until I reference it in a pull request to the docs soon.

**Comment by DominicTobias** [comment]
Glad you got it working, are you sure `pixelCrop` won't work? It's doing the same calculation as in your code:

```js
getPixelCrop(crop) {
  const { imageRef } = this;
  return {
    x: Math.round(imageRef.naturalWidth * (crop.x / 100)),
    y: Math.round(imageRef.naturalHeight * (crop.y / 100)),
    width: Math.round(imageRef.naturalWidth * (crop.width / 100)),
    height: Math.round(imageRef.naturalHeight * (crop.height / 100)),
  };
}
```

P.S Fixed a mistake in my code:
```js
canvas.width = pixelCrop.width;
canvas.height = pixelCrop.height;
```

**Comment by ibraback** [comment]
@DominicTobias Yup, there was something wrong in the code, but I thought it was related to **pixelCrop** at first but it turns out it is related to canvas dimensions, thanks mate 😉

**Comment by ibraback** [comment]
@DominicTobias please try to resize the window and verify the cropped image using my code and yours, the **pixelCrop** object values doesn't work well in the responsive use cases.

**Comment by DominicTobias** [comment]
This should be fixed as of 3.0.2, let me know if you still have problems

**Comment by AlaDouagi** [comment]
Yup, it is solved now, the **pixelCrop** object does the trick without manually get the values from **crop** 👌

**Comment by DominicTobias** [comment]
Ok great 👍
