### ISSUE TITLE
Update documentation for onChange property

### ISSUE THREAD

**Issue by kjellski** [DominicTobias/react-image-crop#128]
Currently the released version requires onChange property, but it's not mentioned in the documentation why and what should be placed there.

**Comment by DominicTobias** [comment]
Hi, I've added an example in the readme:

```js
onChange = (crop) => {
  this.setState({ crop });
}
```

**Comment by kjellski** [comment]
Hi @DominicTobias, thanks for the fast response. I just thought this is not really required, is it? The PropType is marked .isRequired... or is that a wanted API change? I just don't know and I recognized that it wasn't before ;) 

If it's a wanted change, just go ahead and close the ticket :)

**Comment by DominicTobias** [comment]
Yep it's a wanted change, since the crop state is no longer stored in the ReactCrop component ;)

**Comment by DominicTobias** [comment]
PS I will check out your importing issue later
