### ISSUE TITLE
The distributed export doesn't work as expected

### ISSUE THREAD

**Issue by kjellski** [DominicTobias/react-image-crop#129]
The current version 3.0.2 is exporting the module in a weird way, the example

    import ReactCrop from 'react-image-crop';
    ...
    <ReactCrop src="path/to/image.jpg" />

Doesn't work anymore.

**Comment by DominicTobias** [comment]
If you `console.log(ReactCrop)` what's the output? Are you using babel and webpack in your project?

**Comment by kjellski** [comment]
@DominicTobias sorry man, I seem to have mixed up two differen things. The linter told my that the rule "import/default" was violated and I misinterpreted that. I've now disabled the rule, and it's just fine with the example you provided. 
Although, is there anything against a ES6 "default export" ? Or is it just not getting through the transpile?
