### ISSUE TITLE
(Idea) Trigger event when image is loaded

### ISSUE THREAD

**Issue by DPr00f** [DominicTobias/react-image-crop#13]
Hey @DominicTobias, 
Sorry to raise an issue but couldn't find another way to submit an idea.
I was wondering if the library should be triggering an event (onLoaded/onComplete) when the image is loaded. The reason when I'm asking is that if the aspect property is passed in, essentially the crop state will change, but it's not reported back to the parent component.
By now I'm avoiding this by doing the calculations myself and triggering the preview component, but it feels wrong since react-image-crop is doing the calculations.
Let me know thoughts

**Comment by DominicTobias** [comment]
Not at all - I appreciate the suggestions and contributions! Exposing the image load event would be fine by me, perhaps `onImageLoaded`? Feel free to make a PR :)

**Comment by DPr00f** [comment]
`onImageLoaded` seems good to me.
I'll do the PR then :)
Thanks
