### ISSUE TITLE
can this work?

### ISSUE THREAD

**Issue by nicewahson** [DominicTobias/react-image-crop#131]
can't work on my pc chrome 61, can it be more simple to use?

**Comment by DominicTobias** [comment]
Please show how you’re trying to use it or I can’t help

**Comment by nicewahson** [comment]
i copy demo code
<pre>
class Parent extends Component {
    constructor() {
      super();
      this.state = {
        crop: {
          x: 0,
          y: 0,
          // aspect: 16 / 9,
        },
        maxHeight: 80,
      };
      this.onButtonClick = this.onButtonClick.bind(this);
    }
    // ...

    render() {
      return (
        <div>
          <ReactCrop
            {...this.state}
            src="http://imgsrc.baidu.com/image/c0%3Dshijue1%2C0%2C0%2C294%2C40/sign=dce088c1a3ec8a1300175fa39f6afbfa/622762d0f703918f2b2091e45b3d269759eec42f.jpg"
            onImageLoaded={this.onImageLoaded}
            onComplete={this.onCropComplete}
            onChange={this.onCropChange}
          />
          <button onClick={this.onButtonClick}>Programatically set crop</button>
          <button onClick={() => { this.setState({ foo: Date.now() }); }}>Change foo state</button>
        </div>
      );
    }
  }

class App extends Component {
  render() {
    return (
        <Parent />
    );
  }
}
</pre>
just change the property 'src' with a url string and what is the next step?there is just a button but not work

**Comment by nicewahson** [comment]
well, i forget to include style file, o(╯□╰)o
