### ISSUE TITLE
 Cannot read property 'aspect' of undefined to click for to do a crop

### ISSUE THREAD

**Issue by paterninaisf** [DominicTobias/react-image-crop#132]
Hey Dominic Thanks for this library!

I have a issue when try to implement the puglin. When I try to do click for selcect an area for to do a crop, It's throw an exception. Do you have any idea about this?

` Cannot read property 'aspect' of undefined`

![image](https://user-images.githubusercontent.com/19295280/31950302-eb3bbc70-b8a0-11e7-9134-68704e54453d.png)
![image](https://user-images.githubusercontent.com/19295280/31950316-f6fa6e08-b8a0-11e7-9795-feb949ced74b.png)

**Comment by paterninaisf** [comment]
Hey, I missed pass the `crop` prop to component, however, in the documentation say that is optional, for that I thought that it's no was necessary. 

Thank you!

**Comment by DominicTobias** [comment]
Hm it's supposed to be optional! Can you let me know what props you were trying? Thanks

**Comment by davitv** [comment]
Same issue i have

**Comment by davitv** [comment]
<img width="1491" alt="screenshot 2017-11-01 19 14 33" src="https://user-images.githubusercontent.com/3396749/32287583-f9c316ae-bf39-11e7-8066-61d526c91397.png">

**Comment by DominicTobias** [comment]
Thanks I'm able to replicate the bug, I'll make a release with a fix shortly

**Comment by davitv** [comment]
Thanks! That's blazingly fast!

**Comment by DominicTobias** [comment]
Released 3.0.6

**Comment by davitv** [comment]
Sir, you are a legend!

**Comment by paterninaisf** [comment]
Hey, Thank you man!!
