### ISSUE TITLE
Add Minified Version for External Usage

### ISSUE THREAD

**Issue by virgofx** [DominicTobias/react-image-crop#134]
Since this library is not that small and typically used only on certain pages for applications it would be nice to have a minified version for use on production sites where the file can be loaded in UMD format from a CDN.

**Comment by DominicTobias** [comment]
This used to exist in the project and someone made a PR to remove it :P

Personally I don't mind it being here though.

PS Most people tend to use something like NPM + webpack to consume modules so this isn't an issue. You would use webpack's `System.import` abilities to load different bundles for each route so it would automatically only load what was needed for each one.

**Comment by virgofx** [comment]
Odd, not sure why someone would remove it.  Either way, adding it only adds additional opt-in functionality for people that may want CDN usage. You're right most people probably consume by requiring the module directly and bundling directly.

**Comment by DominicTobias** [comment]
Yep sounds good, just wondering how webpack consumes the config since you changed it to an array with 2x functions (as per comment in PR)?

**Comment by virgofx** [comment]
Passing an array enables Webpack's multi-compiler mode. It's just a way to run Webpack multiple times in one pass. 

Example:
https://github.com/webpack/webpack/tree/master/examples/multi-compiler

**Comment by DominicTobias** [comment]
Ah good to know 👍

**Comment by DominicTobias** [comment]
Published 3.0.3 @virgofx

**Comment by virgofx** [comment]
Sweet -- Looks good:
https://unpkg.com/react-image-crop@3.0.3/dist/

I'll submit a PR now to get this repo added to CDNJS and CC you. Usually takes a few days to get things done over there.
