### ISSUE TITLE
Get Webpack case-sensitive warning with v3.0.3 

### ISSUE THREAD

**Issue by chenesan** [DominicTobias/react-image-crop#136]
It seems that in v3.0.3 with `dist/`, webpack will warn about case-sensitive problem when import react-image-crop:

```
WARNING in ./~/React/react.js
[1] There are multiple modules with names that only differ in casing.
[1] This can lead to unexpected behavior when compiling on a filesystem
[1] with other case-semantic.
[1] Use equal casing. Compare these module identifiers:
[1] * /Path/To/My/Project/node_modules/React/react.js
[1]     Used by 1 module(s), i. e.
[1]     /Path/To/My/Project/node_modules/react-image-crop/dist/ReactCrop.js
[1] * /Path/To/My/Project/node_modules/react/react.js
[1]     Used by 368 module(s), i. e.
[1]     /Path/To/My/Project/node_modules/babel-loader/lib/index.js??ref--0!/Path/To/My/Project/views/index.js
```

**Comment by salali** [comment]
Have this issue also

**Comment by DominicTobias** [comment]
Thanks I didn't spot the change in a PR that caused this but will update and release a fix now

**Comment by DominicTobias** [comment]
Sorry github auto closed the issue, but let me know if that fixes it plz

**Comment by virgofx** [comment]
@DominicTobias React needs to be uppercase. This breaks UMD.

**Comment by DominicTobias** [comment]
Hm that's going to be a problem as people require in `react` not `React`, modules are lower case in NPM world. Will need to see if there's compromise. How does it break UMD exactly?

**Comment by virgofx** [comment]
Weird is that I can't reproduce the issue. Not sure how others are seeing it?

**Comment by DominicTobias** [comment]
I was actually curious too because if you require the package normally it should (I thought) get lib/ReactCrop, not the built version. So I was wondering how the warning was talking about e.g. `/Path/To/My/Project/node_modules/react-image-crop/dist/ReactCrop.js`

@chenesan @salali ow are you include this package in your projects?

**Comment by virgofx** [comment]
Yeah the /dist versions shouldn't be included. That's for CDN only. So it appears to be a user error. Checking newer versions of webpack the new standard is to simply have `react: 'React'`. So 3.0.3 appears to be correct.

**Comment by DominicTobias** [comment]
Yeah thinking about it seems likely. Do you think

```js
react: {
  root: 'React',
  commonjs2: 'react',
  commonjs: 'react',
  amd: 'react',
}
```

Should work though as root['React'] which gets compiled is equivalent to `window.React`. I'll publish the change.

**Comment by virgofx** [comment]
So the above fix - Works. The /dist contents to get included as specified via the index.js -- Which is the correct and desired behavior as there may be some processing done to cleanup the library prior to being consumed. So 3.0.5 should be good.  Maybe make a note in the release notes in 3.0.4 to not use this version and upgrade immediately to 3.0.5.

**Comment by DominicTobias** [comment]
Thanks for checking, I've added that

**Comment by chenesan** [comment]
@DominicTobias I got this issue when I `yarn add react-image-crop` with v3.0.3 and `import ReactCrop from 'react-image-crop'` in my project. Maybe the `index.js` export the module in `dist/`?
Anyway, the warning disappears in v3.0.5 for me, too;) Thank you @DominicTobias @virgofx !

**Comment by DominicTobias** [comment]
Thanks for checking @chenesan. Yeah interesting not sure why that warning was appearing then, but at least it's fixed!
