### ISSUE TITLE
Feature Request: Circular Bounding Preview

### ISSUE THREAD

**Issue by virgofx** [DominicTobias/react-image-crop#137]
I know this used to exist in v1 and was subsequently removed in v2 to remove bloat; however, now that the code base is cleaner, uses PureComponent, fairly lightweight ... would it be at all possible to revisit the circular bounding preview to see if it could be easily incorporated?

**Comment by DominicTobias** [comment]
By preview do you mean the cropped area? Is the use case for a profile pic?

If so I would imagine it would be better as a fixed 1:1 aspect, and the inside of the rectangle is shaded so that it shows a circle in the middle?

**Comment by virgofx** [comment]
Yes referring only to a preview of the cropped area. All aspect coordinates can remain intact - e.g. `x, y, width, height` ... the only change would be to the crop preview (when using fixed aspect ratio 1:1) to show some sort of overlay/circular preview. I believe that it could be done with mostly efficient CSS/adjustments. If done via a singular class and then CSS, figured it could be done pretty easy and then just adding another option in the config props to adjust.

It doesn't have to change the coordinates of the square corners to do this:
![image](https://user-images.githubusercontent.com/739719/32233162-fe66fa6e-be16-11e7-897d-794d451c1a24.png)

You could just blend both ... somehow leave everything and then just add some sort of visual circle to highlight the inside or unhighlight the outer boundaries

**Comment by DominicTobias** [comment]
Yep I see what you mean, if it can be achieved with minimal extra code and mostly css then sounds good. However I'm travelling 50%+ of the time from now until December and have lots to do so I can't say if and when I'll look into doing it!

**Comment by virgofx** [comment]
No worries -- I think we're on the same page. Will leave this open if anyone else has time to submit a PR for a visual addition with additional prop. I think it should be pretty easy.

**Comment by virgofx** [comment]
It appears just setting the selection div to use `border-radius: 50%` works sufficiently. Will close this for reference.

![image](https://user-images.githubusercontent.com/739719/33634173-26248d56-d9c8-11e7-86d9-4e6b2afd1d50.png)

**Comment by DominicTobias** [comment]
Great! That was easy

**Comment by DThanhNg** [comment]
Sorry to raise the question again. You mentioned _setting the selection div to use border-radius: 50%_ . Where can I find this settings? I meant what Props of ReactCrop takes css styles for 'selection div' you mentioned. I tried to put it in crop parameter, it didn't work

**Comment by DominicTobias** [comment]
You would have to do this with CSS on the crop area. I will add an option
to make it rounded in the next release along with rule-of-two-thirds

**Comment by DominicTobias** [comment]
There is now a `circularCrop` option to do this

**Comment by NonsoAmadi10** [comment]
How do you make the cropped canvas image remain in circular form

**Comment by DominicTobias** [comment]
@NonsoAmadi10 you will need to do some canvas clipping I haven't tried it myself - try searching for something like "html canvas circular image clip" for example https://stackoverflow.com/questions/7166471/how-to-draw-only-a-circular-part-of-an-image-with-html-5-canvas/7170712 -- fiddle from there: http://jsfiddle.net/hJS5B/47/
