### ISSUE TITLE
Cropping by top corners

### ISSUE THREAD

**Issue by Janekk** [DominicTobias/react-image-crop#14]
Tried that in Chrome. Grabbing the corner and trying to make the crop area smaller, causes moving the whole crop area to some other part of the image. Pretty nasty ;)

**Comment by DominicTobias** [comment]
@Janekk That's strange, I can't replicate it - what version are you using and what crop params did you use? If you open demo/index.html do you get the same behaviour?

**Comment by Janekk** [comment]
Just stumbled upon that in my React component, pretty basic one:

```
  constructor() {
    super();

    this.state = {
      dataUrl: null
    };

    this.crop = {
      x: 20,
      y: 10,
      width: 60,
      aspect: 3 / 4
    };
  }

  render() {
    var {dataUrl} = this.state;
    return (
      <div>
        <input type="file" onChange={this.onFileChange.bind(this)}/>
        {dataUrl ?
          <ReactCrop crop={this.crop} src={dataUrl} onComplete={this.onCropComplete.bind(this)}/>
          : null
        }
      </div>
    );
  }
```

Will try to test it in isolation to be sure that nothing from my project influences that behavior. Btw. @DominicTobias how can I run your demo? I started it with `npm dev`, webpack has started, but what url/port is it running on?

**Comment by DominicTobias** [comment]
Thanks I'll check this probably tomorrow. To run that that (without wanting
to modify the source) simply open up index.html - no need to start a server

**Comment by DPr00f** [comment]
I think I know what's going on with this issue.
Probably the image you're using is bigger in width than height.
But you're forcing the width to be 60% and letting react-image-crop to figure out the height. (Which will most likely be outside of the boundaries)
Take a look at the gif
![bug14](https://cloud.githubusercontent.com/assets/989959/12529940/4b64c1e4-c1c4-11e5-92fc-d0ef1c29bb9f.gif)

A work around for this is to figure out before hand which values to pass to react-image-crop. Either pass width or height when the aspect is set, but don't do both.

**Comment by DPr00f** [comment]
@Janekk can you tell by the gif if those were the problems you were experiencing?

**Comment by DominicTobias** [comment]
Thanks for the investigation @DPr00f , even if it's not that it's a good catch

**Comment by Janekk** [comment]
@DPr00f actually it was a vertical image, so it should be ok with settings from my snippet. I'll take a look today again

**Comment by DominicTobias** [comment]
@Janekk if you still have the problem please link to the image here and I'll try with those settings

**Comment by Janekk** [comment]
@DominicTobias @DPr00f the problem turned out to be quite simple one to reproduce. Try adding something to the demo page above the file input, that takes some vertical space, so that you have scroll to the image crop area. Then try dragging the top corners. It might be something with the offset calculation (`getElementOffset` ?)

**Comment by DominicTobias** [comment]
Thanks that sounds easy to reproduce, I'll take a look later

**Comment by DominicTobias** [comment]
Fixed in 0.0.1

**Comment by DPr00f** [comment]
Nice. Good job Dominic

**Comment by Janekk** [comment]
Thank you Dominic
