### ISSUE TITLE
not working in IE 11, for big image

### ISSUE THREAD

**Issue by edidiway** [DominicTobias/react-image-crop#147]
Hi, I am testing on IE 11, and use the big image resolution.
When you used image which height is greater than its content, and scroll was appear..
Then when I scroll down and want to crop the photo, the scroll always reset/go to the top of browser again.

**Comment by DominicTobias** [comment]
Hi, is the scroll being reset as you're dragging a crop, or just when you're scrolling down the page?

**Comment by DominicTobias** [comment]
This has been fixed in v4 now
