### ISSUE TITLE
cropping from initial state without onChange

### ISSUE THREAD

**Issue by foodaka** [DominicTobias/react-image-crop#148]
i am setting a suggested crop dimensions

 const coverInitialState = {
   x: 0,
   y: 25,
   width: 100,
   height: 50
 }

if the user just clicks a button crop, how to get the pixelCrop so i can display a preview of the crop to the user? Because the user did not drag the cursor the onChange was not fired and thus no pixelCrop object for the canvas.

**Comment by DominicTobias** [comment]
Hi,

In this case you can calculate your own pixel crop in `onImageLoaded`:

```js
onImageLoaded = (image) => {
  const { crop } = this.state;
  const pixelCrop = {
      x: Math.round(image.naturalWidth * (crop.x / 100)),
      y: Math.round(image.naturalHeight * (crop.y / 100)),
      width: Math.round(image.naturalWidth * (crop.width / 100)),
      height: Math.round(image.naturalHeight * (crop.height / 100)),
    };
  console.log('pixelCrop:', pixelCrop);
}
```

**Comment by foodaka** [comment]
Ah thanks for the reply, and kudos for the awesome library
