### ISSUE TITLE
Select box not visible

### ISSUE THREAD

**Issue by SevenZark** [DominicTobias/react-image-crop#149]
Hi,

First of all, thanks for this! I hope I can get it working because it's just what I needed.

I'm having an issue where, when clicking and dragging on the image, the selection frame does not show. The cursor correctly changes to crosshairs over the image, and upon clicking, a darkened semi-opaque layer shows up over the image, but no selection box or handles show up at all.

I'm using Chrome on a mac. Yes, I am including the scss and it seems to be working at least for the dark layer and the mouse cursor change.

Relevant code snips:

```
onChange(crop) {
  this.setState({crop})
}

```

```
<ReactCrop
  src={this.props.image}
  crop={{aspect: 16/9}}
  onChange={this.onChange}
/>
```

**Comment by SevenZark** [comment]
Okay, I got it to work by doing this:

```
<ReactCrop
  src={this.props.image}
  crop={this.state.crop}
  onChange={this.onChange}
```

So, the ReactCrop object wasn't showing any selection because it wasn't aware of one. I figured this out by a pure lucky guess, but the documentation doesn't show this. In fact, it shows the crop property as being 'optional.' Did I just miss the info somewhere? Or maybe does the documentation need to be clarified?

**Comment by DominicTobias** [comment]
Hi, glad you solved it. The readme says:

crop (optional)
All crop values are in percentages, and are relative to the image. All crop params are optional. _However while you can initially omit the crop object, any subsequent change will need to be saved to state in the onChange callback and set here._

I hope this is clear enough!

**Comment by SevenZark** [comment]
It's clear, yes, but perhaps easy to miss. Or it was for me, anyway. It might be helpful to put the property assignment right in the example code near the top of the readme, since it's one of the first things people will see, and something most will need to do when looking at that example code. Just a suggestion. :)

**Comment by DominicTobias** [comment]
Agreed, I've tried to make it clearer now and moved the onChange doc up there too
