### ISSUE TITLE
Add $mobile-media-query sass variable

### ISSUE THREAD

**Issue by owenoak** [DominicTobias/react-image-crop#153]
The `ReactCrop.scss` file currently specifies a `$mobile-max-width` variable, which is used to generate a media query for mobile devices:

```
$mobile-max-width: 768px;
...
@media (max-width: $mobile-max-width) {...}
```

In my project, I'm only supporting iOS and Chrome, so I can use the `pointer: coarse` media feature (https://developer.mozilla.org/en-US/docs/Web/CSS/@media/pointer) which will engage in mobile devices where fingers are used, and be ignored on desktop browsers.

I suggest you instead define:

```
$mobile-media-query:  "max-width: 768px" !default;
...
@media($mobile-media-query) {...}
```

That way I can override the entire media query before including the `ReactCrop.scss` file in my project.

Thanks!

**Comment by DominicTobias** [comment]
This and your other suggestion seem like sensible ideas. Are you able to
raise a PR for them? Thanks

**Comment by owenoak** [comment]
Done, my first pull request.  :-)  I did one request for both this and #152.  Thanks!

**Comment by DominicTobias** [comment]
Great! thanks @owenoak
