### ISSUE TITLE
Expects width and height both

### ISSUE THREAD

**Issue by aanchalgera** [DominicTobias/react-image-crop#155]
The documentation states that we can either specify width or height but if I initialise crop of ReactCrop as 
```  
crop: {
    aspect: 1,
    x: 10,
    height: 100
} 
```
It doesn't show a selection box. As I understand, it's because, it does not go into this code block
```
 if (isCropValid(crop)) {
      cropSelection = this.createCropSelection();
    }
```
so `cropSelection` is not initalized. It was working perfectly fine in version 2.1.1.

**Comment by DominicTobias** [comment]
Hi, the documentation says you can either omit both of them, or include them. I'm surprised this was working in 2.1.1 because the crop wouldn't be visible if it had no width. What were you expecting to see if it did work?

**Comment by aanchalgera** [comment]
I am giving the aspect ratio, x and height. I was expecting the width to be
calculated by itself.
I am giving this as the default value to display a box of fixed aspect
ratio. Is there any other way?

On Jan 19, 2018 5:54 PM, "Dominic Tobias" <notifications@github.com> wrote:

Hi, the documentation says you can either omit both of them, or include
them. I'm surprised this was working in 2.1.1 because the crop wouldn't be
visible if it had no width. What were you expecting to see if it did work?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DominicTobias/react-image-crop/issues/155#issuecomment-358952768>,
or mute the thread

**Comment by DominicTobias** [comment]
Aha yes I get you now. This has unfortunately changed to be a bit less convenient than before.

Before state was internally maintained inside the component - so the crop was copied to state, and internally it would figure out the missing width or height.

Making this a "pure" component has some nice advantages, but it means that you need to tell it both width and height.

To do this you should instead set your crop in `onImageLoaded`. See these instructions: https://github.com/DominicTobias/react-image-crop#onimageloadedimage-optional

**Comment by aanchalgera** [comment]
Sure. I will do it this way then. Thanks for the prompt reply :)

**Comment by DominicTobias** [comment]
Np, closing, let me know if you have any issues with it
