### ISSUE TITLE
Initial image preview

### ISSUE THREAD

**Issue by saveliy-kremen** [DominicTobias/react-image-crop#156]
I am init component:
`  onImageLoaded(image) {
    this.setState({
      crop: makeAspectCrop(
        {
          x: 0,
          y: 20,
          aspect: this.props.widthPreview / this.props.heightPreview,
          width: 100,
          keepSelection: true
        },
        image.width / image.height
      )
    });
  }`

But onCropComplete return hole image, not cropped area.
If change cropped area, all works fine.

**Comment by saveliy-kremen** [comment]
This issue can be closed. Everything works well. It was decided by adding the code to
onImageLoaded(image):
`  onImageLoaded(image) {
    const crop = makeAspectCrop(
      {
        x: 0,
        y: 20,
        aspect: this.props.widthPreview / this.props.heightPreview,
        width: 100,
        keepSelection: true
      },
      image.width / image.height
    );
    const pixelCrop = {
      x: Math.round(image.naturalWidth * (crop.x / 100)),
      y: Math.round(image.naturalHeight * (crop.y / 100)),
      width: Math.round(image.naturalWidth * (crop.width / 100)),
      height: Math.round(image.naturalHeight * (crop.height / 100))
    };
    this.onCropComplete(crop, pixelCrop);
  }`

**Comment by DominicTobias** [comment]
Hi, just wondering what the reason for calling `onCropComplete` manually here is?

**Comment by saveliy-kremen** [comment]
Hi, it was necessary to get the cropped image by default, without changing the crop area.

onCropComplete(crop, pixelCrop) {
	const canvas = document.createElement("canvas");
	canvas.width = pixelCrop.width;
	canvas.height = pixelCrop.height;
	const ctx = canvas.getContext("2d");
	ctx.drawImage(
	  this.props.originalUploadFile.file,
	  pixelCrop.x,
	  pixelCrop.y,
	  pixelCrop.width,
	  pixelCrop.height,
	  0,
	  0,
	  pixelCrop.width,
	  pixelCrop.height
	);
	const base64Image = canvas.toDataURL("image/jpeg");
	this.props.handleCroppedImage({ data: crop, preview: base64Image });
  }

**Comment by DominicTobias** [comment]
Aha ok I get it, glad you solved it!
