### ISSUE TITLE
This plug-in doesn't work on the mobile H5

### ISSUE THREAD

**Issue by hrh94** [DominicTobias/react-image-crop#157]
What parameters do I need to set up

**Comment by hrh94** [comment]
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>

**Comment by skv-headless** [comment]
How it looks in console

<img width="682" alt="screen shot 2018-01-25 at 18 12 32" src="https://user-images.githubusercontent.com/1488195/35388836-5f5aa23a-01fb-11e8-9f98-3ec170f2d495.png">

https://www.chromestatus.com/features/6131337345892352

As I understood chrome now wants `{passive: false}` explicitly. 
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Parameters

**Comment by DominicTobias** [comment]
Aha, thanks @skv-headless, I'll make a patch update

**Comment by DominicTobias** [comment]
When you have time please try v3.0.10 @hrh94

**Comment by DominicTobias** [comment]
I'm closing this but let me know if there are any problems, should be fixed with 3.0.10
