### ISSUE TITLE
Consider to convert the code to ES5

### ISSUE THREAD

**Issue by bennyhan9** [DominicTobias/react-image-crop#159]
The library isn't transpiled correctly to es5, 

you get error: 
**Unexpected token
You may need an appropriate loader to handle this file type**

**Comment by DominicTobias** [comment]
Hi,

How are you including this library? It's already pointing to the compiled ES5 module at https://github.com/DominicTobias/react-image-crop/blob/master/dist/ReactCrop.js if you include it the normal way.

**Comment by bennyhan9** [comment]
i include it this way:
const ReactCrop = require('react-image-crop/dist/ReactCrop');

and it now work without any error, thanks.

**Comment by DominicTobias** [comment]
OK strange! The "main" entry in package.json points to that file so it shouldn't be necessary
