### ISSUE TITLE
pixelCrop Not Set Until Change Occurs

### ISSUE THREAD

**Issue by jimmyhales** [DominicTobias/react-image-crop#160]
I have a special case where I configured the crop tool default location and size to be exactly where it needs to be for my collection of images, all the same size. Ideally I could open with the cropper and hit save, but even though the crop tool appears like it's going to crop the image, no pixelCrop item has been created because nothing has changed after loading the image. This causes the image to save the entire photo without being cropped. This requires the user to "change" the cropping parameters before saving.

I understand I can calculate the correct ratio upon the image being opened, but this is something react-image-crop should be doing. 

If the pixelCrop tool were available upong onImageLoaded then this wouldn't be an issue.

**Comment by DominicTobias** [comment]
The component is now pure and driven by props, it doesn't maintain state internally. This allows for greater simplicity, more control (controlled component vs uncontrolled), but also means it doesn't internally set an aspect ratio when the image is loaded.

In your case you can listen for `onImageLoaded` and crop from there, something like:

```js
onImageLoaded = (image) => {
  const { crop } = this.state;

  const pixelCrop = {
    x: Math.round(image.naturalWidth * (crop.x / 100)),
    y: Math.round(image.naturalHeight * (crop.y / 100)),
    width: Math.round(image.naturalWidth * (crop.width / 100)),
    height: Math.round(image.naturalHeight * (crop.height / 100)),
  };

  this.renderCropPreview(image, pixelCrop);
}
```

**Comment by DominicTobias** [comment]
*Or, if like you're saying you need to calc the ratio:

```js
onImageLoaded = (image) => {
  const crop = makeAspectCrop({
    x: 0,
    y: 0,
    aspect: 16 / 9,
    width: 50,
  }, image.width / image.height);

  const pixelCrop = {
    x: Math.round(image.naturalWidth * (crop.x / 100)),
    y: Math.round(image.naturalHeight * (crop.y / 100)),
    width: Math.round(image.naturalWidth * (crop.width / 100)),
    height: Math.round(image.naturalHeight * (crop.height / 100)),
  };

  renderCropPreview(image, pixelCrop);

  this.setState({ crop });
}
```

**Comment by jimmyhales** [comment]
Thank you for this. Now that I see how you created the pixelCrop from the
crop upon onImageLoaded I'm surprised I didn't think of this.

This does what I needed it to do. Thanks!

**Comment by DominicTobias** [comment]
Great, glad you got it working!
