### ISSUE TITLE
How to write the declaration document with typescript?

### ISSUE THREAD

**Issue by countingSta** [DominicTobias/react-image-crop#162]

**Comment by DominicTobias** [comment]
Hi can you add more detail, I'm unfamiliar with TS?

**Comment by danielasy** [comment]
Hi, if there's any interest, I can try to write the type definitions for this library 🙂 I've used it in a component for TypeScript project a while ago

**Comment by DominicTobias** [comment]
Hi Danielasy if you’d like to then that would be great!

**Comment by YvanGuidoin** [comment]
I would also appreciate, as I'm using react-image-crop in a project that we're moving to typescript (Thanks @DominicTobias btw for your work).

To be compatible with typescript, you only need a declaration file for the interfaces of the component (like `PropTypes` but more powerful) and a line in your `package.json` to precise to the typescript compiler where to find the declaration file

**Comment by danielasy** [comment]
Hello all, it took a while but I opened a PR at DefinitelyTyped. Feel free to check it out: [https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25431](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25431)

**Comment by DominicTobias** [comment]
This has been merged now so closing, thanks @danielasy

**Comment by TomasHubelbauer** [comment]
Would you consider merging the types in with this library and setting them up in `package.json`/`types` so that we don't have to install the `@types` package separately?

**Comment by DominicTobias** [comment]
Hi we don't need to merge them we can simply declare them as a dependency in this module so you don't have to install them yourself as per this comment https://github.com/Microsoft/types-publisher/issues/81#issuecomment-234051338

If you want to make a PR for that I'd be happy to merge as I won't be able to do it until some time next week.
