### ISSUE TITLE
Is there a way to limit the file size of the final cropped image? 

### ISSUE THREAD

**Issue by firaskrichi** [DominicTobias/react-image-crop#164]
Sometimes a 5MB file when cropped for example can be a little bigger. Is there a way to limit the size of the final cropped image not to exceed 5MB for example? 

Thanks!

**Comment by DominicTobias** [comment]
Hi, are you uploading that data to the server? Are you uploading the cropped canvas data?

**Comment by hrh94** [comment]
At the same time, the selected picture has 5M, but the image is compressed by react-image-crop, so that only 500K is uploaded to the server

**Comment by DominicTobias** [comment]
I'm not exactly sure what you mean, but you have two choices:

1) Upload the original image once, and only send crop parameters to the server.
2) Reduce the image size when mapping it to canvas, and also you can reduce the image quality (google for this)

**Comment by firaskrichi** [comment]
@DominicTobias sorry for the late reply. 

Yes I am uploading the copped canvas data to the server. My question is, does the cropped canvas data file size exceed the original file size, and is it possible to reduce the quality of the cropped canvas data to never exceed a certain file size

**Comment by DominicTobias** [comment]
This is more of a question for google, I have reduced the image quality of an image before but I can't remember the implementation details. Try searching something like "javascript reduce canvas image quality", there are quite a lot of solutions and answers on stackoverflow etc e.g. https://stackoverflow.com/questions/18922880/html5-canvas-resize-downscale-image-high-quality

**Comment by firaskrichi** [comment]
Great thanks @DominicTobias !
