### ISSUE TITLE
Custom parameter to onChange(crop, pixelCrop)

### ISSUE THREAD

**Issue by GoodGuyMarco** [DominicTobias/react-image-crop#165]
How can I pass a custom parameter to the onChange function?

**Comment by GoodGuyMarco** [comment]
`
onCropChange = (crop, pixelCrop, imageName) => {

        console.log(crop, pixelCrop);

        this.setState({
            croppedImages: {
                ...this.state.croppedImages,
                [imageName]: {
                    crop: crop,
                    pixelCrop: pixelCrop
                }
            }
        });
    };

    renderPreview = () => {
        const {droppedImages} = this.state;

        if (droppedImages.length === null) {
            return null;
        }

        return droppedImages.map((image) => {
            return <ReactCrop
                keepSelection={true}
                crop={this.state.croppedImages[image.name]}
                key={image.name}
                src={image.preview}
                onChange={this.onCropChange}
            />
        });
    };
`

This is my use case. Got multiple images and need to maintain multiple crops.

**Comment by DominicTobias** [comment]
You can move the arrow bind to your map and pass what you like there:

```js
onCropChange(crop, pixelCrop, imageName) {
...
}

renderPreview = () => {
  ...
  return droppedImages.map((image) => {
    return <ReactCrop
      ...
      onChange={(crop, pixelCrop) => this.onCropChange(crop, pixelCrop, image.name)}
    />
  });
};
```

**Comment by GoodGuyMarco** [comment]
Thank you! I'm dumb.

**Comment by DominicTobias** [comment]
No prob!
