### ISSUE TITLE
Rounding issues in getPixelCrop

### ISSUE THREAD

**Issue by MaciejM92** [DominicTobias/react-image-crop#167]
Hi, good job with the lib! I think I have an idea for improvement as it comes to outputting the pixel values in `onComplete` callback. Right now it is possible to receive boundaries outside of the original image surface:

1. Use image 1000px width and 666px tall
2. Try to crop with 16/9 ratio, full width
3. Place the crop area to the very bottom

The problem here is that when using `Math.round` you may end up with y=104px and the height=563px. This is one pixel outside the original surface. I'd suggest using `Math.floor` and `Math.ceil` instead. My suggestion would be to use floor for the x and y values while using ceil for width and height in getPixelCrop.

Let me know your thoughts.

**Comment by DominicTobias** [comment]
Hi,

Thanks for raising this good point. Your solution sounds good, or
alternatively clamping the width and height to remain in bounds as we have
the image node (clamp(x + width), imageWidth)). But off the top of my head
I think your idea would work too, will give it a think

**Comment by DominicTobias** [comment]
Should be fixed in 3.0.11

**Comment by MaciejM92** [comment]
🎉 Thank you!
