### ISSUE TITLE
Crop selection not showing on image altough  crop object looks fine

### ISSUE THREAD

**Issue by GoodGuyMarco** [DominicTobias/react-image-crop#168]
It worked before and appeared suddenly. Although my crop object looks fine
```
{
  aspect: 1.3333333333333333 
  height: 100 
  width: 88.88888888888887
  x: 0
  y: 0
}
```
the selection is not shown on the image. I'm clueless. Is it possible that it's a CSS issue or something?

**Comment by LeahAtTock** [comment]
What was your eventual solution for this?

**Comment by GoodGuyMarco** [comment]
Forgot to import the css file :laughing:

**Comment by LeahAtTock** [comment]
Haha, yup, that fixed it for me. Thanks!
