### ISSUE TITLE
Enable container zoom scaled

### ISSUE THREAD

**Issue by chemitaxis** [DominicTobias/react-image-crop#169]
Hi, we have one container that is transformed with css with scale. We need to add a delta to calculate the correct position of the mouse. I have enabled it. The PR is incoming.

Thanks.

**Comment by DominicTobias** [comment]
Hi thanks for the PR but I’m not sure if anyone else will find this useful!
Out of curiosity why are you zooming the container with css?

**Comment by chemitaxis** [comment]
For example, in our app, we have a page that have a zoom, and the container div is scaled when yo make zoom ;)

**Comment by DominicTobias** [comment]
This sounds very niche, I've not come across anyone who is using this with scale so not sure about increasing the API surface area for one use case, sorry! I'm still curious why your app has a zoom feature, the use can some the whole page in? I'm wondering why you don't make the container the width and height that you intend it to be without zooming?

**Comment by chemitaxis** [comment]
Hi Dominic! No problem, we have move the ReactCrop outside the container...
you can close the PR now. Thanks!

**Comment by DominicTobias** [comment]
Cool glad you solved it! Thanks for the PR anyway
