### ISSUE TITLE
Pass className & imageClassName as a prop ?

### ISSUE THREAD

**Issue by yashcr07** [DominicTobias/react-image-crop#171]

**Comment by philwinkel** [comment]
would be nice, i have been writing styles that overwrite the css provided with the component

**Comment by DominicTobias** [comment]
Released in v4.0.0 let me know if you have any problems, as mentioned this is only a breaking change for people who had overridden `$mobile-media-query` scss variable. However only `className` is supported, if you want to target nested items use the parent class.

**Comment by DominicTobias** [comment]
Hi `className` prop has been added, you can style elements further down based on that
