### ISSUE TITLE
No default export found in module  import/default

### ISSUE THREAD

**Issue by nypinstripes** [DominicTobias/react-image-crop#178]
Hey @DominicTobias this lib looks great & really want to use it, but when i try to import it into my components i'm getting this error

error  No default export found in module  import/default

![screen shot 2018-06-01 at 2 18 28 pm](https://user-images.githubusercontent.com/1851296/40856705-c5ec2672-65a6-11e8-9e60-55513cdb114a.png)

any advice would be appreciated thanks.

**Comment by DominicTobias** [comment]
What JS bundler are you using?

**Comment by nypinstripes** [comment]
@DominicTobias  webpack 4.10.2 , wild card import with the alias seems to give a parsing unexpected token error.

**Comment by nypinstripes** [comment]
@DominicTobias sorry that's if i use the braces, without the braces i get a no exported names found in module.
![screen shot 2018-06-01 at 2 36 15 pm](https://user-images.githubusercontent.com/1851296/40857481-49f6d1fe-65a9-11e8-9df9-55d333725002.png)

**Comment by DominicTobias** [comment]
If you console.log ReactCrop what does the browser say? There are definitely things exported from that module!

**Comment by nypinstripes** [comment]
@DominicTobias i get the RC object, maybe a linter settings issue?

<img width="1183" alt="screen shot 2018-06-01 at 2 43 28 pm" src="https://user-images.githubusercontent.com/1851296/40857817-4993c20c-65aa-11e8-824f-a976fa2d96b2.png">

**Comment by DominicTobias** [comment]
I'm quite surprised about seeing most of those there as I'm only exporting a few of them but shouldn't do harm. I can also see `default` there so I would expect `import ReactCrop from 'react-image-crop'` to also work, if you console log that does it work?

**Comment by nypinstripes** [comment]
<img width="1045" alt="screen shot 2018-06-01 at 2 48 41 pm" src="https://user-images.githubusercontent.com/1851296/40858024-f0d24e58-65aa-11e8-94c9-e7f27ed4dd5d.png">

@DominicTobias

**Comment by DominicTobias** [comment]
Ok so it's working, was wondering why more people weren't complaining 😅Seems there is something up with your eslint config. Try removing it from the project, updating eslint globally, and running `eslint --init`

**Comment by nypinstripes** [comment]
@DominicTobias that might work, but unfortunately i have to keep it in my project, for the time being im fine with just having eslint ignore the line, and continue on my way.. thanks again

**Comment by DominicTobias** [comment]
No prob

**Comment by Rasbin** [comment]
To fix by supressing this error message, the following code should work.  But, there must be other better ways to solve this.

`/*eslint-disable */`

`//suppress all warnings between comments`
`import ReactCrop from 'react-image-crop';`

`/*eslint-enable */`

**Comment by DominicTobias** [comment]
This is due to this module exporting using ES5 `module.exports`, when I tried to update it to ES6 exports it caused an issue when using this module globally so have to tread carefully. You can read about this issue here: https://github.com/benmosher/eslint-plugin-import/issues/558

Nothing is breaking but the only way to fix this is to export the module using ES6 `export`.

**Comment by DominicTobias** [comment]
Fixed in v6.0.0

**Comment by DominicTobias** [comment]
Note: import with `import ReactCrop from...` not `import * as ReactCrop from...` in v6

**Comment by enessoylu** [comment]
@DominicTobias If I am not mistaken, I have to use like this:

![image](https://user-images.githubusercontent.com/20838344/54130444-6e7ff580-4421-11e9-822c-885e3aba9686.png)

Any plan to fix type definitions?

**Comment by kieranbenton** [comment]
To @enessoylu's point, right now its not possible to import v6 through typescript as the type definitions don't match the actual shape of the library.

**Comment by JKaypa** [comment]
![image](https://github.com/sekoyo/react-image-crop/assets/109996710/c3100962-4036-4262-8eab-d4aa63608b23)
@sekoyo  I am also having this issue at this time. Do you know what is happening, any suggestion would be appreciated. Thanks

**Comment by sekoyo** [comment]
> ![image](https://private-user-images.githubusercontent.com/109996710/309438692-c3100962-4036-4262-8eab-d4aa63608b23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNTc3OTQsIm5iZiI6MTcwOTM1NzQ5NCwicGF0aCI6Ii8xMDk5OTY3MTAvMzA5NDM4NjkyLWMzMTAwOTYyLTQwMzYtNDI2Mi04ZWFiLWQ0YWE2MzYwOGIyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQwNTMxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTFlNWYzYmE5YzBiMWFjNmNkNmRjYTNiNDE5MTAzZWU5N2U3NzJiMmY2MDZiMTA5OGQ3ZGQ0ZGJhNDc1MjdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ia7P8UzRVjUILerqt4jlDnXQCXrES9k13EX2o21LpGQ) @sekoyo I am also having this issue at this time. Do you know what is happening, any suggestion would be appreciated. Thanks

What version are you using?

**Comment by JKaypa** [comment]
![image](https://github.com/sekoyo/react-image-crop/assets/109996710/2745db29-0600-41cb-b68f-9a2818c1fe79)

**Comment by sekoyo** [comment]
> ![image](https://private-user-images.githubusercontent.com/109996710/309438692-c3100962-4036-4262-8eab-d4aa63608b23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNjE2NTUsIm5iZiI6MTcwOTM2MTM1NSwicGF0aCI6Ii8xMDk5OTY3MTAvMzA5NDM4NjkyLWMzMTAwOTYyLTQwMzYtNDI2Mi04ZWFiLWQ0YWE2MzYwOGIyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQwNjM1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzg1MWE3ODRhZDAyMDJmYWNiZWRhNjE0MDAxNjU2NGZkYzQwNWQ4MTE3ZDBjZTBlNjQ3NDU2NTlhZGNhMmMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.czXycMvfFszs54Qgfa5Z44YRhfXMzBCMYH9pcWpY32k) @sekoyo I am also having this issue at this time. Do you know what is happening, any suggestion would be appreciated. Thanks

Hard to say as there is some issue with whatever you're using to compile your code. `centerCrop` is definitely exported in that version and is being used on the CodeSandbox example.

**Comment by JKaypa** [comment]
![image](https://github.com/sekoyo/react-image-crop/assets/109996710/4c805e40-6a1f-4ad8-8cb9-cba7fa53d1ea)
I had to do this. At least solved the error

**Comment by JKaypa** [comment]
Thank you for your answer and support
