### ISSUE TITLE
src not accepting blob file

### ISSUE THREAD

**Issue by michelpm1** [DominicTobias/react-image-crop#179]
Hello, I'm trying to use your component with a blob file, it's wrote in the documents it's supposed to accept it.

The problem it's not accepting. Follow my error log:

>     Types of property 'src' are incompatible.
>       Type 'Blob' is not assignable to type 'string'.

My code:

>  const cropValues = {
>         x: 20,
>         y: 10,
>         width: 30,
>         height: 10
>     };
> 
> let fileBlop = file as any as Blob;
>         const cropper = (<ReactCrop src={fileBlop} onChange={(crop: Crop) => console.log(crop)} crop={cropValues}></ReactCrop>);
>         ReactDOM.render(cropper, document.getElementById('root'));

Appreciate any help, really would like to use your component.

**Comment by DominicTobias** [comment]
Hi you need to create a url from your blob: `const blobUrl = URL.createObjectURL(blob);` and pass `blobUrl` in instead.

**Comment by michelpm1** [comment]
I add a observation to readMe file to let people know how to use the component with blob file

**Comment by DominicTobias** [comment]
Thanks but I don't want to make the Readme larger than it needs to be but I will change the wording to "blob url" from "blob path" (note I said path not object) hopefully that's obvious enough. Closing this but let me know if you have any issues using a blob url.
