### ISSUE TITLE
Crop overlay (darkened background) not showing in firefox 44.0

### ISSUE THREAD

**Issue by IljaDaderko** [DominicTobias/react-image-crop#18]
Jut tested image cropping in firefox 44, but it doesn't seem to show that dark/opaque overlay to show where image will be cropped.

**Comment by DominicTobias** [comment]
I had quite the internal debate when implementing this as I'm using the css "clip-path" property which has limited browser support. It means cleaner code as the alternative is to move 4 divs around to create the illusion. My logic was that a clipping tool is likely to be used in an admin area where you can require a modern browser.

Good news though - it seems Firefox has "moz-clip-path" so it should be an easy fix. I won't be able to fix this until I'm back from holiday in a couple of weeks though. I'll also add the MS prefixed one.

**Comment by DPr00f** [comment]
I took a look at this one. It seems that firefox supports clip-path but the element needs to be on the screen. I'll give it a go later on.

**Comment by DPr00f** [comment]
Refers to https://github.com/DominicTobias/react-image-crop/pull/20
Will be fixed in the upcoming version.

**Comment by DominicTobias** [comment]
Published
