### ISSUE TITLE
How to get the initial value of `pixelCrop` if user uses default selection

### ISSUE THREAD

**Issue by acbabis** [DominicTobias/react-image-crop#183]
In my application, I'm using `onImageLoaded` to center to the crop window on the image. It is possible that the user will not have to move the crop. If the user submits the form without clicking on the image, is there a way to get an instanceof `pixelCrop`?

**Comment by acbabis** [comment]
Figured it out. I was able to import `getPixelCrop` and invoke it in `onImageLoaded` after computing the initial value of `crop` to get the initial value of `pixelCrop`. If I made a PR for demonstrating this use case in the README.md, is it likely to be accepted?

**Comment by DominicTobias** [comment]
Thanks but no need for a PR, something like this has only come up twice in a few years. However I will document the other functions like `getPixelCrop` in the README thanks.

**Comment by kdekooter** [comment]
@acbabis @DominicTobias very interested in either the PR or the README update!

**Comment by DominicTobias** [comment]
pixelCrop is now passed to onImageLoaded so this should be easier
