### ISSUE TITLE
onError handler ?

### ISSUE THREAD

**Issue by valkheim** [DominicTobias/react-image-crop#184]
Is an `onError` handler bound to the `img` on the roadmap ?

In my application, I retrieve urls that may be wrong ad I'd like to listen to such event to display a generic image instead.

**Comment by DominicTobias** [comment]
Hi this seems like a reasonable thing to have, I'll add it in the next release. I'm on holiday from today but might have some time to do it, otherwise it will have to wait 2-3 weeks
