### ISSUE TITLE
How to programmatically set free aspect?

### ISSUE THREAD

**Issue by de83c78d1f** [DominicTobias/react-image-crop#186]
Assume I have a panel with buttons. Those buttons set aspect ratio of a crop.
For now it looks like this: I press a button, e.g. 
```jsx
<ToggleButton value={'4:3'}>4:3</ToggleButton>
```
which gives my component a value of desired aspect ratio of the crop.
Then I resolve given value to get numeric value of desired aspect, like here:
```es6
private resolveAspectRatio = (aspectRatio: string) => {
  switch (aspectRatio) {
    case '1:1':
      return 1;
    case '4:3':
      return 4 / 3;
    case '3:4':
      return 3 / 4;
    case 'free':
      return undefined;
    case 'image':
    default:
      return this.imageAspectRatio;
  }
}
```
On receiving new aspectRatio from control panel with buttons this code executes:
```es6
componentWillReceiveProps(nextProps: Props) {
  if (this.props.aspectRatio !== nextProps.aspectRatio) {
    // free aspect does not render new crop immediately
    const [aspect, x, y, height] = [this.resolveAspectRatio(nextProps.aspectRatio), 30, 30, 40];
    this.setState({crop: ReactCrop.makeAspectCrop({aspect, x, y, height}, this.imageAspectRatio)});
  }
}
```
This logic works perfectly fine and desired selection mounts immediately if I want to set up numeric aspect ratio, but if I want to programmatically set 'free' ratio through `undefined` aspect value - crop selection disappears w/o any errors, in other words - nothing is selected. Trying to select new crop with mouse indeed shows that free aspect works.
Documentation doesn't clarify how to programmatically set free aspect ratio. Is it possible to set free aspect ratio on the fly and immediately render this change?

**Comment by DominicTobias** [comment]
Hi this sounds like it could be a bug you should be able to do it. I’m away
for two weeks so I’m not going to be able to look at it until I’m back
though!

**Comment by de83c78d1f** [comment]
I guess i spotted the problem. [ReactCrop.js](https://github.com/DominicTobias/react-image-crop/blob/master/lib/ReactCrop.js#L71), function:
```es6
function makeAspectCrop(crop, imageAspect) {
  ... some logic here, omitted
  return completeCrop;
}
```
In this function lots of arithmetic operations are performed with crop.aspect, w/o check on `undefined`. Those silently return `NaN` (not sure why silently).
In my case I changed `componentWillReceiveProps` block in the following fashion:
```es6
componentWillReceiveProps(nextProps: Props) {
    if (this.props.aspectRatio !== nextProps.aspectRatio) {
      const [aspect, x, y, height, width] = [this.resolveAspectRatio(nextProps.aspectRatio), 30, 30, 40, 40];
      if (aspect) {
        this.setState({crop: ReactCrop.makeAspectCrop({x, y, height, aspect}, this.imageAspectRatio)});
      } else {
        this.setState({crop: {x, y, height, width}});
      }
    }
  }
```
Essentially I avoided using `makeAspectCrop` w/o aspect. Maybe it helps someone before this bug is resolved.

**Comment by DominicTobias** [comment]
Thanks for investigating it I’ll take a look when I’m back 👍

**Comment by DominicTobias** [comment]
This will be in the next release
