### ISSUE TITLE
pixelCrop comes back as NaN when setting initial width/height

### ISSUE THREAD

**Issue by jjm340** [DominicTobias/react-image-crop#188]
If the component is initialized with a percentage for width/height, then the second param to onChange and onComplete always comes back with all NaNs for x, y, width, and height.  What up with that?

**Comment by DominicTobias** [comment]
Hi can you post your code? Also check the working demo linked in the Readme
at the top of you’re stuck.

**Comment by jjm340** [comment]
Actually turns out we were using this incorrectly, thanks for the help!  A recommendation though:  An error message would be nice to say that the wrong values were passed and x, y, width and height can't be computed as a result.  Just my opinion.
