### ISSUE TITLE
Doesn't show anything if any parent uses `display: grid;`

### ISSUE THREAD

**Issue by niftykins** [DominicTobias/react-image-crop#189]
If there's a parent that uses `display: grid;` then this library doesn't seem to render anything. I think it may have something to do with the `max-height: -webkit-fill-available;` that's set on the img, as when I uncheck that it everything shows up.

Changing everything from Grid and adapting it to use Flexbox makes it work also.

https://codesandbox.io/s/ryz8x7j8xq

After a little more testing it appears to break in:
- Chrome Version 67.0.3396.99
- Chrome Version 68.0.3440.84

But works in:
- Firefox Version 61.0.1
- Safari Version 11.1.1

**Comment by Rainbowlemon** [comment]
I've just come across the same issue. Temporary fix was to just add `max-height: inherit`.

**Comment by DominicTobias** [comment]
Good catch, filling available height for normal situations is a good thing and fixes other issues people had so this is a shame. Will have to reproduce in a simple example and submit a bug to Chrome. As @Rainbowlemon says you can just reset that property for now.

**Comment by DominicTobias** [comment]
It looks like this is working in Chrome 71 now (perhaps earlier versions too)

**Comment by DominicTobias** [comment]
Closing due to it seeming to work in Chrome now

**Comment by kdekooter** [comment]
@DominicTobias not working yet in Chrome. I had to add the following CSS to make it work (as @Rainbowlemon pointed out):
```
.ReactCrop__image {
  max-height: inherit;
}
```

**Comment by DominicTobias** [comment]
Ah that's a shame, there's not much I can do as `fill-available` is preferred in all cases where this isn't a bug! I think for now you'll just have to turn it off with CSS as you've done.
