### ISSUE TITLE
4.0.2 Dist Build Is Broken as result of latest ES6 build changes

### ISSUE THREAD

**Issue by virgofx** [DominicTobias/react-image-crop#190]
The changes for the ES6 build no longer work when including ReactImageCrop statically

<Removing bad copy/paste ... see below>

Last working build 4.0.1

**Comment by virgofx** [comment]
Sorry wrong copy paste:

4.0.1:
```
ƒ ReactCrop() {
    var _ref;

    var _temp, _this, _ret;

    _classCallCheck(this, ReactCrop);

    for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
      args[…```

4.0.2:
```
window.ReactCrop
{ReactCrop: ƒ, default: ƒ, getPixelCrop: ƒ, makeAspectCrop: ƒ, __esModule: true}
```


Issue still persists -- the es6 changes bunked the exports all up for static includes.

**Comment by DominicTobias** [comment]
Interesting, I wonder how you would access other exports with the < 4.0.1 version e.g. `getPixelCrop`!

**Comment by virgofx** [comment]
For dist builds it needs to be accessed via property ... example below. The main export needs to be a component/function.

```jsx
render() {
    const { ReactCrop } = window;

   <ReactCrop 
        src={ .... }
        onImageLoaded={image => {
          const newCrop = ReactCrop.makeAspectCrop(
              {
                  x: 0,
                  y: 0,
                  aspect: 1,
                  width: 100,
                  height: 100,
              },
              image.width / image.height
          );
          this.pixelCrop = ReactCrop.getPixelCrop(image, newCrop);
      }} />
}
```

**Comment by DominicTobias** [comment]
Right gotcha

**Comment by DominicTobias** [comment]
Please try https://unpkg.com/react-image-crop@4.0.3/dist/ReactCrop.js @virgofx

**Comment by virgofx** [comment]
Works! TY

**Comment by virgofx** [comment]
I'm not sure what you're trying to solve .. but this isn't how the industry publishes libraries. There is best practice for proper exports such that libraries can be used universally using Webpack and rollup... if it helps you could literally clone a lot of sample libraries that offer the library flavor for plugins for react. It needs to work globally so it can be included via UMD / browser / CDN. You're basically saying I want to do something different than the other 1,000,000 *libraries* published out there. Why?  I mean look at actual React dist .. or any other library.

**Comment by DominicTobias** [comment]
I have looked at them and they are all exported as objects so actually this is going against standards:

http://jsfiddle.net/ferahl/q42wtdrg/2/

**Comment by virgofx** [comment]
I'm not sure what the standards are and I don't follow the fiddle; however, if you browse libraries .. they all export multiple types --- including a UMD .. so we need UMD so leave it .. Just add what you need without impacting anything else.

**Comment by virgofx** [comment]
The sources files don't have to change for the ES exports. Again, it can be reconfigured via rollup/ webpack.

**Comment by DominicTobias** [comment]
The modules are still exported as UMD the export style isn't under question, as my SO question demonstrates nobody has the answer except perhaps exporting many build types and hoping that compilers read the correct one, which I don't really have the inclination to do since almost nobody uses global scripts and if they do it will work but they have to add `default` to it, something you would have to do with e.g. redux-saga

**Comment by DominicTobias** [comment]
Just tried most of the most popular react libs and only one of them exports as a function (ReactGridLayout) which is also the only one that uses module.exports from what I saw - http://jsfiddle.net/ferahl/q42wtdrg/17/

**Comment by virgofx** [comment]
I wish I understood better (I'm not an export on export/import and what you're trying to achieve) ... All I know is that there should be a UMD version that is accessible to be imported via CDN (e.g. https://reactjs.org/docs/cdn-links.html) This allows application developers to **exclude** the specific librar(ies) ... and typically larger libraries from their application bundle and include it statically.  

So currently, looks like ReactCrop currently only has the UMD build in dist (https://unpkg.com/react-image-crop@5.0.0/dist/).

I think it's pretty straight forward to add additional Rollup/Webpack output type ... and then you specify the different versions that get picked up when using this library in your own application by updating the corresponding `package.json` fields which are used by different services (Rollup/Webpack/etc)

Here is an example:
https://github.com/reactstrap/reactstrap/blob/master/package.json#L5-L11


So again ... the issue isn't with removing UMD ... it's understanding what you're trying to do and what's not working in how your using this library in your separate application ... as I believe that's probably where the configuration error is.
