### ISSUE TITLE
no access to pixelCrop after setting default crop.

### ISSUE THREAD

**Issue by Osuriel** [DominicTobias/react-image-crop#192]
I need access to pixelCrop inside onImageLoaded function. how do I go about getting pixelCrop?

**Comment by DominicTobias** [comment]
Hi I've had this question before and it seems like a useful feature so as of 4.0.4 you can get it from the second parameter. Please let me know if it works/you have any issues. Thanks.

**Comment by Osuriel** [comment]
I wrote this and it worked to get the pixelCrop:

const makePixelCrop = (imageWidth, imageHeight, xPercentage, yPercentage) => {
  const pixelCrop = {};
  pixelCrop.x = (imageWidth * xPercentage) / 100;
  pixelCrop.y = (imageHeight * yPercentage) / 100;
  pixelCrop.width = imageWidth - (pixelCrop.x * 2);
  pixelCrop.height = imageHeight - (pixelCrop.y * 2);
  return pixelCrop;
};

Maybe it could help someone else.
