### ISSUE TITLE
Explodes when image loads when crop={ undefined } (before onChange fires)

### ISSUE THREAD

**Issue by grrowl** [DominicTobias/react-image-crop#193]
This is a regression since 3.0.11, and exists in 4.0.1—4.0.4:

> * While you can initially omit the crop object, any subsequent change will need to be saved to state in the onChange callback and passed here.

Initially we pass `crop={ undefined }`, and update `crop=` only after `onChange` fires. Since at least 4.0.1, `react-image-crop` will crash in `onImageLoad`'s call of `getPixelCrop(image, this.props.crop)`, because at image load time `this.props.crop` is still `undefined` (because we haven't fired `onChange` yet with that value)

**Comment by DominicTobias** [comment]
Thanks I'll put a fix in for this later today (no access to pc at the mo), this will be since 4.0.4 I think as previously pixelCrop wasn't passed to onImageLoaded

**Comment by DominicTobias** [comment]
Fixed in 5.0.0. Please try it out and let me know if you have any issues.

**Comment by grrowl** [comment]
legend, i'll try it out and report back

**Comment by DominicTobias** [comment]
Closing this as it shouldn't be exploding anymore

**Comment by grrowl** [comment]
sorry we haven't had a chance to bump it internally yet! thanks for your help :)
