### ISSUE TITLE
To further Crop the cropped image would fail all the time

### ISSUE THREAD

**Issue by bhao-speedline** [DominicTobias/react-image-crop#194]
I use the cropper in my project. When I crop the image, I draw the selected area to a canvas and then convert the canvas to a Blob. Then I use `URL.createObjectURL` to conver the Blob to a url and feed it to the cropper, so that I can further crop it. But when I try to crop it a second time, it would fail all the time. I either got a totally black image or a image that is not the area I selected. 

Does anyone know how to solve it? Or am I doing it incorrectly? Thanks!

**Comment by bhao-speedline** [comment]
@adjourn Thanks. I double checked and I'm sure the pixelCrop is correct. One thing I found is that it seems the image I got in the second crop is not a crop of the first crop, but a crop of the original image, even though the original image is replaced by the first crop. There must be a bug in my code and I will try to debug it. Thanks!

**Comment by bhao-speedline** [comment]
I think I found the issue. But I don't know how to fix it. The issue is that, when I get the cropped image, I set the src of the ImageCropper to the new cropped image. Then when I try to use `document.getElementsByClassName("ReactCrop__image")[0]` to get the image element for cropping, I still get the old image element whose src is the old image. Does anyone have any thought? Thanks!

**Comment by DominicTobias** [comment]
@bhao-speedline can you post that part of the code?

**Comment by bhao-speedline** [comment]
I found the issue. There was one line of code which I thought was commented turned out to be not. That line reset the src of the HTMLImageElement back to the original uploaded image, and that caused failure of the second crop. Thanks! @adjourn @DominicTobias

**Comment by DominicTobias** [comment]
Ok glad you found the issue, closing this now
