### ISSUE TITLE
Zoom feature?

### ISSUE THREAD

**Issue by adjourn** [DominicTobias/react-image-crop#195]
What do you guys think about zoom feature? Is it in the scope of this package? I did search around and I might not just know the correct keywords but I couldn't find any good alternatives to this package.

Example (use scrollwheel): https://fengyuanchen.github.io/cropperjs/

**Comment by adjourn** [comment]
I already tested a simplistic solution, added this to div with class `ReactCrop`:

```jsx
onWheel={(e) => {
  e.preventDefault();
  const deltaY = e.deltaY;
  if (deltaY) {
    const delta = deltaY / 1000; // either 0.1 or -0.1
    const temp = this.imgScale ? this.imgScale - delta : 1 - delta;
    this.imgScale = Math.min(Math.max(temp, this.props.minScale), this.props.maxScale); // clamp
    // no need for fancy smoothing algorithms 
    // looks great w/ simple CSS transition
    this.imageRef.style.transform = `scale(${this.imgScale})`;
  }
}}
```

Zoom works fine but selection is way off, not sure what to change (yet). My provided example is a bit misleasing, Im actually not looking for something fancy and complex, zoom from image center works fine.

**Comment by adjourn** [comment]
Closing the issue since this feature is not going to end up in `react-image-crop`.

**Comment by sdei-lovepreet** [comment]
@adjourn , we also want the zoon feature, can you please provide solution for this?

**Comment by sebaveg** [comment]
When zoom feature?

**Comment by BallerIndustries** [comment]
> When zoom feature?

Code it yourself

**Comment by FabioZan86** [comment]
I managed to combine two libraries `react-image-crop` and `cropperjs`. The first for layout and crop positioning and the second for resizing and zooming.
