### ISSUE TITLE
Draw Cropbox Based on Application's State

### ISSUE THREAD

**Issue by rwschmitz** [DominicTobias/react-image-crop#204]
Hi!

I'm using your library in an application of mine.  You have it setup such that you're creating a cropping box when a user drags either their mouse (desktop) or finger (mobile) from the start location to the end location.

I was wondering, is it possible to draw the cropbox by pointing the `this.state.crop.width` and `this.state.crop.height` to a state that exists in a higher component in my application?

**Example**
I have input fields on a form with a width and height section.  A user can type numbers into these input fields.  The numbers the user is entering into these input fields are updating state in my application `onChange`.  Right now, I'm **not** seeing any way I can have the cropbox drawn based on my state values.

The only solution I've come up with so far is to create a button in my application, write a function that takes in my width and height, and then do the following `onClick`:

```
this.setState({
  crop: {
    x: 0,
    y: 0,
    width: this.props.width,    // this is a reference to state that lives at a higher level in my app.
    height: this.props.height  // this is a reference to state that lives at a higher level in my app.
  }
});
```

**Comment by rwschmitz** [comment]
![screen shot 2018-10-03 at 5 28 39 pm](https://user-images.githubusercontent.com/30060083/46443143-dd9a4500-c731-11e8-8f9e-fee4cd413fa7.png)

So basically, when I type 75 and 90 into the fields, I would like to be able to have a cropbox automatically draw with the dimension of 75 x 90.

I'm not sure how that's possible with access to the methods you provide of `onChange` and `onComplete`.

Thank you for making a wonderful library and I hope you'll be able to provide some insight.

**Comment by DominicTobias** [comment]
Hi @rwschmitz, I would recommend shifting your state up some levels - either put it in global state (e.g. redux store), or put it higher up and pass it down as deep as you need:

- Parent - state can be here, it passes the state as `crop` and `onCropChage` and renders MiddleComponent e.g. `<MiddleComponent crop={this.state.crop} onCropChange={this.onCropChange} />`
- Middle component - your middle component can pass these props to the next component down
- Component that renders ReactCrop

If that becomes too tangled you can use global state using something like redux.

**Comment by rwschmitz** [comment]
Thank you!  I found your library to do what was needed and it is awesome.  Keep up the good work, man!  Closing.
