### ISSUE TITLE
rotate 90deg crop image on iPhone

### ISSUE THREAD

**Issue by AlexDomsn** [DominicTobias/react-image-crop#205]
The image is rotated in iPhone either in Chrome or Safari. In Android is OK in PC is OK but in iPhone the image is auto rotated 90 grades.

**Comment by DominicTobias** [comment]
As talked about here this is probably the browser ignoring xif rotation: 
https://github.com/DominicTobias/react-image-crop/issues/181

All this library is doing is putting the image in a src tag so it’s not the responsibility of this library to try and fix browser behaviour with displaying images. If you put your image in an <img> tag and look on the phone you should see the same thing. Have a look at the links in that other issue you might have to use a library to fix your image.

**Comment by DominicTobias** [comment]
I'm closing this one and keeping #181 open, if you want to add something please add it there thanks
