### ISSUE TITLE
Strange overlay issue

### ISSUE THREAD

**Issue by chrise86** [DominicTobias/react-image-crop#21]
In my app I'm getting an issue when selecting large images, where the crop doesn't match the highlight:

![screen shot 2016-02-25 at 14 33 47](https://cloud.githubusercontent.com/assets/616956/13322583/fdec85e6-dbcc-11e5-8afb-f09b4ecdffde.png)

I have set:

```
.ReactCrop--image {
  max-width: 100%;
}
```

...and have tried all sorts of combinations for crop params. Also, how do I go about selecting the default selected crop to be either 100% of width (if portrait) or 100% of height (if landscape) and keeping the aspect ratio 1/1 (square)?

**Comment by DominicTobias** [comment]
Hi can you upload that image somewhere and link it, and let me know what browser/version you're using? And are you using 0.1.1 from npm, or the latest master?

**Comment by chrise86** [comment]
Actually using it in a Meteor app so using this: https://github.com/praneybehl/meteor-react-image-crop which is a wrapper around this package - guessing it's not up to date :(

Browser is Chrome OSX 48.0.2564.116 (64-bit)

Image: http://imgur.com/5WkvIDL

**Comment by chrise86** [comment]
I've forked, updated (to npm version 0.1.1) and included the forked package in my app and still having same issue:

https://github.com/chrise86/meteor-react-image-crop/tree/react-image-crop-0.1.1

**Comment by DPr00f** [comment]
Hey @chrise86 can you try changing the css?
```
.ReactCrop--image-copy, .ReactCrop--image {
    max-width: 100%;
}
```

Seems to me that you're changing the width of the image but not the copy of it.
Let us know if that fixes it.

**Comment by chrise86** [comment]
Nice! That works, thanks!

Any idea about the other point?

> how do I go about selecting the default selected crop to be either 100% of width (if portrait) or 100% of height (if landscape) and keeping the aspect ratio 1/1 (square)?

**Comment by DPr00f** [comment]
You could preload the image and decide then what to do.
```
 var img = new Image();
    img.onload = () => {
      this.setState({
        src: src,
        ready: true,
        imageAspect: img.naturalWidth / img.naturalHeight
      });
    };
    img.src = src;
```

and on your render you could do
```
var crop = { aspect: 1 };
if(this.state.imageAspect < 1) {
   crop.width = 100;
} else {
   crop.height = 100;
}
```

Now you could pass the crop variable into ReactImageCrop

This is just a suggestion, I'm not sure it would work for you or not, but give it a go.

**Comment by DominicTobias** [comment]
Thanks @DPr00f, I've published a 0.1.3 version which has `max-width` already set to 100%, and also `onImageLoaded` passes a second arg - `image` (the DOM element of the image). So you should be able to do the first part of the code @DPr00f posted in that callback. Let us know how it goes.

**Comment by chrise86** [comment]
Brilliant thanks!

**Comment by chrise86** [comment]
Sorry, I must be missing something, how do you capture the cropped image? I.e. how would I then upload the cropped image to somewhere like S3?

**Comment by DominicTobias** [comment]
@chrise86 this tool (like others) is just for selecting a crop - the actual cropping is normally done by a backend when the crop parameters are sent over. There are some services which offer specifically that e.g. https://www.imgix.com/ but normally backend languages like java or node had libraries which can do it too

**Comment by DPr00f** [comment]
The library doesn't have any code for upload. Although you could pick up the base64 and send it for S3.
Take this as an example
```
  onCropComplete(crop) {
    this.previewImage(crop).then((canvasUrl) => {
        ApiActions.uploadBase64(canvasUrl, this.getDraftUploadFileName(true));
    });
  }

previewImage(crop) {
    return new Promise((resolve, reject) => {
      var img = new Image();
      img.setAttribute('crossOrigin', 'anonymous');
      img.onload = () => {
        var imageWidth = crop.originalWidth;
        var imageHeight = crop.originalHeight;

        var cropX = (crop.x / 100) * imageWidth;
        var cropY = (crop.y / 100) * imageHeight;

        var cropWidth = (crop.width / 100) * imageWidth;
        var cropHeight = (crop.height / 100) * imageHeight;

        var destWidth = cropWidth;
        var destHeight = cropHeight;
        var canvasWidth = cropWidth;
        var canvasHeight = cropHeight;

        if(crop.maxWidth || crop.maxHeight) {
          var scaledCrop = this.scale({
              width: cropWidth,
              height: cropHeight,
              maxWidth: crop.maxWidth * 2,
              maxHeight: crop.maxHeight * 2
          });

          // Scale the image based on the crop scale.
          var scaledImage = this.scale({
              scale: scaledCrop.scale,
              width: imageWidth,
              height: imageHeight
          });
          destWidth = scaledCrop.width;
          destHeight = scaledCrop.height;
          canvasWidth = scaledCrop.width;
          canvasHeight = scaledCrop.height;
        }

        var canvas = document.createElement('canvas');
        canvas.width = canvasWidth;
        canvas.height = canvasHeight;
        var ctx = canvas.getContext('2d');
        ctx.drawImage(img, cropX, cropY, cropWidth, cropHeight, 0, 0, destWidth, destHeight);
        var canvasUrl = canvas.toDataURL('image/png');
        resolve(canvasUrl);
      }
      img.src = this.state.originalImageUrl;
    });
  }

scale(options) {
    var scale = options.scale || Math.min(options.maxWidth/options.width, options.maxHeight/options.height);

    scale = Math.min(scale, 100);

    return {
      scale: scale,
      width: options.width * scale,
      height: options.height * scale
    };
  }
```

Please note than my crop object contains the `originalImageWidth` and `originalImageHeight` so you need to workout those yourself, also it might contain a `maxWidth` and a `maxHeight`

and here's my code for the upload of the base64

as an action I have
```
uploadBase64: function uploadBase64(base64, name = "test.png", type = "image/png") {
    ApplicationDispatcher.dispatch({
      actionType: ApplicationEvents.UPLOAD_BASE64,
      base64: base64,
      name: name,
      type: type
    });
  }
```

and in the store I have

```
uploadBase64(base64, name, type) {
    request.post('/api/sign/s3')
           .send({
             name: name,
             type: type,
             encoding: "base64",
             imageBinary: base64
           })
           .set('Accept', 'application/json')
           .end((err, res) => {
             if(this.hasError(err, res)) {
               this.emit(ApplicationEvents.FAILED_BASE64_UPLOAD, { name: name });
               return;
             }
             this.emit(ApplicationEvents.UPLOADED_BASE64, { name: name, url: res.body.url });
           });
  }
```

Let me know if you want the backend code as well, I'm happy to share it

**Comment by chrise86** [comment]
Wow thanks very much, I'll need some time to look this over! I think my main issue was not really knowing how to grab the image (with the new crop dimensions).

**Comment by DPr00f** [comment]
If you're doing cropping on the frontend you should really keep the image info.
