### ISSUE TITLE
[Feature Request] Keep image mime type

### ISSUE THREAD

**Issue by alkunjo** [DominicTobias/react-image-crop#212]
Hi @DominicTobias, thank you for the awesome works you had done. Since it helps me a lot on my react project :smile: 

I was wondering is it possible for me to get the loaded image which I got from **onImageLoaded** event will return the loaded image as it is?
For example I try to input the **GIF** and **JPEG** image, when the image is loaded the mime type is changed to **PNG**. What I expect is that the loaded image will have the same mime type as its origin image. Thank you

**Comment by DominicTobias** [comment]
Hi and thanks, I'm not sure what the browser does here but the library is just putting the source into img `src` tag and the onLoad event comes from the browser, I doubt I can change that. What code are you using to get the mime type? I'm wondering if there is a discussion about this somewhere else.

**Comment by alkunjo** [comment]
I currently knowing that the mime type is always **PNG** after the image is loaded because I check on the image `src` which the source is a base64 decoded image with prefix like this 
```
data:image/png;base64,R0lGODlh4AFAAff...ZM51lx8Q7EKPAtbHntSAAAA7
```
If that seems not possible, I'll try to change the mime type after the image loaded with the state with  then and see if it works

**Comment by DominicTobias** [comment]
How are you converting your image to base64? I ask because if you use toDataURL without specifying mime type it defaults to PNG

**Comment by alkunjo** [comment]
Hi @DominicTobias, I finally found the answer. It's actually my fault that I didn't recheck it sequentially on my code. I was assuming that when the image is loaded, it was your code that changes it into PNG base64 image. Yet when I inspect it by searching images on Google Image and use its **Copy Image** features and paste it into my **dropfile-like** component, Google provides it in PNG base64 image. 
I'm so sorry for my inaccuracy on checking my code, so I'll close this issue. Thank you very much for your response and assistance 😄 👍

**Comment by DominicTobias** [comment]
Glad you found the cause, out of curiosity is it the code from my sandbox link/demo folder which takes a local file?
