### ISSUE TITLE
pixelCrop on onImageLoaded is undefined

### ISSUE THREAD

**Issue by tayan-serna** [DominicTobias/react-image-crop#214]
I try to use the pixelCrop to set an initial state on the image just if the people doesn't want to do a new crop.
To do that I would like to use the pixelCrop instead of the image.naturalHeight/Width.

Here is an example of the solution and the logging result in google chrome

![image](https://user-images.githubusercontent.com/11379127/47514269-904b5800-d845-11e8-8100-5e55451f3a58.png)

![image](https://user-images.githubusercontent.com/11379127/47514138-4bbfbc80-d845-11e8-8c5e-efe66a4c8d0d.png)

**Comment by DominicTobias** [comment]
Hi, what's your question, why `pixelCrop` is undefined? It is undefined if you don't pass a crop into the component when you initialise it.

**Comment by tayan-serna** [comment]
I'm trying to get an initial `pixelCrop`, so if the people don't change the current crop I could obtain a preview image.
I do actually have an initial crop
![image](https://user-images.githubusercontent.com/11379127/47531292-cb17b500-d872-11e8-8b56-5e58cf5f651e.png)

**Comment by DominicTobias** [comment]
And you're setting `crop` on `ReactCrop` right? Refer to this working demo, look at the console log: https://codesandbox.io/s/mzjzvol4zy

**Comment by anubhavr19** [comment]
Please pass the **crop** props to the component like this **undefined** not showing in **console.log()**
```
<ReactCrop
            src={this.state.src}
            crop={this.state.crop}
            onImageLoaded={this.onImageLoaded}
            onComplete={this.onCropComplete}
            onChange={this.onCropChange}
          />
```

You dont need set initial crop you just put crop inside state like this
this.state{( 
```
crop: {
 aspect: 1,
      height: 100,
      width: 100,
      x: 0,
      y: 0,
    }
)}
```

**this.state.crop** will set your initial frame height, width, x, and  y

**Comment by tayan-serna** [comment]
I already doing that.
![image](https://user-images.githubusercontent.com/11379127/47573436-edf1aa00-d902-11e8-9ca9-9a5b6910e5cd.png)

![image](https://user-images.githubusercontent.com/11379127/47573416-e16d5180-d902-11e8-9add-2b3c6e708757.png)

**Comment by DominicTobias** [comment]
Please make a reproducible version of your issue on the sandbox as it should be literally impossible for pixelCrop to be null unless your crop is falsy - https://github.com/DominicTobias/react-image-crop/blob/master/lib/ReactCrop.js#L95

**Comment by DominicTobias** [comment]
I'm going to close this due to inactivity. This code has changed slightly in latest patch releases, but reviewing it again (see link above), pixelCrop should not be null if a crop is provided.

**Comment by rahulupadhyay** [comment]
Hello @DominicTobias, I have the same issue with pixelCrop undefined. 

Can you please help me out here? 

This is my component setup: 

	<ReactCrop
		src={imgSrc}
       	crop={this.state.crop}
      	onImageLoaded={this.handleImageLoaded}
      	onComplete={this.handleOnCropComplete}
      	onChange={this.handleOnCropChange}/>

Where crop has been defined as: 

	
    crop: {
    	aspect: 1,
    	height: 512,
    	width: 512,
    	x: 0,
    	y: 0
    }

OnCropComplete, I am logging the CROP and PIXELCROP, 

    handleOnCropComplete = (crop, pixelCrop) => {
	    console.log(crop, pixelCrop);
    	const canvasRef = this.imagePreviewCanvasRef.current;
    	const {imgSrc} = this.state;
    	// image64toCanvasRef(canvasRef, imgSrc, pixelCrop);
    };

here, pixelCrop is always "undefined".
