### ISSUE TITLE
"Maximum call stack exceeded" error on iOS Safari

### ISSUE THREAD

**Issue by tudorpavel** [DominicTobias/react-image-crop#217]
Version: 6.0.7

Steps to reproduce:
  - open demo on iOS Safari (I'm using an iPhone 6 with iOS 11.4.1)
  - upload an image
  - click "Change to 16/9 aspect" button
  - play around with the resize
  - notice that page starts freezing up

Using USB debugging on macOS Safari I was able to identify the error as:
> RangeError: Maximum call stack size exceeded.

![screen shot 2018-11-14 at 17 23 09](https://user-images.githubusercontent.com/2506871/48492749-2239f580-e833-11e8-94e8-f18051582acd.png)

I'm not exactly sure what could be the cause of this, but it seems to me like a classic React infinite render loop so it might be related to [componentDidUpdate](https://github.com/DominicTobias/react-image-crop/blob/master/lib/ReactCrop.js#L199).

**Comment by DominicTobias** [comment]
Thanks @tudorpavel, I was afraid of this after I made the update there. I will see if I can see why but otherwise I have an idea to change that code to make it safer.

**Comment by tudorpavel** [comment]
Indeed, it's most likely a regression caused by the fix for #206. I cannot reproduce this issue on version 6.0.4.

**Comment by DominicTobias** [comment]
Fixed in 6.0.8
