### ISSUE TITLE
"Maximum update depth exceeded" when clicking the image

### ISSUE THREAD

**Issue by djorak** [DominicTobias/react-image-crop#218]
I have been getting this error and it looks like it was introduced recently. At first I assumed it was an issue in my local setup, but I can reproduce it in the demo.

It seems to come from the fact that the `onChange` gets called in an infinite loop.

- Version: 6.0.7
- Steps to reproduce:
    1. open demo (Tried in Firefox and Chrome)
    2. upload an image
    3. click anywhere in the image
    4. notice React Error
- Error:
> Invariant Violation
> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

![image](https://user-images.githubusercontent.com/2163258/48494170-337c0580-e825-11e8-974d-bfa900a73d70.png)

**Note:** rolling back to v6.0.5 fixes it.

**Comment by DominicTobias** [comment]
Hi this should be fixed in 6.0.8 please give it a go

**Comment by djorak** [comment]
Thank you, 6.0.8 fixed it. 🙂

**Comment by DominicTobias** [comment]
Great thanks for checking

**Comment by noashka** [comment]
Hello. I have the same problem. When I upload an image in the first time and trying change cropp size I have this error. I took code from the demo folder 
react 16.6
react-image-crop 6.0.11

But when I downgrade module version to 6.0.8 it works fine

**Comment by DominicTobias** [comment]
@noashka thanks can you please let me know the dimensions of the image you tried and also the crop settings? And does it happen every time when you try to resize the crop?

I will take a look at it this evening

**Comment by noashka** [comment]
I used a simple jpeg image, 435x512px.
I used example [code](https://github.com/DominicTobias/react-image-crop/blob/master/demo/demo.js) from the demo folder. Without anything changes
If I use initial crop area, I get an error.
If I set new crop area, all works fine

**Comment by DominicTobias** [comment]
Thanks @noashka, if you get a moment I'm curious if you get the same error on https://codesandbox.io/s/72py4jlll6

**Comment by noashka** [comment]
@DominicTobias yes, I get the same error

**Comment by DominicTobias** [comment]
Thanks, interesting I can't actually replicate but I've seen it before but not sure what I did. I choose an image and then play around with moving and resizing and didn't manage to break it yet.

**Comment by DominicTobias** [comment]
@noashka Please try 6.0.12 this issue should be fixed now. It was proving too problematic to try and fix/complete invalid aspect crops every component update/render, so I just fix/complete them if they are incorrect on image load

**Comment by noashka** [comment]
@DominicTobias You've fixed it! Thank you for help!

**Comment by DominicTobias** [comment]
Great thanks for checking
