### ISSUE TITLE
Compatibility with react-modal on iOS

### ISSUE THREAD

**Issue by tudorpavel** [DominicTobias/react-image-crop#219]
I couldn't find any previous discussion on this, so I will start one here.

Our use case involves adding ReactCrop inside a [react-modal](https://github.com/reactjs/react-modal) and we noticed that ReactCrop does not work properly on iOS when placed inside a modal. Basically, the crop rectangle disappears.

I'm not sure what could be causing this, but my guess is that on iOS Safari the `getElementOffset` code works unexpectedly because of the way the modal is positioned? I'm going to try to debug this further tomorrow.

I've modified the demo to include a modal for debugging purposes:
https://github.com/Camversity/react-image-crop/tree/debug-modal

Any thoughts on this?

**Comment by DominicTobias** [comment]
Hi, are you running this on a mobile phone from a server by any chance?

**Comment by tudorpavel** [comment]
The demo? Yep, I'm using [serve](https://www.npmjs.com/package/serve) to open the demo on a mobile phone:
```
yarn global add serve
cd react-image-crop
serve -s .
```

And then using my local IP and port `5000` on the device.

**Comment by DominicTobias** [comment]
Then please pull the latest master and npm install, otherwise you don't get ReactCrop.css because the relative path to it `../dist/ReactCrop.css` doesn't work when running a server. After that it should be fine in a modal.

**Comment by tudorpavel** [comment]
I did have that problem initially because I used `serve` with just the `demo/` folder, but after that I made sure the CSS is loaded properly by serving the entire repo folder. The crop rectangle appears initially but the problems start when trying to move/resize it.

Regardless, we first noticed these issues in our app which uses [create-react-app](https://github.com/facebook/create-react-app).

**Comment by DominicTobias** [comment]
Hm strange, your fork works fine for me if I npm start and then open demo/index.html, even after moving, resizing etc

**Comment by tudorpavel** [comment]
Did you try it on an iPhone with Safari? It works fine everywhere else, as is usually the case with Safari... :cry:

**Comment by DominicTobias** [comment]
I did just try updating your branch against master so that it has the change in demo.js at the top `import '../dist/ReactCrop.css';` and then I ran a simply python server `python -m SimpleHTTPServer 3636` inside the demo folder:

![ios](https://user-images.githubusercontent.com/760314/48503255-865fb800-e839-11e8-9c51-228ee764c05c.png)

**Comment by tudorpavel** [comment]
Hmm, interesting... It's true I tested it with 6.0.7 earlier when I was still in the office but now I don't have an iPhone with me.

I will check again tomorrow morning, thanks!

We can close this for now.

**Comment by tudorpavel** [comment]
To follow up, I have it working as expected in the demo. The popup in our app still behaves strangely on small screen (iPhone) even though it works as in the demo on large screen (iPad). I will have to investigate it further in our setup.

**Comment by tudorpavel** [comment]
I've finally gotten to the bottom of this... The weird behavior was in fact due to 2 issues:

1. My mistake from #220: I was setting all `width`, `height` and `crop`. The solution was to set initial values only for `width` and `crop`, while setting `height: null`.

2. Issues with EXIF orientation discussed in #205 and mentioned in the README (I should've [RTFD](https://www.urbandictionary.com/define.php?term=RTFD)), I was calculating the image `width` and `height` in memory with the uploaded [File/Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) using [this naive approach](https://gist.github.com/schabluk/808f8691720d3a0e0e200a333bc61ecc). I needed to do this before rendering `ReactCrop`. My photo was landscape in memory and portrait in ReactCrop due to EXIF orientation. The solution was to use [blueimp-load-image](https://github.com/blueimp/JavaScript-Load-Image/) to load the image in memory with `orientation: true`:

```js
const getImageDimensions = (imageFile) => {
  return new Promise((resolve) => {
    loadImage(
      imageFile,
      (img) => {
        resolve({ width: img.width, height: img.height });
      },
      {
        orientation: true
      }
    );
  });
};
```

@DominicTobias thanks for this library and thanks for your help!

**Comment by DominicTobias** [comment]
Ok great glad you got it working 👍

**Comment by DominicTobias** [comment]
Ps I’m thinking about maybe making the drag handles slightly larger for
touch devices, if you have trouble dragging them let me know. Another guy
was saying his users in user eating found it hard (they are only 9x9 atm I
think)

**Comment by tudorpavel** [comment]
> Ps I’m thinking about maybe making the drag handles slightly larger for touch devices, if you have trouble dragging them let me know.

Sure, I guess it couldn't hurt to have them larger to improve the UX on touch devices. :+1:

**Comment by osdiab** [comment]
@DominicTobias assuming drag handles aren't larger yet, is there a way to configure them to be larger?

**Comment by DominicTobias** [comment]
They are larger now but if you want to adjust them further the easiest way is to set some sass variables before importing the file - https://github.com/DominicTobias/react-image-crop/blob/master/lib/ReactCrop.scss#L11 but you can also just override in CSS too. Probably the experience can be optimised further for mobile as discussed here - https://github.com/DominicTobias/react-image-crop/issues/201
