### ISSUE TITLE
Sandmox demo - On click crash

### ISSUE THREAD

**Issue by YoshiYo** [DominicTobias/react-image-crop#221]
Hey, 

I used your sandbox to better understand your package.
Indeed, if you click away on the image outside the selection box, the code crash because the blob is empty.

I just add an "if" to handle the problem. If you have a better way to achieve this, tell me. 
```
return new Promise((resolve, reject) => {
      canvas.toBlob(blob => {
        if (blob) {
          blob.name = fileName;
          window.URL.revokeObjectURL(this.fileUrl);
          this.fileUrl = window.URL.createObjectURL(blob);
          resolve(this.fileUrl);
        }
      }, "image/jpeg");
    });
  }
```

This is the new sandbox url updated : https://codesandbox.io/s/y0yqnowlpx

**Comment by DominicTobias** [comment]
Hi, thanks I noticed this but didn't get around to fixing it. It happens when the crop width and height is 0 so it can be caught a bit higher up the food chain. I've updated the sandbox now.

```js
onCropComplete = async (crop, pixelCrop) => {
    if (crop.width && crop.height) {
      const croppedImageUrl = await this.getCroppedImg(
        this.imageRef,
        pixelCrop,
        "newFile.jpeg"
      );
      this.setState({ croppedImageUrl });
    }
  };
```

**Comment by YoshiYo** [comment]
Hi @DominicTobias,

Thank you for your answer. 
Yes, when I wrote this, I was : "Okey, I know it's not the best idea but ok, it's seems working".

I updated my code with your tip.

Thanks you 🚀
