### ISSUE TITLE
Specifying aspect with only width or height does not initialize the cropper area

### ISSUE THREAD

**Issue by avo** [DominicTobias/react-image-crop#224]
Your documentation specifies that when using aspect to only specify width OR height (or neither). Currently, when passing in the following crop, no cropper area is initialized but it does draw the cropper with aspect appropriately. If I pass both a height and a width than the cropper area is displayed but then the aspect isn't necessarily correct (based on the image dimensions) since width and height are percentages. 

```
crop: {
  aspect: 1,
  width: 50,
  x: 0,
  y: 0
}
```

If I remove aspect and specify width, height, x and y than the cropper area initializes correctly. This is working as expected.

We used to be able to display an initial cropper area with aspect ratio but this doesn't seem to be the case anymore.

**Comment by DominicTobias** [comment]
Hi, can you clarify what you mean by this bit "no cropper area is initialized but it does draw the cropper with aspect appropriately."?

If you take a look over here it does draw an aspect on the image you load in: https://codesandbox.io/s/72py4jlll6

**Comment by avo** [comment]
Your example does appear to load the image with the crop area initially on it. I had run a basic test specifying only two props (src and crop) where the src was hard coded as a string and the crop similar to the above with aspect ratio and it did not load initially with the crop area; I had to drag to crop.

**Comment by DominicTobias** [comment]
Hm are you able to replicate with this? https://codesandbox.io/s/k3233k2ov3

**Comment by avo** [comment]
I dug into it further and noticed that I was not using the latest 6.x.x version. After updating, I was able to track down the bugs on our end. We have an avatar component that utilizes a cropper component which wraps this cropper. We had a few issues: one was that we were declaring with and height with the aspect which caused the aspect to not be the expected value and we did not have x and y declared which for some reason caused the cropper area to not be movable. Then within the cropper code, we were calling getPixelCrop directly within onImageLoaded and it was returning NaN when our crops had aspect and only one dimension specified. I saw from your example that pixelCrop is passed into onImageLoaded, so removed that direct call. The final thing that was causing the preview to not have a cropper initially was because we were calling onChange(crop, pixelCrop) again from onImageLoaded and it seemed to be resetting the crop width/height with the initial values again. I'm not sure why the initial test I ran directly using ReactCrop with a static src, hardcoded crop, and empty change function did not render properly with the initial crop but it was likely something I did on my end. Thanks for your time!

**Comment by DominicTobias** [comment]
Ok glad you fixed it! I would like to automatically fix invalid crops in the future even if both width and height are specified, I wrote the code tonight but just need to test it carefully as it's quite easy to cause an infinite loop.
