### ISSUE TITLE
Transparency support

### ISSUE THREAD

**Issue by michaelpeterlee** [DominicTobias/react-image-crop#227]
Transparencies display black in <ReactCrop /> component and the cropped result image.

Cool library thank you.

**Comment by DominicTobias** [comment]
Hi, it just renders the src you pass to it, my guess is that you’re taking
a file input and converting it to JPG, and the crop example I provided also
coverts to JPG if I recall but you can change the png easily it just makes
the conversion slower.

**Comment by michaelpeterlee** [comment]
That works excellent thank you, sorry to not review further before posting.
