### ISSUE TITLE
Changing crop-selection css

### ISSUE THREAD

**Issue by jbpadilha** [DominicTobias/react-image-crop#228]
How Can I change ReactCrop__crop-selection  css ? I'd like to add border-radius:50% to looks like a circle.
![screen shot 2018-12-07 at 2 40 37 pm](https://user-images.githubusercontent.com/29067407/49669057-173b4500-fa2e-11e8-9098-c7ce2517ce2e.png)

**Comment by DominicTobias** [comment]
Hi, you can just override the CSS or pass in a custom class with the `className` prop and override with that.

**Comment by DominicTobias** [comment]
Closing, if you have any questions let me know

**Comment by AdriaRios** [comment]
Hi @DominicTobias,
Imagine I want to render circle or rectangle depending on the case. How can I do that? I could override the CSS but I don't know how to apply on or another, I don't see any way pass that info down.

Thank you!

**Comment by DominicTobias** [comment]
@AdriaRios you can pass in different class names if you want to render a circle or not to `className` and style the css from that

**Comment by AdriaRios** [comment]
Hi @DominicTobias, I don't know how to do id. The className are defined inside the component:

```<div
        ref={(n) => { this.cropSelectRef = n; }}
        style={style}
        className="ReactCrop__crop-selection"
        onMouseDown={this.onCropMouseTouchDown}
        onTouchStart={this.onCropMouseTouchDown}
        role="presentation"
      >
```

I would like to Edit or extend `ReactCrop__crop-selection`, how can I do it? I don't see any dynamic class in the code.

Maybe I am missing something

**Comment by MetaMmodern** [comment]
For anyone who finds this thread: module css is not working, you have to create a simple .css file and import it into your component as a file(the same way it is imported in documentation tutorial).

**Comment by MetaMmodern** [comment]
@DominicTobias is there a way for people to not import the css file provided by library? It looks a bit odd to use component this way(although I know that it's a common way in small libraries). I'm guessing that it's a way to provide user's full customization opportunity, but I may be wrong.

**Comment by DominicTobias** [comment]
@MetaMmodern a javascript style library is too big and opinionated for this - even a relatively lightweight one like Emotion is ~6 times bigger than the library itself. Also they are more likely to cause issues than plain old CSS e.g. version conflicts, SSR issues etc. Also many like Emotion do not support Preact properly or in a suboptimal way and this lib support Preact. I don't think it's too much hassle to add an import statement for the .css and it keeps the library lightweight and free of potential issues around CSS-in-JS. Storybook for example has had many issues with conflicts between using an older version of Emotion and users using a newer one.

**Comment by MetaMmodern** [comment]
> @MetaMmodern a javascript style library is too big and opinionated for this - even a relatively lightweight one like Emotion is ~6 times bigger than the library itself. Also they are more likely to cause issues than plain old CSS e.g. version conflicts, SSR issues etc. Also many like Emotion do not support Preact properly or in a suboptimal way and this lib support Preact. I don't think it's too much hassle to add an import statement for the .css and it keeps the library lightweight and free of potential issues around CSS-in-JS. Storybook for example has had many issues with conflicts between using an older version of Emotion and users using a newer one.

@DominicTobias I don't mean obscure solutions like emotion, makeStyles or jss. I meant plain module css(Or module scss, since you're already using scss). In our project using webpack(or Vite) it usually builds into js anyway. And later when someone uses it he just needs to import component and that's it. Your library, on the other hand, requires to import css that is being generated by your build tool. I don't mean that second approach is worse, just that it requires one more action from user to set all up. What do you think?
