### ISSUE TITLE
onImageLoaded function signature incorrect

### ISSUE THREAD

**Issue by SunskyXH** [DominicTobias/react-image-crop#229]
![image](https://user-images.githubusercontent.com/10584186/49869187-a095b180-fe4a-11e8-88e5-305a7355af59.png)

in your demo:
![image](https://user-images.githubusercontent.com/10584186/49869228-c1f69d80-fe4a-11e8-87a1-989a62e82e8c.png)

**Comment by DominicTobias** [comment]
Closing as this has since been updated, also I don't maintain the types for this package
