### ISSUE TITLE
Crop Image Not working in IE

### ISSUE THREAD

**Issue by kasturichavan** [DominicTobias/react-image-crop#231]
Not able to crop an image in IE. It doesnt pop up a cropping area on the action.

**Comment by DominicTobias** [comment]
And what version of IE would that be? It wasn't my aim to supporting IE but I can see if it's something obvious. I don't have IE or Windows to test a fix.

**Comment by DominicTobias** [comment]
Closing due to needed details not provided

**Comment by ParthPatel-DA** [comment]
Not able to crop an image in IE.

**Comment by DominicTobias** [comment]
@ParthPatel-DA sorry the library doesn't support IE. People have made PRs for IE stuff before so I thought it was working but I don't provide any guarantee
