### ISSUE TITLE
not enforcing width and cursor stuck on "move"

### ISSUE THREAD

**Issue by BernardA** [DominicTobias/react-image-crop#236]
A couple of issues:
- following your docs I attempted to set aspect ratio and limit the width of the image, which is for user profile, with the code below on '`this.state`:
 
    `   crop: {
                width: 250,
                aspect: 3/4,
            },` 
It does enforce aspect ratio but not the width. I also tried with `maxWidth`. Not sure what `maxWidth` is supposed to do, as it says ` as a percentage of image width`. Normally one would be looking for an absolute value, without any relation to the size of the original image.

- user experience is not optimal when resizing. Well, it's pretty bad really. As the user selects the image - in my case with the regular `input type=file` = it gets stuck with the element that has `cursor: move` and it takes some clicking around to have it change to `cursor: crosshair`.  I tested it on both Mac/Firefox and Mac/Chrome. Not on mobile at this stage.

The images below is inspection for the initial `cursor: move` element:

![screen shot 2019-01-27 at 09 57 30](https://user-images.githubusercontent.com/9449665/51800427-b1e62200-222e-11e9-9957-455abf7f8e6b.png)

And then, eventually it gets to this, which is the desired state:

![screen shot 2019-01-27 at 09 58 10](https://user-images.githubusercontent.com/9449665/51800435-e22dc080-222e-11e9-853c-61e10fd90bca.png)

Some of the code:
I used [this tutorial ](https://www.youtube.com/watch?v=xZdqRobTBXk&list=PLEsfXFp6DpzQbwYDx1zgcKJ4tzyWFaESK&index=29) as reference. 

     constructor(props){
        super(props);
        this.imagePreviewCanvasRef = React.createRef();
        this.state = {
            selectedFile:'',
            selectedFileMimeType:'',
            imageUploadResponse: [],
            uploadErrors: [],
            getProfileResponse: {},
            isActiveChangeAddressForm: false,
            crop: {
                width: 250,
                aspect: 3/4,
            },
            notification: {
                status: '',
                title: '',
                message: '',
                errors: {}
            }
        }
    }

      handleFileSelected =  (event) => {
        console.log('event target file',event.target.files[0] )
        let file = event.target.files[0];
        let errors = [];
        if (!ACCEPTED_MIME_TYPES.includes(file.type)) {
            errors.push('Invalid file type. Only jpeg and png accepted');
        }
        if (file.size > UPLOAD_MAX_SIZE) {
            errors.push('File size is bigger than allowed( 2MB )');
        }
        this.setState({uploadErrors: errors});
        if (errors.length === 0) {
            const myFileReader = new FileReader();
            myFileReader.addEventListener("load", () => {
                this.setState({
                    selectedFile: myFileReader.result,
                    selectedFileMimeType: file.type,
                })
            }, false)
            myFileReader.readAsDataURL(file)
        }
    }

        handleCropChange = (crop) => {
        this.setState({crop})
    }

    handleCropComplete = (crop, pixelCrop) => {
        const canvasRef = this.imagePreviewCanvasRef.current;
        image64toCanvasRef(canvasRef, this.state.selectedFile, pixelCrop);
    }

    handleImageUploadFormSubmit = event => {
        event.preventDefault();
        this.setState({imageUploadResponse: {}});
        const fileExtension = extractImageFileExtensionFromBase64(this.state.selectedFile);
        const filename = `filename.${fileExtension}`;
        let croppedFile = this.imagePreviewCanvasRef.current.toDataURL(this.state.selectedFileMimeType);
        croppedFile = base64StringtoFile(croppedFile, filename);
        const formData = new FormData();
        formData.append('form[imgFile]', croppedFile);
        let submitForm = new Promise((resolve) => {
            resolve(this.props.actionUploadImage(formData));
        });

        submitForm.then((result) => {
       .........
     
     	render() {
		return (
             <ImageUploadForm 
                        handleFileSelected = {this.handleFileSelected}
                        handleDeleteFileSelected={this.handleDeleteFileSelected}
                        handleImageUploadFormSubmit = {this.handleImageUploadFormSubmit}
                        uploadErrors = {this.state.uploadErrors}
                    />
                        {
                            this.state.selectedFile != '' ?
                                <div>
                                    <ReactCrop 
                                        src={this.state.selectedFile} 
                                        crop={this.state.crop} 
                                        onChange={this.handleCropChange}
                                        onComplete={this.handleCropComplete}
                                    />
                                    <div>
                                        <canvas ref={this.imagePreviewCanvasRef}></canvas>
                                    </div>
                                </div>
                            : null
                        }

**Comment by DominicTobias** [comment]
Hi, all widths are in percentages so nothing should be set over 100%. This is the inconvenient tradeoff of having responsive out the box without detecting window or image element resizes and manually adjusting all values.

So you can calculate the maximum possible width as a percentage in `onImageLoaded` as this passes the image element and set the crop there if you want to set a percentage based on a pixel limit.

If you try attaching an image here do you get cursor issues? https://codesandbox.io/s/72py4jlll6

**Comment by BernardA** [comment]
Hi. Thanks for prompt reply. I believe I understand how the width works. I will get the width on `handleFileSelected` above and update ` this.state{crop: {width.`,  with the calculation to get the desired absolute pixel value, correct?

Concerning the cursor, it works fine on your sandbox. I noticed that you have an initial crop area. Is that the solution and where is that accomplished?

**Comment by BernardA** [comment]
Actually having an initial cropped area - besides solving the cursor issue - is also a good UI, as it gives a visual clue of what she/he is expected to do. 
The width also works beautifully. Great!
Many thanks.
