### ISSUE TITLE
Make the natural image dimensions optional

### ISSUE THREAD

**Issue by chrisronline** [DominicTobias/react-image-crop#243]
I have a use case where the natural dimensions of an image (introduced by #122) are causing the numbers in my pixel crop to be slightly off. This is fixed by using the images `width` and `height` instead of the natural dimensions. Is it possible to make this an optional thing? Perhaps a prop that defaults to true but can be turned off?

**Comment by DominicTobias** [comment]
Hi, seems like a reasonable thing to add. I remember when merging this I wasn't sure if it was going to fit all use cases.

**Comment by chrisronline** [comment]
@DominicTobias Sounds good. I made the PR: #244

**Comment by DominicTobias** [comment]
Published in 6.0.16

**Comment by chrisronline** [comment]
You rock! Thanks so much!
