### ISSUE TITLE
 how can i skip the onChange and onComplete call in onImageLoad function?

### ISSUE THREAD

**Issue by xwillmadeit** [DominicTobias/react-image-crop#245]
I have some code like this below

```js
calculateMyCropData = ({ naturalWidth, naturalHeight }, pixelCrop) => {
    const { limitSize } = this.props

    const pixelWidth = limitSize
      ? Math.min(limitSize.width, naturalWidth)
      : pixelCrop.width
    const pixelHeight = limitSize
      ? Math.min(limitSize.height, naturalHeight)
      : pixelCrop.height

    const width = (pixelWidth / naturalWidth) * 100
    const height = (pixelHeight / naturalHeight) * 100

    const x =  50 - width / 2
    const y =  50 - height / 2

    return {
      crop: {
        x,
        y,
        width,
        height
      },
      pixelCrop: {
        width: pixelWidth,
        height: pixelHeight,
        x: Math.ceil((x * naturalWidth) / 100),
        y: Math.ceil((y * naturalHeight) / 100)
      }
    }
}

onImageLoaded = (image, pixelCrop) => {
    const { crop, pixelCrop: computedPixelCrop } = this.calculateMyCropData(
      image,
      pixelCrop
    )

    /** 
     * this crop object is something like this { x: 0, y: 10, width: 100, height: 80}
     * for example i want to center the crop box, and also get the pixelCrop value 
     */
    this.setState({ crop, pixelCrop: computedPixelCrop })
 }

  onCropChange = (crop, pixelCrop) => {
    /** 
     * this crop is passed down by [resolveCrop](https://github.com/DominicTobias/react-image-crop/blob/master/lib/ReactCrop.js#L460)
     * this crop value is not the same as the crop value in handleImageLoaded function
     * but the onChange function is called right after the onImageLoaded function，so here setState override my crop state set in onImageLoaded
     */
    this.setState({
      crop,
      pixelCrop
    })
 }
```

My question is how can i skip the [onChange](https://github.com/DominicTobias/react-image-crop/blob/master/lib/ReactCrop.js#L465) and onComplete call in onImageLoad function, so i can use the right crop state set in onImageLoad function

**Comment by DominicTobias** [comment]
Hi, 

If your pixel crop calculation is the same as the one in the library then you can import `getPixelCrop` from the library and do `const pixelCrop = getPixelCrop(image, yourPercentageCrop)`.

I think I can do something like if `onImageLoaded` callback returns false then do not call `onChange`/`onComplete` meaning "I will handle this", since your `setState` will cause those functions to be called anyway.

**Comment by xwillmadeit** [comment]
Thanks for your reply.
Yeah，like you said its better if the library could provide an option to skip the onChange and onComplete call in `onImageLoaded`？ The crop and pixelCrop value i calculated in `onImageLoaded` callback is only used for image loaded，only when i change the crop manually，the library takes over the control of the crop data

**Comment by DominicTobias** [comment]
Released in 6.0.17, return false to prevent `onChange` + `onComplete` callbacks from being called. Let me know how it goes!

**Comment by xwillmadeit** [comment]
> Released in 6.0.17, return false in `onImageLoaded` to prevent `onChange` + `onComplete` callbacks from being called. Let me know how it goes!

Oh it seems 6.0.17 is not published to npm yet

**Comment by DominicTobias** [comment]
@xwillmadeit  Whoops 😅 it's published now

**Comment by xwillmadeit** [comment]
@DominicTobias add return false to `onImageLoaded ` callback works for me now. 
Thanks a lot ~
