### ISSUE TITLE
get crop area when use the static image with and height

### ISSUE THREAD

**Issue by farshadfahimi1371** [DominicTobias/react-image-crop#247]
I use this module and get the style to my image and wrap it in 480 width and 480px height 
when select the crop area the module return wrong positions 
Is there any way to fix this ?

**Comment by DominicTobias** [comment]
Hi please try `useNaturalImageDimensions={false}`

**Comment by farshadfahimi1371** [comment]
> Hi please try `useNaturalImageDimensions={false}`

I test this and this work currect
first find the height or width of image which one is bigger after that put the bigger one statically and after that reduce the other side depends on the other size and this work correct and return the right position and on the server we could get the real size image with correct crop area
