### ISSUE TITLE
Crash if crop area in resizable container (e.g. modal window). Demo in sandbox.

### ISSUE THREAD

**Issue by verbart** [DominicTobias/react-image-crop#250]
Please, look a simple demo with problem.
Description on comment in code.

https://codesandbox.io/s/q8475vzq5j

**Comment by miltonbo** [comment]
I review your sample, but It is working ok, Chromee and Firefox. Please explain what problem do you have?

**Comment by DominicTobias** [comment]
Hm yes it's working for me too on Chrome?

**Comment by verbart** [comment]
@miltonbo @DominicTobias Now all working. I don’t know what this is connected with, but five months ago there was a problem. As far as I remember, the browser freezes tightly (checked in several versions of browsers).
