### ISSUE TITLE
makeAspectCrop is exported

### ISSUE THREAD

**Issue by Englund0110** [DominicTobias/react-image-crop#254]
In the release notes for [7.0.0](https://github.com/DominicTobias/react-image-crop/releases/tag/7.0.0) is says that makeAspectCrop is not exported, but when looking at the source code, it is: 

`export {
  ReactCrop as default,
  ReactCrop as Component,
  makeAspectCrop,
  containCrop,
};`

**Comment by DominicTobias** [comment]
Hi well spotted thanks, you are right I ended up keeping it because I'm still completing crop objects which are missing width or height if aspect is specified. Updated the release notes. Main thing to note is the signature changed to `makeAspect(crop, imageElement)`

**Comment by DominicTobias** [comment]
In hindsight this function would have been purer if I had passed imageWidth and imageHeight instead. Will probably made a breaking change for that in a future release!

**Comment by Englund0110** [comment]
Hi! I was updating the type definitions, and was just a bit confused. But thanks for the explanation. :-)

**Comment by DominicTobias** [comment]
Aha, thanks for updating them!

**Comment by Englund0110** [comment]
FYI the new type definitions has just been published. :-)

**Comment by DominicTobias** [comment]
Great! Thanks for updated it
