### ISSUE TITLE
Control the background image outside the cropper

### ISSUE THREAD

**Issue by alukaszew** [DominicTobias/react-image-crop#257]
Hello,
I have a question.
Is it possible to control the image inside the cropper (left right), by the component outside and update the cropper image ? 
I've implemented the navigation, and I'm changing the image place, but the cropper is not reacting for background image position, forced by CSS.

**Comment by DominicTobias** [comment]
Hi, the image is using a <img /> tag not a background so you would have to adjust it with position relative + top/right/bottom/left, margin, or transform: translate

**Comment by alukaszew** [comment]
> Hi, the image is using a `<img />` tag not a background so you would have to adjust it with position relative + top/right/bottom/left, margin, or transform: translate

Yeah, but cropper it self, not see the real position. It not updating the changes. Really I thinking how to update the crop area when I positioning the image. The cropper behaviour now is like, I'm positioning the image and cropper zone see the image like it never be positioned left/right or any position.

**Comment by DominicTobias** [comment]
Hm sounds like you haven't set something up right - check here for an example https://codesandbox.io/s/72py4jlll6

**Comment by alukaszew** [comment]
> Hm sounds like you haven't set something up right - check here for an example https://codesandbox.io/s/72py4jlll6

To reproduce, change the image to relative, and make it left: + 10 px. Cropper see the image as without this extra CSS. Changes from outside on CSS, won't affect on cropper. This is the problem . in my case. I'm asking, how to control the position of image with locked cropped area, and updating the result image simultaneously like here: https://fengyuanchen.github.io/cropper/

**Comment by alukaszew** [comment]
Is any way to control the position of image left / right / zoom with outside component or I'm wasting my time ?

**Comment by DominicTobias** [comment]
I'm not sure what you mean as moving the image with position relative works fine I just checked

**Comment by alukaszew** [comment]
> I'm not sure what you mean as moving the image with position relative works fine I just checked

@DominicTobias , but cropper zone, not "see" it properly. imageCropperUrl is not update the proper position of image. I wonder, where I must to inject code to proper update the cropped image with positioning.

**Comment by DominicTobias** [comment]
Still not entirely sure what you mean, here's an example of nudging it to the left and right: https://codesandbox.io/s/v853vkz3w5

**Comment by alukaszew** [comment]
![screenshot-codesandbox io-2019 04 26-08-50-50](https://user-images.githubusercontent.com/16006493/56788714-7264ad00-6800-11e9-86c7-f49c5a3a8cf5.png)
Is it more clear now ? The select zone, seems to ignore the image styles  :)

**Comment by DominicTobias** [comment]
Ah right the crop preview, as you can see it uses `drawImage` and you would need to factor in the x/y changes into it - see https://codesandbox.io/s/v853vkz3w5

`crop.x * scaleX - nudgeFactor`

**Comment by alukaszew** [comment]
> Ah right the crop preview, as you can see it uses `drawImage` and you would need to factor in the x/y changes into it - see https://codesandbox.io/s/v853vkz3w5
> 
> `crop.x * scaleX - nudgeFactor`

Great! You save me lot of time. Many thanks :)
