### ISSUE TITLE
imagecrop在ie11以及edge的兼容问题

### ISSUE THREAD

**Issue by liyue118** [DominicTobias/react-image-crop#258]
根据官方的文档引入插件后，chrome运行正常，但是ie及edge返回Unhandled promise rejection TypeError: Invalid calling object。

如图：
![Capture](https://user-images.githubusercontent.com/37989537/57763954-0c02e880-7735-11e9-8b02-067b79bcd362.PNG)

代码：                                
<ImgCrop>
         <Upload>
         </Upload>
</ImgCrop>

**Comment by liyue118** [comment]
<ImgCrop>
                                    <Upload
                                        name={intl.formatMessage({ id: 'event.content.Upload avatar' })}
                                        listType="picture-card"
                                        showUploadList={false}
                                        //action={Ip}
                                        beforeUpload={this.beforeUpload}
                                        //onChange={this.fileonchange}
                                    >
                                        {imageUrl}
                                    </Upload>
                                </ImgCrop>

**Comment by DominicTobias** [comment]
Hi is this IE11? IE11 doesn't support `canvas.toBlob` I think, you need to use `toDataURL` or a polyfill: https://github.com/eligrey/canvas-toBlob.js

**Comment by liyue118** [comment]
![Capture](https://user-images.githubusercontent.com/37989537/57836637-bccfbd00-77f3-11e9-9bc5-4f5749433958.PNG)


Dear,我把这个polyfill引入之后，
import 'canvas-toBlob';  

ie11报错还是原来的样子

**Comment by liyue118** [comment]
![Capture](https://user-images.githubusercontent.com/37989537/57838652-b6dbdb00-77f7-11e9-8a60-77ac0c728f7f.PNG)
![Capture](https://user-images.githubusercontent.com/37989537/57838687-c8bd7e00-77f7-11e9-8994-e21b9ec194f5.PNG)


我在es文件夹做了如图的修改
效果没有实现

**Comment by dongyang19931108** [comment]
> IE11 (and Edge?) have prefixed `canvas.toBlob` as `canvas.msToBlob`.
> 
> You need to use `msToBlob()` but only for IE/Edge, or `toDataURL` but that is slow. But I think the easiest solution will be to use a polyfill: https://github.com/eligrey/canvas-toBlob.js

You can refer to the compatibility provided by the official website API, add IE compatibility in the source code, after testing, it can run in IE11 and Edge

**Comment by dongyang19931108** [comment]
https://www.canvasapi.cn/HTMLCanvasElement/toBlob#&compatibility    
This is the official address

**Comment by DominicTobias** [comment]
I'm closing this as making a crop on the client isn't something this library does, the example is just for demo purposes and doesn't guarantee browser support. If you're still stuck I recommend asking on StackOverflow.
