### ISSUE TITLE
Resize and customize border event area

### ISSUE THREAD

**Issue by VagnerNico** [DominicTobias/react-image-crop#259]
I faced a issue related to big fingers, so the users encountered difficulties to resize/expand the crop area. (Forgot to tell it's a mobile experience)
Is there any way to increse the area of event listener?
Besides it's possible to customize this squares to be only borders like WhatsApp cropper?

I already anticipate apologizing if you find grammar problems in my english.

Best regards,

Vagner José Nicolodi

**Comment by DominicTobias** [comment]
Hi there are two ways to do this:

1) If you import the .scss file you can override variables used by settings them before importing the file, you can see the variables here: https://github.com/DominicTobias/react-image-crop/blob/master/lib/ReactCrop.scss e.g. https://github.com/DominicTobias/react-image-crop/issues/151

2) If using CSS you can override the width, height, and margins of `ReactCrop__drag-handle` elements to be larger

There is nothing out the box that gives the WhatsApp look but it might be possible using css

**Comment by VagnerNico** [comment]
Everything works fine, thanks!
