### ISSUE TITLE
[v7.0.2] Crop can move on resize and goes beyond boundaries.

### ISSUE THREAD

**Issue by de83c78d1f** [DominicTobias/react-image-crop#261]
Hello, there is issue when u have min dimensions. Assume we have crop component with minWidth/minHeight 160/90px (add those props to ReactCrop component). If you drag your crop to bottom of canvas leaving some space to enlarge crop to bottom. Then drag bottom-left corner to the bottom edge of the canvas and keep dragging.
1. crop moves to the left.
2. crop can move beyond left edge of the canvas.
It is reproducible in demo.
Although checking on crop x position in onCropChange is an option - there's still an issue 1 - crop kinda shouldn't move while user attempts to resize.
![Gif](https://user-images.githubusercontent.com/39216062/58073194-a8504380-7baa-11e9-998b-9db9181b8fb7.gif)

**Comment by DominicTobias** [comment]
Hi thanks for the clear bug report 👍 Please try 7.0.3

**Comment by DominicTobias** [comment]
@de83c78d1f any luck?

**Comment by de83c78d1f** [comment]
Thank you for fast response/fix. Yeah, new version actually fixes the bug mentioned above.
But... Introduces another, which is kinda mirrored version.
![Peek 2019-05-24 11-29](https://user-images.githubusercontent.com/39216062/58314130-89a2b480-7e17-11e9-9d0c-f576eb8a1790.gif)

**Comment by DominicTobias** [comment]
Ah good catch thanks for checking will take a look soon

**Comment by DominicTobias** [comment]
@de83c78d1f Finally getting round to look at this, was this was definitely on 7.0.3? Can you try with this sandbox https://codesandbox.io/s/reactimagecrop-issue-261-qq72y or else spot if I'm doing something wrong?:

I have set same min/max as you and 16/9 aspect, but crop isn't growing on the other side:

![ezgif-1-78ab8b76ab91](https://user-images.githubusercontent.com/760314/58897376-13902e80-86f0-11e9-80c5-585d34cec4ff.gif)

**Comment by DominicTobias** [comment]
Edit: ignore, I can reproduce now

**Comment by DominicTobias** [comment]
@de83c78d1f Fixed in 7.0.4

**Comment by DominicTobias** [comment]
This should be fixed in #7.0.5 now

**Comment by de83c78d1f** [comment]
Hi, all fixes are irrelevant after version 8. Library does not respect boundaries anymore. Nor it respects min dimensions.
![Peek 2019-06-25 15-55](https://user-images.githubusercontent.com/39216062/60100322-2aabc480-9762-11e9-9223-6cda04bf9692.gif)

**Comment by de83c78d1f** [comment]
Ping

**Comment by DominicTobias** [comment]
I'm aware of the bug, I looked into it but didn't find a fix easily. I'm
working on multiple other things at the moment so don't know when I'll next
delve into it. If I recall JCrop didn't have the issue so you could use
that if you prefer

**Comment by DominicTobias** [comment]
Fixed in 8.4.0
