### ISSUE TITLE
import ReactCrop.css Error

### ISSUE THREAD

**Issue by nirfuchs73** [DominicTobias/react-image-crop#262]
Hi
When importing ReactCrop.css i get the below error:
Import:
import 'react-image-crop/dist/ReactCrop.css';

Error:
Error in ./~/react-image-crop/dist/ReactCrop.css
Module parse failed: .\node_modules\react-image-crop\dist\ReactCrop.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .ReactCrop {
|   position: relative;
|   display: inline-block;

What am I missing?
Thanks
Nir

**Comment by DominicTobias** [comment]
Hi this is an issue with your build tools and how you've set them up, if you try and import any css file you should get the same error. You didn't provide any code but I'm guessing it's webpack so you can go there and see how to handle css loading.

**Comment by nirfuchs73** [comment]
Here is the full error:
× Error in ./~/react-image-crop/dist/ReactCrop.css
Module parse failed: .\node_modules\react-image-crop\dist\ReactCrop.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .ReactCrop {
|   position: relative;
|   display: inline-block;
 @ ./src/layouts/DocSubmission/CropDoc.js 10:0-45
 @ ./src/layouts/DocSubmission/index.js
 @ ./src/routes.js
 @ ./scripts/phenomic.browser.js
 @ multi (webpack)-hot-middleware/client.js ./scripts/phenomic.browser.js

**Comment by DominicTobias** [comment]
The full error makes no difference, as mentioned the issue is with your css loader, in your webpack config if you're using webpack.
