### ISSUE TITLE
Retain Image Quality after Crop on front-end?

### ISSUE THREAD

**Issue by Andriy-Kulak** [DominicTobias/react-image-crop#263]
I am curious if this package retains the quality of the original image after the crop... if cropping happens on the front end as is shown in the [demo](https://codesandbox.io/s/72py4jlll6)?

The reason I ask is when I use the example (as shown below), the resulting crop looks a lot more pixelated and less quality image so I am curious if that is what the end result is on the front end?

<img width="1173" alt="screenshot" src="https://user-images.githubusercontent.com/12179976/58306426-06d92400-7e2e-11e9-98c5-5a749b3f40be.png">

The workaround would be to pass the crop parameters and the original image to backend and have another package crop the image, but that would require a lot more work so is there a way to do this well on the front-end?

**Comment by DominicTobias** [comment]
Hi the quality is down to the settings of `canvas.toBlob` - https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

You see I've set it to `image/jpeg` if you remove that it defaults to PNG which is lossless. Also the last argument is `qualityArgument` between 0 and 1, I'm not sure what the default value is but I'm using the default in the demo which may not be 1.

The library itself doesn't have a crop preview built in it's more "this is how you could do it", there are other ways on the server (not sure about the client though).

**Comment by trevorwhealy** [comment]
I have this exact problem too. I couldn't figure out why the same cropped images looked so different depending on the device used and it turns out on mobile, the crop does not retain the same image quality. 

[Can't paste the video I made here for some reason, here's a link to the demo.](https://imgur.com/helXm8v)

When you are cropping an image with text, the problem becomes really obvious. I tried setting the qualityArgument value to 1 in the `toBlob` invocation, but that did not have any effect.

**Comment by DominicTobias** [comment]
@trevorwhealy did you try setting it to `image/png` too?

**Comment by trevorwhealy** [comment]
@DominicTobias thanks for the quick follow up - yes I did just test with `image/png` but to no avail

**Comment by DominicTobias** [comment]
Hmm interesting, maybe there is a better way to do it then - will look into it

**Comment by trevorwhealy** [comment]
That would be awesome! Here's my demo image if it helps you!

![IMG_2091](https://user-images.githubusercontent.com/14946478/58344792-843f6d00-7e0b-11e9-94ce-9a3bf1378bef.JPG)

I should mention that if I'm trying the crop the image on a very large screen where the photo is probably being rendered in its original size, the quality of the crop is perfect. I think the issue is creating a crop on an image that is being scaled down for smaller devices or smaller windowed views.

Demo of the result on a very big screen desktop view.
![Screen Shot 2019-05-24 at 10 07 43 AM](https://user-images.githubusercontent.com/14946478/58344944-f31cc600-7e0b-11e9-8cb9-0d15432826bf.png)

**Comment by DominicTobias** [comment]
Thanks does it degrade as badly for you here? https://bkd3w.codesandbox.io/

Is that Chrome devtools emulator you are trying with? (just want to make sure I'm doing the same thing as I can't see the same level of degradation, if any, at the moment on my external monitor)

**Comment by trevorwhealy** [comment]
That is so interesting! I just tested with the link shared, and do still see degradation. It seems we are using the same Chrome dev tools too.

![Screen Shot 2019-05-24 at 10 30 03 AM](https://user-images.githubusercontent.com/14946478/58346119-ee0d4600-7e0e-11e9-8174-670c2f52e9a6.png)

**Comment by trevorwhealy** [comment]
If you zoom in on your crop preview do you notice any degradation?
It could be that you need to zoom in a little bit

**Comment by DominicTobias** [comment]
Ah yes I do notice the degradation when zooming 🤔

![Screenshot 2019-05-24 at 18 52 17](https://user-images.githubusercontent.com/760314/58347197-2172c380-7e55-11e9-9a75-8115e2a3f479.png)

**Comment by DominicTobias** [comment]
Hi did you get any further with this? I noticed that in general quality is reduced when zoomed with devtools - even the css borders for the drag handles are blurry. I would recommend trying it on a real phone as I suspect it could be a devtools issue.

**Comment by peter-hoa** [comment]
Hello there!  I have been trying out your project, and, have come across the exact same issue.

My experience so far has been that when the canvas is creating the cropped image, it's using as the source, the display image.  The problem here is that the display image resolution is determined by the available space used for presentation on the web page.

Think about what the web browser does to make the image fit into the available space for the user.  It's re-sampling the original image, and putting that into the image element that you're seeing on-screen.

So, that's where the lack of resolution in the cropped image is coming from.

What I have been doing here is: create a hidden image element (which holds the full-resolution image, because the browser is not trying to resize it to fit inside anything), and when it comes time to create the crop, use that hidden image as the source instead of the visible image.

Of course, the crop details have reference to the displayed image pixels, so they have to be scaled up to match the resolution of the actual source image.  ie: x,y, width, height - they're all with reference to the displayed image instead of relative to the source image.

Does that make sense?

**Comment by DominicTobias** [comment]
Whoops forgot to read that @peter-hoa, good point. Sounds like a reasonable hypothesis I'll have a think/look around to see how this could be solved

**Comment by kmvan** [comment]
qualityArgument set to 1 and looks so blur.

**Comment by peter-hoa** [comment]
> Whoops forgot to read that @peter-hoa, good point. Sounds like a reasonable hypothesis I'll have a think/look around to see how this could be solved

Hey @DominicTobias, I've not only provided what I think is a description of what the cause is, but, I also go on to mention how I've avoided the issue.  ie: I actually am doing this, and it works quite well.  Client crop gets the best possible resolution as the outcome.  If you incorporate having the hidden image element, and use that for the generation of the crop on the client, then you should be able to replicate the results I'm seeing using this approach.

Admittedly, I'm doing most testing using Chrome browser on desktop, so, your mileage may vary.

I'm also using a quite large source image, so that the quality issues are easily verifiable.

Keep up the good work!

:)

**Comment by marvinsmit** [comment]
Hey @peter-hoa, could you provide us with a code example for your solution? Would really appreciate :)

**Comment by maximus123123** [comment]
Here is my code, @DominicTobias is right abou the quality parameter. 

The problem with the original code of the following is that it was making the canvas size in relation to the cropper size and not the native image size. So if your Cropper was shrunk by css or smaller/bigger container size, it would effect the final canvas image size.

See belows changes, you may add the image back in parameters if you want.

`      getCroppedImg(crop, fileName) {
        let image = this.imageRef;
        const canvas = document.createElement('canvas');
        const scaleX = image.naturalWidth / image.width;
        const scaleY = image.naturalHeight / image.height;
        canvas.width = Math.ceil(crop.width*scaleX);
        canvas.height = Math.ceil(crop.height*scaleY);
        const ctx = canvas.getContext('2d');

        ctx.drawImage(
          image,
          crop.x * scaleX,
          crop.y * scaleY,
          crop.width * scaleX,
          crop.height * scaleY,
          0,
          0,
          crop.width*scaleX,
          crop.height*scaleY,
        );

        // As Base64 string
        // const base64Image = canvas.toDataURL('image/jpeg');
        // As a blob
        return new Promise((resolve, reject) => {
          canvas.toBlob(blob => {
            blob.name = fileName;
            resolve(blob);
          }, 'image/jpeg',1);
        });
      }`

**Comment by xrchloe** [comment]
To retain image quality after crop on front-end, just make the canvas size larger. In my case, I also want to restrict the cropped image width under 1200px. Below is my code:

`getCroppedImg(image, crop, fileName) {
    const canvas = document.createElement("canvas");
    const scaleX = image.naturalWidth / image.width;
    const scaleY = image.naturalHeight / image.height;
    var originWidth = crop.width * scaleX;
    var originHeight = crop.height * scaleY;
    // maximum width/height
    var maxWidth = 1200, maxHeight = 1200 / (16 / 9);
    var targetWidth = originWidth,
      targetHeight = originHeight;
    if (originWidth > maxWidth || originHeight > maxHeight) {
      if (originWidth / originHeight > maxWidth / maxHeight) {
        targetWidth = maxWidth;
        targetHeight = Math.round(maxWidth * (originHeight / originWidth));
      } else {
        targetHeight = maxHeight;
        targetWidth = Math.round(maxHeight * (originWidth / originHeight));
      }
    }
    // set canvas size
    canvas.width = targetWidth;
    canvas.height = targetHeight;
    const ctx = canvas.getContext("2d");

    ctx.drawImage(
      image, 
      crop.x * scaleX, 
      crop.y * scaleY, 
      crop.width * scaleX, 
      crop.height * scaleY, 
      0, 
      0, 
      targetWidth, 
      targetHeight 
    );

    return new Promise((resolve, reject) => {
      canvas.toBlob(
        blob => {
          if (!blob) {
            console.error("Canvas is empty");
            return;
          }
          blob.name = fileName;
          window.URL.revokeObjectURL(this.fileUrl);
          this.fileUrl = window.URL.createObjectURL(blob);
          resolve(this.fileUrl);
        },
        "image/png",
        1
      );
    });
  }`

**Comment by ehssamimi** [comment]
> To retain image quality after crop on front-end, just make the canvas size larger. In my case, I also want to restrict the cropped image width under 1200px. Below is my code:
> 
> ```
> getCroppedImg(image, crop, fileName) {
>     const canvas = document.createElement("canvas");
>     const scaleX = image.naturalWidth / image.width;
>     const scaleY = image.naturalHeight / image.height;
>     var originWidth = crop.width * scaleX;
>     var originHeight = crop.height * scaleY;
>     // maximum width/height
>     var maxWidth = 1200, maxHeight = 1200 / (16 / 9);
>     var targetWidth = originWidth,
>       targetHeight = originHeight;
>     if (originWidth > maxWidth || originHeight > maxHeight) {
>       if (originWidth / originHeight > maxWidth / maxHeight) {
>         targetWidth = maxWidth;
>         targetHeight = Math.round(maxWidth * (originHeight / originWidth));
>       } else {
>         targetHeight = maxHeight;
>         targetWidth = Math.round(maxHeight * (originWidth / originHeight));
>       }
>     }
>     // set canvas size
>     canvas.width = targetWidth;
>     canvas.height = targetHeight;
>     const ctx = canvas.getContext("2d");
> 
>     ctx.drawImage(
>       image, 
>       crop.x * scaleX, 
>       crop.y * scaleY, 
>       crop.width * scaleX, 
>       crop.height * scaleY, 
>       0, 
>       0, 
>       targetWidth, 
>       targetHeight 
>     );
> 
>     return new Promise((resolve, reject) => {
>       canvas.toBlob(
>         blob => {
>           if (!blob) {
>             console.error("Canvas is empty");
>             return;
>           }
>           blob.name = fileName;
>           window.URL.revokeObjectURL(this.fileUrl);
>           this.fileUrl = window.URL.createObjectURL(blob);
>           resolve(this.fileUrl);
>         },
>         "image/png",
>         1
>       );
>     });
>   }
> ```

thats good but when i crop imag it has balck background!!
![image](https://user-images.githubusercontent.com/47100310/63636657-6b9f5700-c687-11e9-9a4a-5a0469709d3b.png)

**Comment by chendatao407786** [comment]
The real size of the image croped is base on the size of the image that <ReactCrop/> present. 
I made the <ReactCrop/> size larger, problem resolved.

**Comment by tw1t611** [comment]
You need to set the height of the image to 100% to fill it's parent container.

**Comment by sri-wml** [comment]
Here's what I had to do to fix the quality issue. The action became a bit slow. I can live with it as its only for admin purposes. You might want to scale it further down if you want the speed.

`// Base64 Image to Canvas with a Crop
  async image64toCanvasRef(canvasRef, image64, pixelCrop) {
    const canvas = canvasRef;
    const ctx = canvas.getContext('2d');
    const image = new Image();
    image.src = image64;
    let url = '';
    const scope = this;
    image.onload = function () {
      canvas.width = image.naturalWidth;
      canvas.height = image.naturalHeight;
      const scaleX = image.naturalWidth / scope.state.width;
      const scaleY = image.naturalHeight / scope.state.height;
      ctx.drawImage(
        image,
        pixelCrop.x * scaleX,
        pixelCrop.y * scaleY,
        pixelCrop.width * scaleX,
        pixelCrop.height * scaleY,
        0,
        0,
        image.naturalWidth,
        image.naturalHeight,
      );
      url = canvas.toDataURL('image/jpeg', 0.8);
      scope.convertBas64ToImage(url);
      scope.setState({ croppedImageSrc: url });
    };
  }`

**Comment by DominicTobias** [comment]
You should be able to make that faster by converting it to a blob instead
of a data url

**Comment by kirkdrichardson** [comment]
There may be another issue occurring regardless of how the client crop is handled. I came across this because I was originally using the image directly from the upload:

```js
        <input
          type='file'
          style={{ display: 'none' }}
          accept='image/*'
          onChange={this.handleImageUpload}
          ref={this.fileInput} />
```

in the `handleImageUpload` method I would append the image to the class body. However this full-resolution version of the image differed from what was returned by the internal `onImageLoaded = (image: HTMLImageElement): void ` method. Until I set the image to be the image returned by the `onImageLoaded` method, the crop dimensions were off (since they were based on a lossy image and applied to the full-resolution image). Unfortunately, the tradeoff of using the image returned by `onImageLoaded`  was having to display the lower resolution image on the client.

**Comment by TchernyavskyDaniil** [comment]
@maximus123123 
@xrchloe 
Awesome. Thx!

**Comment by samuelpetroline** [comment]
This is my approach to resize the image element and still maintain the aspect ratio. Note that the crop argument actually is **percentageCrop**
 
```js
function getCroppedImg(image, crop) {
  
    const cropWidth = image.naturalWidth * (crop.width / 100)
    const cropHeight = image.naturalHeight * (crop.height / 100)
    const startX = image.naturalWidth * (crop.x / 100)
    const startY = image.naturalHeight * (crop.y / 100)

    const canvas = document.createElement('canvas')
    canvas.width = cropWidth
    canvas.height = cropHeight
    const ctx = canvas.getContext('2d')

    ctx.drawImage(
      image,
      startX,
      startY,
      cropWidth,
      cropHeight,
      0,
      0,
      cropWidth,
      cropHeight
    )

    return new Promise((resolve, reject) => {
      canvas.toBlob(blob => {
        if (!blob) {
          reject('Erro ao carregar imagem')
        }
        
        resolve(blob)
      }, 'image/png')
    })
  }
```

**Comment by Nienormalny** [comment]
> Here is my code, @DominicTobias is right abour the quality parameter.
> 
> The problem with the original code of the following is that it was making the canvas size in relation to the cropper size and not the native image size. So if your Cropper was shrunk by css or smaller/bigger container size, it would effect the final canvas image size.
> 
> See belows changes, you may add the image back in parameters if you want, the only changes is the quality "1" parameter in toBlob, and the crop.width_scaleX, crop.height_scaleY.
> 
> Math.ceil to make sure the natural image isn't reduced by 1 pixel sometimes.
> 
> ```
> getCroppedImg(crop, fileName) {
>         let image = this.imageRef;
>         const canvas = document.createElement('canvas');
>         const scaleX = image.naturalWidth / image.width;
>         const scaleY = image.naturalHeight / image.height;
>         canvas.width = Math.ceil(crop.width*scaleX);
>         canvas.height = Math.ceil(crop.height*scaleY);
>         const ctx = canvas.getContext('2d');
>         ctx.drawImage(
>           image,
>           crop.x * scaleX,
>           crop.y * scaleY,
>           crop.width * scaleX,
>           crop.height * scaleY,
>           0,
>           0,
>           crop.width*scaleX,
>           crop.height*scaleY,
>         );
>         // As Base64 string
>         // const base64Image = canvas.toDataURL('image/jpeg');
>         // As a blob
>         return new Promise((resolve, reject) => {
>           canvas.toBlob(blob => {
>             blob.name = fileName;
>             resolve(blob);
>           }, 'image/jpeg',1);
>         });
>       }
> ```

Thanks for this solution! It helps a lot with image quality! <3

**Comment by zhumengyue** [comment]
Hi, I am still troubled by this problem。

My usage scenario is that I want to output the cropped picture to the specified size。For example，i have an image which size is 867×360，actually i have to upload it by the size 289 ×120,  which means the image need to zoom 3 time. So i select the whole image and crop. Then i get an image which size is 289×120, but it has a bad quality.

I have read the comments before, but it doesn't seem to work.

The point maybe that when i scale the image cropped from canvas, it has a bad quality（

Here is my code
https://codesandbox.io/s/exciting-darkness-jhinc

Here is my image
https://sf3-ttcdn-tos.pstatp.com/img/tos-cn-i-0000/d7ddfa1c08f34b988aa6295c19aeb9f7~tplv-noop.jpeg

and the screenshot, obviously the image cropped (the right one) has a low quality
![image](https://user-images.githubusercontent.com/25398665/77306215-4dd7c480-6d32-11ea-896e-f4811275c767.png)

**Comment by royeeshemesh** [comment]
@maximus123123 working perfectly!

**Comment by sabersalhi16** [comment]
> Here is my code, @DominicTobias is right abour the quality parameter.
> 
> The problem with the original code of the following is that it was making the canvas size in relation to the cropper size and not the native image size. So if your Cropper was shrunk by css or smaller/bigger container size, it would effect the final canvas image size.
> 
> See belows changes, you may add the image back in parameters if you want, the only changes is the quality "1" parameter in toBlob, and the crop.width_scaleX, crop.height_scaleY.
> 
> Math.ceil to make sure the natural image isn't reduced by 1 pixel sometimes.
> 
> ```
> getCroppedImg(crop, fileName) {
>         let image = this.imageRef;
>         const canvas = document.createElement('canvas');
>         const scaleX = image.naturalWidth / image.width;
>         const scaleY = image.naturalHeight / image.height;
>         canvas.width = Math.ceil(crop.width*scaleX);
>         canvas.height = Math.ceil(crop.height*scaleY);
>         const ctx = canvas.getContext('2d');
>         ctx.drawImage(
>           image,
>           crop.x * scaleX,
>           crop.y * scaleY,
>           crop.width * scaleX,
>           crop.height * scaleY,
>           0,
>           0,
>           crop.width*scaleX,
>           crop.height*scaleY,
>         );
>         // As Base64 string
>         // const base64Image = canvas.toDataURL('image/jpeg');
>         // As a blob
>         return new Promise((resolve, reject) => {
>           canvas.toBlob(blob => {
>             blob.name = fileName;
>             resolve(blob);
>           }, 'image/jpeg',1);
>         });
>       }
> ```

you are the best

**Comment by DominicTobias** [comment]
A canvas element will be blurry on retina devices unless you size it up by the pixel ratio and then still show it at the original dimensions:

```js
const pixelRatio = (typeof window !== 'undefined' && window.devicePixelRatio) || 1
const yourCropPreviewWidth = 600;
const yourCropPreviewHeight = 400;

<canvas
  width={yourCropPreviewWidth * pixelRatio}
  height={yourCropPreviewHeight * pixelRatio}
  style={{
    width: yourCropPreviewWidth,
    height: yourCropPreviewHeight,
  }}
/>
```

I've updated the hook example for this: https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o

Couple of things to note:
- I keep the preview as a canvas since it's a lot faster than converting it to a blob and assigning that to an image but that's up to you
- I added a download button to show what converting it to a blob would look like (or if you want to send it to the server). The crux is that you need to size it back down to the original dimensions if it has been sized up for retina.

**Comment by bhatvikrant** [comment]
@DominicTobias hey man, the cropped image is not downloading on the sandbox

> A canvas element will be blurry on retina devices unless you size it up by the pixel ratio and then still show it at the original dimensions:
> 
> ```js
> const pixelRatio = window.devicePixelRatio || 1
> const yourCropPreviewWidth = 600;
> const yourCropPreviewHeight = 400;
> 
> <canvas
>   width={yourCropPreviewWidth * pixelRatio}
>   height={yourCropPreviewHeight * pixelRatio}
>   style={{
>     width: yourCropPreviewWidth,
>     height: yourCropPreviewHeight,
>   }}
> />
> ```
> 
> I've updated the hook example for this: https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o
> 
> Couple of things to note:
> 
> * I keep the preview as a canvas since it's a lot faster than converting it to a blob and assigning that to an image but that's up to you
> * I added a download button to show what converting it to a blob would look like (or if you want to send it to the server). The crux is that you need to size it back down to the original dimensions if it has been sized up for retina.
> * If you want to show the crop at the size relative to the original image you can still scale it like @maximus123123 showed.

**Comment by DominicTobias-b1** [comment]
> @DominicTobias hey man, the cropped image is not downloading on the sandbox
> 
> > A canvas element will be blurry on retina devices unless you size it up by the pixel ratio and then still show it at the original dimensions:
> > ```js
> > const pixelRatio = window.devicePixelRatio || 1
> > const yourCropPreviewWidth = 600;
> > const yourCropPreviewHeight = 400;
> > 
> > <canvas
> >   width={yourCropPreviewWidth * pixelRatio}
> >   height={yourCropPreviewHeight * pixelRatio}
> >   style={{
> >     width: yourCropPreviewWidth,
> >     height: yourCropPreviewHeight,
> >   }}
> > />
> > ```
> > 
> > 
> > I've updated the hook example for this: https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o
> > Couple of things to note:
> > 
> > * I keep the preview as a canvas since it's a lot faster than converting it to a blob and assigning that to an image but that's up to you
> > * I added a download button to show what converting it to a blob would look like (or if you want to send it to the server). The crux is that you need to size it back down to the original dimensions if it has been sized up for retina.
> > * If you want to show the crop at the size relative to the original image you can still scale it like @maximus123123 showed.

Unfortunately it's blocked due to being in an iframe - you need to access it from https://y831o.csb.app/

The solution for being in an iframe would be to always generate a blob and put it in the anchor instead of programmatically triggering a click e.g. `<a href={blobUrl} download="imagePreview.png" />`

**Comment by bhatvikrant** [comment]
okayy!, 
also If i try to upload the image below its preview doesnt show up. Is it because it is a high pixel image? tried this on your sandbox 
![IMG_3213](https://user-images.githubusercontent.com/50735025/83836747-0b5b3c80-a712-11ea-93f1-e64179f93bc3.jpg)

**Comment by DominicTobias-b1** [comment]
@arendjr hm it's working fine for me in latest Chrome with your image

**Comment by DominicTobias** [comment]
I noticed that the crop preview was blurry even on a non-retina screen. I've fixed the issue by always setting the pixel ratio to x4 and disabling `imageSmoothingEnabled` on the canvas.

Before:
![Screenshot 2020-06-18 at 12 23 52 PM](https://user-images.githubusercontent.com/760314/84978364-4708f400-b15f-11ea-9630-18854e1d36a7.png)

After:
![Screenshot 2020-06-18 at 12 24 12 PM](https://user-images.githubusercontent.com/760314/84978370-4bcda800-b15f-11ea-93f9-10f7a8c187bd.png)

I've updated the hooks demo: https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o?file=/src/App.js

**Comment by aliemami** [comment]
and here is my code for the hook version, note that I moved the function inside the body of the module to avoid passing parameters 
    const getResizedCanvas = () => {
        const scaleX = imgRef.current.naturalWidth / imgRef.current.width;
        const scaleY = imgRef.current.naturalHeight / imgRef.current.height;
        const tmpCanvas = document.createElement("canvas");
        tmpCanvas.width = Math.ceil(crop.width*scaleX);
        tmpCanvas.height = Math.ceil(crop.height*scaleY);

        const ctx = tmpCanvas.getContext("2d");
        const image = imgRef.current;
        ctx.drawImage(
            image,
            crop.x * scaleX,
            crop.y * scaleY,
            crop.width * scaleX,
            crop.height * scaleY,
            0,
            0,
            crop.width*scaleX,
            crop.height*scaleY,
        );

        return tmpCanvas;
    }

**Comment by dimitrisraptis96** [comment]
For the React hook example this simple adjustment fixed the issue for me: 

```javascript
 React.useEffect(() => {
    if (!completedCrop || !previewCanvasRef.current || !imgRef.current) {
      return;
    }

    const image = imgRef.current;
    const canvas = previewCanvasRef.current;
    const crop = completedCrop;

    const scaleX = image.naturalWidth / image.width;
    const scaleY = image.naturalHeight / image.height;
    const ctx = canvas.getContext("2d");
    const pixelRatio = window.devicePixelRatio;

   // FIX No.1
   // We need to set the canvas width & height to the original image's size
   // Otherwise, the image is scaled down
    canvas.width = scaleX * crop.width * pixelRatio; 
    canvas.height = scaleY * crop.height * pixelRatio; 

    ctx.setTransform(pixelRatio, 0, 0, pixelRatio, 0, 0);
    ctx.imageSmoothingQuality = "high";

   // FIX No.2
   // We draw the cropped piece with it's original dimensions
    ctx.drawImage(
      image,
      crop.x * scaleX,
      crop.y * scaleY,
      crop.width * scaleX,
      crop.height * scaleY,
      0,
      0,
      crop.width * scaleX,
      crop.height * scaleY
    );
  }, [completedCrop]);
```

Essentially, the `canvas.width` attribute is not the same `canvas.style.width`. [More here](https://stackoverflow.com/a/5045549/9149776)

**Comment by DominicTobias** [comment]
> For the React hook example this simple adjustment fixed the issue for me:
> 
> ```js
>  React.useEffect(() => {
>     if (!completedCrop || !previewCanvasRef.current || !imgRef.current) {
>       return;
>     }
> 
>     const image = imgRef.current;
>     const canvas = previewCanvasRef.current;
>     const crop = completedCrop;
> 
>     const scaleX = image.naturalWidth / image.width;
>     const scaleY = image.naturalHeight / image.height;
>     const ctx = canvas.getContext("2d");
>     const pixelRatio = window.devicePixelRatio;
> 
>    // FIX No.1
>    // We need to set the canvas width & height to the original image's size
>    // Otherwise, the image is scaled down
>     canvas.width = scaleX * crop.width * pixelRatio; 
>     canvas.height = scaleY * crop.height * pixelRatio; 
> 
>     ctx.setTransform(pixelRatio, 0, 0, pixelRatio, 0, 0);
>     ctx.imageSmoothingQuality = "high";
> 
>    // FIX No.2
>    // We draw the cropped piece with it's original dimensions
>     ctx.drawImage(
>       image,
>       crop.x * scaleX,
>       crop.y * scaleY,
>       crop.width * scaleX,
>       crop.height * scaleY,
>       0,
>       0,
>       crop.width * scaleX,
>       crop.height * scaleY
>     );
>   }, [completedCrop]);
> ```
> 
> Essentially, the `canvas.width` attribute is not the same `canvas.style.width`. [More here](https://stackoverflow.com/a/5045549/9149776)

Nice one, I've update the sandboxes

**Comment by topsecretagent008** [comment]
import React, { useRef, useState } from "react";
import ReactCrop, {
    centerCrop,
    makeAspectCrop
} from 'react-image-crop';
import 'react-image-crop/dist/ReactCrop.css';

import demoImage from "../assets/findImage.png";

function centerAspectCrop(
    mediaWidth,
    mediaHeight,
    aspect
) {
    return centerCrop(
        makeAspectCrop(
            {
                unit: '%',
                width: 90,
            },
            aspect,
            mediaWidth,
            mediaHeight,
        ),
        mediaWidth,
        mediaHeight,
    )
}

function ImageCropper(props) {
    const { imageToCrop, onImageCropped } = props;
    const [crop, setCrop] = useState("")
    const imageRef = useRef("");

    const onImageLoad = (e) => {
        const { width, height } = e.target;
        setCrop(centerAspectCrop(width, height, 1))
    }

    async function cropImage(crop) {
        if (imageRef && crop.width && crop.height) {
            await getCroppedImage(
                imageRef.current,
                crop,
                'croppedImage.jpeg' // destination filename
            );
        }
    }

    function getCroppedImage(sourceImage, cropConfig, fileName) {
        const canvas = document.createElement('canvas');
        const scaleX = sourceImage.naturalWidth / sourceImage.width;
        const scaleY = sourceImage.naturalHeight / sourceImage.height;


        var originWidth = cropConfig.width * scaleX;
        var originHeight = cropConfig.height * scaleY;
        // maximum width/height
        var maxWidth = 1200, maxHeight = 1200 / (9 / 9);
        var targetWidth = originWidth,
            targetHeight = originHeight;
        if (originWidth > maxWidth || originHeight > maxHeight) {
            if (originWidth / originHeight > maxWidth / maxHeight) {
                targetWidth = maxWidth;
                targetHeight = Math.round(maxWidth * (originHeight / originWidth));
            } else {
                targetHeight = maxHeight;
                targetWidth = Math.round(maxHeight * (originWidth / originHeight));
            }
        }
        // set canvas size


        canvas.width = targetWidth;
        canvas.height = targetHeight;
        const ctx = canvas.getContext('2d');

        ctx.drawImage(
            sourceImage,
            cropConfig.x * scaleX,
            cropConfig.y * scaleY,
            cropConfig.width * scaleX,
            cropConfig.height * scaleY,
            0,
            0,
            targetWidth,
            targetHeight
        );

        return new Promise((resolve, reject) => {
            canvas.toBlob(
                (blob) => {
                    if (!blob) {
                        reject(new Error('Canvas is empty'));
                        return;
                    }
                    const file = new File([blob], "cropped-image.jpg", { type: "image/jpeg" });
                    blob.name = fileName;
                    const croppedImageUrl = window.URL.createObjectURL(blob);
                    onImageCropped({ file: file, url: croppedImageUrl });
                    resolve(croppedImageUrl);
                }, 'image/jpeg'
            );
        });
    }

    return (
        <div className="max-h-[500px] overflow-y-auto">
            <ReactCrop
                crop={crop}
                onComplete={(crop) => cropImage(crop)}
                onChange={(crop) => setCrop(crop)}
                crossorigin="anonymous"
                aspect={1}
            >
                <img ref={imageRef} alt="crop image" src={imageToCrop || demoImage} onLoad={onImageLoad} />
            </ReactCrop>
        </div>
    );
}

ImageCropper.defaultProps = {
    onImageCropped: () => { console.log("AAAAAAAAAAAAAAAAA") }
}

export default ImageCropper;
![Screenshot_2](https://github.com/DominicTobias/react-image-crop/assets/117511812/87098a78-8b5a-44c5-a7bf-0b983c32a4e9)


help me?

**Comment by topsecretagent008** [comment]
If you crop an image, the image quality deteriorates.
