### ISSUE TITLE
Multiple crop selection?

### ISSUE THREAD

**Issue by wisyr** [DominicTobias/react-image-crop#264]
Looking forward for possibility to mark multiple crops on the image. 
Thank you for an outstanding library!

**Comment by DominicTobias** [comment]
Hi thanks but what's your use case for this, can't you select one crop and then another?

Sounds edge case and something that would make the code base considerably more complex and quite a lot of work (crop arrays, arrays of internal data, overlapping crops) etc. If you really want to do it I would recommend forking the repository.

**Comment by wisyr** [comment]
I'm in a need (or user is) of having access to every crop created simultaneously on a single image. And yes - it's rather a complex issue which would require a lot of work. There's already a lib called Jcrop which handles it, hovewer your lib is at much higher quality. Thanks for reply. Cheers!

**Comment by DominicTobias** [comment]
Thanks I appreciate that, though I had a look at JCrop and it seems pretty solid, I would recommend going with that as I don't intend to do this work I'm busy with other stuff and would take quite a bit of refactoring, sorry! Closing
