### ISSUE TITLE
setState({ crop }) in onImageLoaded not work since v8.0.0

### ISSUE THREAD

**Issue by nanxiaobei** [DominicTobias/react-image-crop#265]
v7.0.5 is fine

**Comment by DominicTobias** [comment]
Hi, thanks I can reproduce it, will take a look in the next day or two

**Comment by DominicTobias** [comment]
Actually I fixed this now, please try 8.0.1

**Comment by DominicTobias** [comment]
Also - make sure you `return false` in the callback

**Comment by nanxiaobei** [comment]
Thanks for your quick response, it's fixed!
