### ISSUE TITLE
Server-side rendering: "window is not defined" error

### ISSUE THREAD

**Issue by ArtBIT** [DominicTobias/react-image-crop#267]
This library breaks SSR since it assumes that the `window` object is available in https://github.com/DominicTobias/react-image-crop/commit/9417719b766a9417afaf628f10fef8425f69e936#r33877568

Before using the `window` object, please be wary and check whether the `window` object is defined `(typeof window === 'undefined')`.

**Comment by DominicTobias** [comment]
Where is that error happening? The only place I access window is in `getElementOffset` which isn't called unless there is a mouse/touch down on a crop.

I will add a guard for document though.

**Comment by ArtBIT** [comment]
You are using `window` in a class property, so it bombs out during initialization.

I have a fix in place, I just want to verify it.

**Comment by DominicTobias** [comment]
Ah ok. You can make an extension of the class and put a dummy for window there for the time being.

**Comment by DominicTobias** [comment]
Please try 8.0.2

**Comment by ArtBIT** [comment]
It bombs on the same line: https://github.com/DominicTobias/react-image-crop/blob/71d03146e104eabce592c7e15907bc86b7feddd7/lib/ReactCrop.js#L224

**Comment by DominicTobias** [comment]
You're looking at 8.0.1, what about 8.0.2?  - https://github.com/DominicTobias/react-image-crop/blob/master/lib/ReactCrop.js#L224

**Comment by ArtBIT** [comment]
That fixes it. But webpack injects `window` object in the build since the target is not `node`. I will send a pull request with what fixed it for me.
