### ISSUE TITLE
Aspect ratio not being enforced correctly

### ISSUE THREAD

**Issue by rgreen312** [DominicTobias/react-image-crop#271]
When passing in an aspect ratio and width, the cropper will originally show the correct crop, but upon resizing, the aspect ratio will change to be 1:1 

Below GIF is using v8.0.3. I've tested with different versions, and this seems to be introduced in 8.0.0, as 7.0.5 works as expected. 

![](https://media.giphy.com/media/jRlHukienxlJ6InWch/giphy.gif)

**Comment by DominicTobias** [comment]
Hi can you send a link to the codesandbox?

**Comment by rgreen312** [comment]
I used the [demo](https://codesandbox.io/s/72py4jlll6) linked from the README of this repo. Only changes I made were to the version of `react-image-crop`

**Comment by DominicTobias** [comment]
Ah ok, do you mind trying it now please/ensure that 8.0.3 is selected for the version?

**Comment by rgreen312** [comment]
Just tried again, but still seeing a square crop even though the aspect is set to 16 / 9
<img width="1325" alt="Screen Shot 2019-06-12 at 11 46 18 AM" src="https://user-images.githubusercontent.com/10169700/59377841-db987500-8d07-11e9-8f38-b1618dadeb74.png">
<img width="1342" alt="Screen Shot 2019-06-12 at 11 47 16 AM" src="https://user-images.githubusercontent.com/10169700/59377843-db987500-8d07-11e9-926d-1339f97b22e5.png">

**Comment by DominicTobias** [comment]
Thanks for reporting this, please try 8.0.4 https://codesandbox.io/s/72py4jlll6

**Comment by rgreen312** [comment]
Looks great! Thanks for fixing so quickly!

**Comment by rgreen312** [comment]
Sorry to bother you again, but it looks like there are still some issues when the crop hits the edge of the image: 
![](https://media.giphy.com/media/SuC4B2GZch91dpfON4/giphy.gif)

**Comment by DominicTobias** [comment]
Hi yep I noticed that too, unfortunately it's too late today and I had an idea to simplify some code at the time so I will have to address this later tomorrow!

**Comment by rgreen312** [comment]
Sounds good, thanks for all your work on this

**Comment by DominicTobias** [comment]
Np, hopefully this is good no in 8.0.5

**Comment by rgreen312** [comment]
Looks great!
