### ISSUE TITLE
Adding ability to use this component to crop videos

### ISSUE THREAD

**Issue by rgreen312** [DominicTobias/react-image-crop#272]
Closing this because it's not an issue with the existing cropper, but I was wondering if you would be willing to add support for cropping video using `react-image-cropper`.  Updating the existing codebase to support this should not be a huge change, and I'd be willing to put in the time to open a PR supporting this if you would be interested in adding it to this library.  This could be accomplished by adding `supportVideo` as a new prop. The biggest change would then be checking the mime type of `src` to determine whether the cropper should render an `<img>` or a `<video>`, which would introduce some new complexity. 

Let me know your thoughts on this, would be interested in getting this working soon!

**Comment by DominicTobias** [comment]
Hi I'm open to this if you want to look into it. Could also potentially be a render prop that allows taking over rendering the img part and replacing it with a video (or anything else that the user wants)

**Comment by rgreen312** [comment]
Great, I'll try to get to this early next week
