### ISSUE TITLE
Crop Image renders larger than parent elements. 

### ISSUE THREAD

**Issue by GilliganL** [DominicTobias/react-image-crop#275]
Hi, I have run into an issue that I haven't seen posted. I'm not sure if this is an actual issue or if there is something I'm missing. 

Without React Crop:
<img width="761" alt="Screen Shot 2019-06-27 at 4 05 06 PM" src="https://user-images.githubusercontent.com/33589045/60304028-5d39f680-98f5-11e9-9eb0-66931955a669.png">

With React Crop:
<img width="845" alt="Screen Shot 2019-06-27 at 4 04 58 PM" src="https://user-images.githubusercontent.com/33589045/60304032-5f9c5080-98f5-11e9-8019-31f86f6c12d2.png">

The first image is not using React Crop and the second one is using React Crop. The image comes in too large with React Crop. Using styles either just cuts off the edges of the image, hiding them, or makes the crop tool positioning incorrect per how it looks. Calling the image with a different height (we're using Cloudinary) also causes the crop tool to be incorrect so the cropped result is different than it shows. Sometimes when you click on the image the first time it rerenders and is the correct size. 

Thank you!

**Comment by DominicTobias** [comment]
Hi I'm not really sure what I'm looking for in these two images - they look the same to me! Are you able to replicate the issue here? https://codesandbox.io/s/72py4jlll6 and if so please link to the image you use

**Comment by DominicTobias** [comment]
Ah I see, ReactCrop is exceeding the expected bounds and there is gray space in the first one. It will be hard for me to see what is doing on without a working example of the issue though, as this might be related to your css

**Comment by GilliganL** [comment]
Hi! I apologize for not responding right away. I resolved the issue fortunately. The problem was that there was another element in one of the ReactCrop parent wrappers. The first parent wrapper (which is where I though height would come from) was view height minus this other element but the second parent wrapper was view height including this other element. The crop tool was using the height of the second parent instead of the direct first parent. I put that element outside of the second parent and now it's rendering correctly. Thanks for the quick response!

**Comment by DominicTobias** [comment]
Ah ok I'm surprised actually as the outer element has `position: relative` it should have used that, unless some children were put inside `<ReactCrop>` element itself. Anyway glad you figured it out.
