### ISSUE TITLE
No longer able to use script in Chrome extension after upgrade from v6.0.13 to v8.1.0

### ISSUE THREAD

**Issue by randombk** [DominicTobias/react-image-crop#278]
After upgrading the library from v6.0.13 to v8.1.0, attempting to use the library in a Chrome extension results in the following error:

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:".

    at Object../lib/ReactCrop.js (ReactCrop.js:107)
    at __webpack_require__ (ReactCrop.js:30)
    at ReactCrop.js:94
    at ReactCrop.js:97
    at webpackUniversalModuleDefinition (ReactCrop.js:3)
    at Object../node_modules/react-image-crop/dist/ReactCrop.js (ReactCrop.js:10)
    at __webpack_require__ (bootstrap:19)
```

Updating extension manifest to `
    "content_security_policy": "script-src 'self' 'unsafe-eval' blob: filesystem: chrome-extension-resource:; object-src 'self'"` serves as a temporary work-around, but is not suitable for long-term use due to security concerns.

**Comment by DominicTobias** [comment]
I will update the package "main" entry to the min version which doesn't have eval() sourcemaps.

For now you can require the min version directly - `'react-image-crop/dist/ReactCrop.min'`
