### ISSUE TITLE
Doesn't work in a functional component

### ISSUE THREAD

**Issue by mtjn** [DominicTobias/react-image-crop#279]
The same component and as far I can see identical logic for a basic test react-image-crop implementation works fine as a class component, but fails in a functional component.

The RIC readme gives a simple example as a functional component so I assume RIC is intended to work in this use-case.

[Class component](https://codesandbox.io/s/react-image-crop-class-demo-mlznm) (works)
[Functional component](https://codesandbox.io/s/react-image-crop-function-demo-gh7uo) (broken)

Have I made a silly mistake, or am I missing something?

**Comment by DominicTobias** [comment]
Hi instead of `setCrop({ crop })` do `setCrop(crop)`

**Comment by mtjn** [comment]
Ahh, can't believe I missed that - thanks, wil lclose now.
