### ISSUE TITLE
Default crop selection issue

### ISSUE THREAD

**Issue by slaxmiprasad** [DominicTobias/react-image-crop#280]
I am setting a default crop when the image is loaded in the _onImageLoaded_ method. I am able to achieve the default crop but when I want to resize it, it is not allowing in the first attempt. I am able to resize the crop from second attempt. 

This is my onImageLoaded method:
private onImageLoaded = (image) => {
    this.imageRef = image;
    let length = image.width < image.height ? image.width : image.height;
    let crop = { width: length, height: length, x: 0, y: 0, aspect: 1 }; // I want a square crop area selected
    this.setState({ crop: crop });
    this.makeClientCrop(crop); //Just showing crop preview by default
    return false;
  };

**Comment by mtjn** [comment]
Hi @slaxmiprasad, I am also experiencing this problem. Why did you close the issue?

@DominicTobias could you please reopen this?

**Comment by designbyadrian** [comment]
But you're already returning false in your example? Did you change something else? I'm having the same issue.
