### ISSUE TITLE
getCroppedImg function has wrong parameter type on README file

### ISSUE THREAD

**Issue by AleffSouza** [DominicTobias/react-image-crop#281]
Hello there,

It looks like the jsdocs is referencing to the wrong type for its image parameter at that `getCroppedImg` function [here](https://github.com/DominicTobias/react-image-crop#what-about-showing-the-crop-on-the-client)
I suppose it should be a [`HTMLImageElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement) instead of `File`.

It's a very simple thing but I believe it may help some typed-oriented people, just like me =)

Best regards

**Comment by DominicTobias** [comment]
Hi, do you mean in the typescript definition?

**Comment by AleffSouza** [comment]
Sorry, I was pointing to the wrong URL:
[https://github.com/DominicTobias/react-image-crop#what-about-showing-the-crop-on-the-client](https://github.com/DominicTobias/react-image-crop#what-about-showing-the-crop-on-the-client)

Basically, I was suggesting to change the jsdocs annotation there from:

```
/**
 * @param {File} image - Image File Object
 * ...
 */
function getCroppedImg(image, crop, fileName) {
```  

To:
```
/**
 * @param {HTMLImageElement} image - Image File Object
 * ...
 */
function getCroppedImg(image, crop, fileName) {
```

**Comment by DominicTobias** [comment]
Ah that's easy enough - updated
