### ISSUE TITLE
Crop produces warning

### ISSUE THREAD

**Issue by jthistle** [DominicTobias/react-image-crop#283]
It looks like this:

```
Warning: State updates from the useState() and useReducer() Hooks don't support the
second callback argument. To execute a side effect after rendering, declare it in the
component body with useEffect(). index.js:1375
    e index.js:1375
    React 3
    t ReactCrop.min.js:417
```

I'm guessing this is coming from outdated use of `useState()` in the cropper.

**Comment by DominicTobias** [comment]
Hm there is no use of useState or hooks in the component, are you sure this isn't coming from your code?

**Comment by jthistle** [comment]
I thought so too (I'm using hooks), but the traceback would suggest otherwise. I'm not using callbacks in my useState hooks either :/

**Comment by DominicTobias** [comment]
If you comment out `<ReactCrop` part from render(), does the error go away?

**Comment by DominicTobias** [comment]
If you comment out `<ReactCrop` part from render(), does the error go away?

**Comment by jthistle** [comment]
Weird, I haven't changed anything and now I can't reproduce this. Seems like a rogue error... sorry about that. Closing.

**Comment by nyaapass** [comment]
I also saw this warning when I was using this component follow the Example of README.md:

```jsx
<ReactCrop src={src} crop={crop} onChange={setCrop} />;
```

search the warning message then I saw someone else also got this warning: [fuafa/not-a-hub/issues/12](https://github.com/fuafa/not-a-hub/issues/12) and there is a [solution](https://github.com/fuafa/not-a-hub/commit/04428e1d5554fe69799b187e0c1a80b171725f85) to avoid this warning: 

```jsx
<ReactCrop src={src} crop={crop} onChange={newCrop => setCrop(newCrop)} />;
```
