### ISSUE TITLE
@types issue

### ISSUE THREAD

**Issue by yasso1am** [DominicTobias/react-image-crop#287]
The typescript definitions I am including from @types/react-image-crop do not include the prop `circleCrop`, which I believe is relatively new.

Error from my IDE: "Property 'circleCrop' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactCrop>"

I will would update this if I knew how, I'll go look to make a comment on that package as well.

**Comment by lemonJS** [comment]
Hey @yasso1am!

My PR for this got merged a few weeks ago:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37317

All you should need is `yarn add @types/react-image-crop@latest`

**Comment by DominicTobias** [comment]
Thanks @lemonJS
