### ISSUE TITLE
Babel5 Builds break in the latest change. 

### ISSUE THREAD

**Issue by ddaza** [DominicTobias/react-image-crop#29]
There is still a lot of us that haven't switched from Babel5 to 6. 
The latest [commit](https://github.com/DominicTobias/react-image-crop/commit/32c81a4838065c3c6344492e10358735ee3fee46)  broke all my builds and I get this error: 
```
ERROR in ./~/react-image-crop/index.js
Module parse failed: /usr/src/app/node_modules/react-image-crop/index.js Line 2: Unexpected token
You may need an appropriate loader to handle this file type.
| //http://stackoverflow.com/a/33683495/414062
| import ReactCrop from './dist/ReactCrop';
| export default ReactCrop;
| 
```
Please consider doing something like this: 
```javascript
var ReactCrop = require('./dist/ReactCrop');
module.exports = ReactCrop;
```

I've tested it and can confirm that this works in Babel 5.

**Comment by DominicTobias** [comment]
Thanks @ddaza, that makes sense I'll test it now

**Comment by DominicTobias** [comment]
@ddaza Please try version 0.1.9 and let me know if that fixes your issue.

**Comment by ddaza** [comment]
:+1: it works! thanks.

**Comment by DominicTobias** [comment]
Cool - thanks for checking
