### ISSUE TITLE
Passing unit as "px" but still height width coming in % 

### ISSUE THREAD

**Issue by garima-birdeye** [DominicTobias/react-image-crop#292]
setting crop : {
           aspect: 1 / 1,
            x: 0,
            y: 0,
            height: 30,
            width: 30,
            unit: "px"
}
but still giving value in percentage..

**Comment by DominicTobias** [comment]
Hi, where is it giving the value as percentage?

**Comment by garima-birdeye** [comment]
in reactCrop class it shows values in percent

**Comment by DominicTobias** [comment]
What does your `onChange` callback look like?

**Comment by garima-birdeye** [comment]
This includes nothing just a setstate


this.setState({
            crop
        });

**Comment by DominicTobias** [comment]
I can't help you if you don't post your code, the important part is if you
are using the first or second argument. If you see here pixels are working
fine - https://codesandbox.io/s/react-image-crop-demo-rmxgq

I will close this if you don't provide more information
