### ISSUE TITLE
Does not work with latest Chrome

### ISSUE THREAD

**Issue by marin-liovic** [DominicTobias/react-image-crop#296]
Just noticed that it does not work anymore in Chrome, Version 76.0.3809.132. Not sure if this is the version that killed it... I tried old version of the lib (6.0.18) and the latest one (8.2.2) and both are broken.

**Comment by marin-liovic** [comment]
Hmm, so the demo works in Chrome. It looks like there might be some issue with css...

**Comment by marin-liovic** [comment]
Just FYI, I had to change parent wrapper display from flex to block to make it show in Chrome, even though it worked like that for months...

**Comment by jwrlee88** [comment]
Hey @marin-liovic, I just ran into the same issue as you and I think you should take a look at this issue: https://github.com/DominicTobias/react-image-crop/issues/288#issuecomment-520729358

it helped me get the crop area back.

**Comment by DominicTobias** [comment]
Hi I'm not able to reproduce it in Chrome 76 on Mac with this demo - https://codesandbox.io/s/72py4jlll6 can you? I wonder if it's caused by some cascading CSS. I may just remove it if it's causing an issue but want to understand how to replicate it

**Comment by DominicTobias** [comment]
Edit - just read comments about the flex container. I think I will remove and people can add if they need it
