### ISSUE TITLE
circularCrop is invisible under black image

### ISSUE THREAD

**Issue by qwwwpp** [DominicTobias/react-image-crop#297]
When crop an image with dark background, the circle of image cropper is invisible
![image](https://user-images.githubusercontent.com/11554486/64562138-245ccb80-d301-11e9-91f3-8839438ae08b.png)
but it works if I use an image with light background
![image](https://user-images.githubusercontent.com/11554486/64562389-c1b7ff80-d301-11e9-97e1-abed8e5f4388.png)

**Comment by DominicTobias** [comment]
Hi good point, maybe a border around the circle will do the trick

**Comment by DominicTobias** [comment]
Fixed in 8.3.1

**Comment by JeevaS0722** [comment]
see this
[](https://github.com/DominicTobias/react-image-crop/issues/64#issuecomment-702721821)
