### ISSUE TITLE
Is fixed crop box supported?

### ISSUE THREAD

**Issue by Komalov** [DominicTobias/react-image-crop#298]
I need to create fixed crop area, so I could move image inside it until pic will fits well. It's not a very rare case for the most UIs because it saves space, so maybe it's possible already, but I cannot get it

**Comment by DominicTobias** [comment]
I like that way of doing it but I found out about that technique after doing this. It's not possible with this library and I don't intend to add it as it is a different way of doing it entirely and there isn't much code sharing, so I think you're better off searching for another lib for that
