### ISSUE TITLE
Calling toDataURL on network image crop

### ISSUE THREAD

**Issue by Janekk** [DominicTobias/react-image-crop#30]
Assuming I will to initialize the cropper with some image URL and I want to be able to edit it (meaning to crop the image and call canvas.toDataURL based on the cropped image). The problem is, I will get 

```
Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

```

while calling `canvas.toDataURL` because the server didn't send `"Access-Control-Allow-Origin: *` response header. In order for the server to send such header I need to load the image with `crossOrigin = 'anonymous'` attribute set. Would it be OK to make it configurable via props that underlying the <image /> (I use `'.ReactCrop--image-copy'` image to load it onto canvas and get dataURL) has `crossOrigin = 'anonymous'` attribute set? (I can issue a PR if such change is OK.)

**Comment by DominicTobias** [comment]
I'm trying to understand what you're doing with `ReactCrop--image-copy` - are you editing the image live as they are changing the crop or something, and also using a remote image url?

**Comment by Janekk** [comment]
Basically my goal is to be able to send the cropped image to the backend and I'm doing it by loading the cropped image area onto `canvas`, reading it to `dataURL` format and sending that base64 payload to the backend. 

But after some considerations I decided to implement this in my wrapper component, no need to bloat the  `react-crop-image` compoentent here. So I'll close this issue now :) Thank you

**Comment by DominicTobias** [comment]
Cool glad you found a solution 👍

**Comment by foodaka** [comment]
@DominicTobias if using a remote URL how to fix this problem?

**Comment by foodaka** [comment]
Basically i want to pass a url as a prop to the component so i can edit images. I dont need react cropper to handle any upload. I am getting the `Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.` error

**Comment by erwinleonardy** [comment]
Hi @Janekk. I know that this is an old post. However, I encountered the same issue. May I know what did you do in the wrapper component? It seems to me that `crossOrigin = 'anonymous' ` is always set after `src` in React.
