### ISSUE TITLE
cropping now showing the real crop

### ISSUE THREAD

**Issue by kimutaiRop** [DominicTobias/react-image-crop#303]
I have been getting my crop canvas show a weird crop for almost 2 days and I was ready to copy code from a working example till i found https://codesandbox.io/s/04w6mvpwm0 showing exactly the same 'false' canvas as mine was

**Comment by DominicTobias** [comment]
Hi, I only have time to support the latest major version of the library which is v8 and that is v5. I suggest you take a look at the official demo link and see what is different: https://codesandbox.io/s/72py4jlll6

Or it could be a bug in that version I haven't checked.

**Comment by kimutaiRop** [comment]
hii.. thanks  so much I think this is working
