### ISSUE TITLE
typescript types don't work when using es6 modules

### ISSUE THREAD

**Issue by MastroLindus** [DominicTobias/react-image-crop#304]
the types definition in @types/react-image-crop don't work properly.

If you try to do 
"import ReactCrop from "react-image-crop";

typescript will flag an error because ReactCrop is not marked as export default in the types file.
Typescript will allow the syntax 
"import * as ReactCrop from "react-image-crop", but that will give an error at runtime because it will result in passing the export object to react.

The types package should export default the ReactCrop component

**Comment by DominicTobias** [comment]
Hi feel free to make a PR to @types, I didn't write or maintain that package and don't use typescript myself so closing this
