### ISSUE TITLE
Dynamic image crop for cropping multiple images in the same page

### ISSUE THREAD

**Issue by kimutaiRop** [DominicTobias/react-image-crop#305]
I have a page where the image crop is created dynamically as soon as the user adds an image to state, user can add a list of images which i loop over, I was wondering if I can share the same function for cropping the image and doing those all other stuff like updating the state for all the images user tries to upload, i triesd adding the ref and id property to each instance of the ReactCrop created dynamically but as soon as the second instance is created, the first crop can no-longer be modified, changing the size of crop of prior added image changes that of later added image instead. despite me accessing the image id and the ref, instead the id still reads the later one
    `<ReactCrop ref={this.currentId} id={`${index}image`}
                                        src={image}
                                        crop={this.state.crop[index]}
                                        onImageLoaded={this.onImageLoaded}
                                        onComplete={this.onCropComplete}
                                        onChange={this.onCropChange}
                                    />`
`makeClientCrop(crop) {
        var id = this.currentId.current.props.id;
        let the_ref = this.getCanverRef(id)
        this.onImageLoaded(the_ref)
        id = parseInt(id,10);
        if (this.imageRef && crop.width && crop.height) {
          const croppedImageUrl = await this.getCroppedImg(
            this.imageRef,
            crop,
            "newFile.jpeg"
          );
          var final_prev = this.state.final_images_preview
          final_prev[id] = croppedImageUrl
          this.setState({
              final_images_preview:final_prev
           });
        }
      }`

**Comment by DominicTobias** [comment]
Hi you should extract it to a component which encapsulates the state and
logic and use that multiple times, using ref etc for that is an anti pattern
