### ISSUE TITLE
Best fit and centering

### ISSUE THREAD

**Issue by FredyC** [DominicTobias/react-image-crop#306]
I know there was related issue #196 in the past and I tried to act based on the advice, but something is not working. I've modified CodeSandbox example, but for some reason when `return false` is used in `onImageLoaded`, no crop area is shown at all.

https://codesandbox.io/s/react-image-crop-demo-nkqvq

What am I missing, please? I just want a fixed rectangle, but positioned initially as best as possible so in most cases a user can just confirm or move slightly.

**Comment by DominicTobias** [comment]
Hi this is ironically easier to do with a pixel crop (square image with percentage problem). I would like to make `onImageLoaded` stuff more intuitive in the future but that will have to wait for a major version change.

The reason it's not working is that when you set the crop yourself after the initial mount you're on your own and have to create a complete crop.

```js
onImageLoaded = image => {
    this.imageRef = image;

    const width = image.width > image.height ? (image.height / image.width) * 100 : 100;
    const height = image.height > image.width ? (image.width / image.height) * 100 : 100;
    const x = width === 100 ? 0 : (100 - width) / 2;
    const y = height === 100 ? 0 : (100 - height) / 2;

    this.setState({
      crop: {
        unit: '%',
        aspect: 1,
        width,
        height,
        x,
        y,
      },
    });

    return false;
  };
```

https://codesandbox.io/s/react-image-crop-centered-demo-2gmxg

**Comment by FredyC** [comment]
Yea, I thought it will be something silly like that. Thanks a lot, very nice. 💯 

It seems it's also possible to use the little hack and run that setState in `setImmediate` instead of `return false` to leave the initial computation being done and then use percents as you have outlined in the FAQ.
