### ISSUE TITLE
Any variable other than "crop" and the dashed lines/functionality go away

### ISSUE THREAD

**Issue by huntermetts** [DominicTobias/react-image-crop#309]
Essentially I am trying to create 2 croppers, one for a profile image and one for a banner image. My goal is to have one with an aspect ratio of 1/1 (profile) and another with the aspect ratio of 3/1 (banner). Because of this I have tried passing the "crop" prop a different value for each instance of react-image-crop, but it seems that when I change the variable name "crop", the dashed lines no longer show and I cannot crop the image. I hope the photos below will provide clarity to the issue. 
![Screen Shot 2019-10-14 at 9 04 49 AM](https://user-images.githubusercontent.com/44845206/66759323-ab074a00-ee65-11e9-9724-603c2fe58bbb.png)
![Screen Shot 2019-10-14 at 9 05 22 AM](https://user-images.githubusercontent.com/44845206/66759328-ad69a400-ee65-11e9-87f9-38f401ca79f3.png)
![Screen Shot 2019-10-14 at 9 26 54 AM](https://user-images.githubusercontent.com/44845206/66759332-af336780-ee65-11e9-9515-ed5a217d3f97.png)
![Screen Shot 2019-10-14 at 9 29 29 AM](https://user-images.githubusercontent.com/44845206/66759338-b0649480-ee65-11e9-9f3a-bd77b0b030c3.png)

**Comment by DominicTobias** [comment]
Hi, what does the logoCrop object look like?

**Comment by huntermetts** [comment]
Hello! Here is a screen shot. Also, thank you. This is super useful!

![Screen Shot 2019-10-14 at 2 04 15 PM](https://user-images.githubusercontent.com/44845206/66776295-a9507d00-ee8b-11e9-9c12-39c070b5401d.png)

**Comment by DominicTobias** [comment]
The crop will only be completed for you on load at the moment. I had issues
checking for invalid crops and completing them after that but might look at
it again at some point.

For now you need to set a valid crop after load (both width and height).

This is easier with pixels when using an aspect ratio.

When the image loads you have the image reference, so you can derive the
height you need to set with that, e.g:

**Comment by DominicTobias** [comment]
```js
logoCrop.height = this.imageRef.height * logoCrop.width / 100
```

P.S Your `<Fragment>` is redundant in your screenshot

**Comment by DominicTobias** [comment]
The problem with % is that it's not straight forward. Take your case where you set width to 95%:

Image = 300x150
==================

Width: 95%

95% of 300px is 285px (300 * 95 / 100)

285px is larger than the whole height, so a square isn't possible.

If you're just trying to set a centered square as default then see: https://github.com/DominicTobias/react-image-crop#how-can-i-center-the-crop

```js
// Center a square percent crop.
const width = image.width > image.height ? (image.height / image.width) * 100 : 100;
const height = image.height > image.width ? (image.width / image.height) * 100 : 100;
const x = width === 100 ? 0 : (100 - width) / 2;
const y = height === 100 ? 0 : (100 - height) / 2;

this.setState({
  logoCrop: {
    unit: '%',
    aspect: 1,
    width,
    height,
    x,
    y,
  },
});
```

**Comment by huntermetts** [comment]
Where would I set a valid crop after load?

**Comment by DominicTobias** [comment]
Anywhere you want it depends what your doing e.g in the click of a button

**Comment by huntermetts** [comment]
So, once I click the button to open the image's upload page, I should set "crop"'s state there instead of in the main state at the top?

**Comment by huntermetts** [comment]
Got it. Thank you.

**Comment by DominicTobias** [comment]
Basically the only crop that will be completed is the first one you pass
in, after that you need to pass in valid crops with width and height.

So for any crop object you want to pass in after the cropper has already
mounted you can set the whole thing then, there is no advantage to having
part of it defined up front, but also nothing wrong, you will just have to
complete the height that you didn’t fill it before using it.

**Comment by huntermetts** [comment]
Ok awesome, thanks again!
