### ISSUE TITLE
Initial crop selection is lost after focus is changed to another input in case user haven't changed the crop selection

### ISSUE THREAD

**Issue by yury-dymov** [DominicTobias/react-image-crop#31]
Hello, first of all thank you for very nice library.

I am facing issue with following workflow:
1) User selects image file from his or her computer to input with file type
2) Initial image is loaded as blob to react-image-crop, which is rendered only after image is selected
3) I would like to have only squared images, therefore I am showing crop rectangle right after image is shown with aspect=1
4a) If user doesn't perform any changes to the cropping area and goes to the next input, initial selection is lost and the whole image is selected. Afterwards it is not longer possible to apply any changes to crop selection
4b) If user perform changes to the cropping area, final selection persists after moving to the next input. It is also possible to perform new changes. In other words, everything works as expected.

Initial selections works fine:
![initial](https://cloud.githubusercontent.com/assets/1292558/14761625/4f02c842-0999-11e6-909e-7f0cbad02546.png)

Initial selection lost and cropping interface doesn't work anymore after moving to the next input:
![after](https://cloud.githubusercontent.com/assets/1292558/14761629/7152787a-0999-11e6-8aa0-8d9f5eea40b7.png)

My source code:
```
import React, { Component, PropTypes } from 'react';
import Crop from 'react-image-crop';

export default class CropWrapper extends Component {
  static propTypes = {
    initialValue: PropTypes.any,
    src: PropTypes.string,
    onChange: PropTypes.func
  }

  componentWillMount() {
    const { x, y, width, height } = this.props.initialValue;

    this.state = { x, y, width, height, aspect: 1 };
  }

  componentDidMount() {
    require('react-image-crop/dist/ReactCrop.css');
  }

  handleCropChange = (crop) => {
//    this.props.onChange(crop);
    this.setState(crop);
  }

  handleCropComplete = (crop) => {
//    this.props.onChange(crop);
    this.setState(crop);
  }

  render() {
    const { x, y, width, height, aspect } = this.state;

    return (
      <Crop
        src={this.props.src}
        crop={{ x, y, width, height, aspect }}
        keepSelection={true}
        onChange={this.handleCropChange}
        onComplete={this.handleCropComplete}
      />
    );
  }
}

```

**Comment by DominicTobias** [comment]
Hi @yury-dymov, I'm having trouble replicating this. What are you passing in `initialValue`? Your code would be a little simpler/more efficient if it was attaching the crop state to `this.state.crop` (no need for destructuring then). Also unless you need to update the state each pixel change as the crop is being dragged it's usually ok to just update the state in `onCropComplete`.

My guess is that when they are clicking in the next box, a parent component is being re-rendered/setting some prop, and that is causing that component to re-render with some different values - but then it's strange that you can't adjust the crop afterwards - can you also not drag it? Maybe put `debugger;` statement in the render to see if it's being re-rendered when you click into the next input and see what values are being passed through. Let me know how it goes!

**Comment by yury-dymov** [comment]
@DominicTobias, thank you for response.

I figured out following:
1) I uploaded 200x400 image (it should be not a square image)
2) My initialValue is {x: 0, y: 0, width: 100, height: 100, aspect: 1}
3a) If I change initialValue to {...,width:30, height:30, ...} everything works fine.
3b) If I change initialValue to {...,width:90, height:90, ...} everything works fine but aspect is broken after performing steps mentioned in the initial message.

In my workflow I would like to have initial square selection with starting point at (0, 0) and side length of min(image_width, image_height).

**Comment by DominicTobias** [comment]
Thanks for the extra details - interesting, sounds like a bug to me I'll take a look

**Comment by DominicTobias** [comment]
I fixed at least one of the issues - are you still have more issue with upgrading to `1.0.0-rc2`?

**Comment by DominicTobias** [comment]
P.S. There are some gotchas when specifying both the width and height with a fixed aspect as this is using percentages - for example 90% & 90% on an image that isn't square would mean that the crop couldn't be square so it has to adjust one of the values. Actually I noticed that at the moment it's adjusting both of them so I need to look into that.

**Comment by yury-dymov** [comment]
@DominicTobias for my case both issues are resolved. Thank you!

**Comment by DominicTobias** [comment]
Ah great!
