### ISSUE TITLE
x,y coordinates always 0,0 on load

### ISSUE THREAD

**Issue by farzd** [DominicTobias/react-image-crop#317]
I've edited the sandbox demo to demonstrate this,
The x,y cooridnates onChange/onComplete from crop/cropPercentage seem to be 0,0 when crop is set without manual dragging, upon manual drag they seem to be accurate

https://codesandbox.io/s/react-image-crop-demo-y6eto
[the values are logged out using console.log]

**Comment by DominicTobias** [comment]
Hi, can you explain what you're trying to achieve? onCropComplete is probably not the right place to do it.

Also you said you want a square crop with a width of 100%, so the only way that can fit is if x is 0 so what you pass in is ignored. If you set the initial crop to be smaller the x has an effect.
