### ISSUE TITLE
ReactCrop__crop-selection on the video appears only after a click

### ISSUE THREAD

**Issue by Valew17** [DominicTobias/react-image-crop#319]
Hello.
If I use the image, there is no problem, but if I use the video, then ReactCrop__crop-selection after initialization is not.
Appears after clicking on the video.
Also does not appear at all if you add keepSelection.
Sorry for my English.

**Comment by Valew17** [comment]
const renderVideo = () => (
                <video autoPlay loop style={{ display: 'block', maxWidth: '100%' }}>
                    <source src={this.props.url} type="video/mp4" />
                </video>
            );
            
            box = <ReactCrop
                    renderComponent={renderVideo()}

                    src={this.props.url}
                    crop={this.props.crop}
                    onChange={(newCrop, newCrop2) => this.props.setCrop(newCrop, newCrop2)}
                    ruleOfThirds
                  />

**Comment by DominicTobias** [comment]
Sorry for the very slow reply on this. I have added a mechanism in 8.4.3 to make this easier. You need to tell ReactCrop when your media has finished loading. For video add this in `onLoadStart`:

```
<video
    autoPlay
    loop
    style={{ display: 'block', maxWidth: '100%' }}
    onLoadStart={e => {
      // You must inform ReactCrop when your media has loaded.
      e.target.dispatchEvent(new Event('medialoaded', { bubbles: true }));
    }}
  >
```
