### ISSUE TITLE
How to access the cropped image?

### ISSUE THREAD

**Issue by jmancherje** [DominicTobias/react-image-crop#32]
Is there an elegant way to take the cropped state and access the cropped image? I would like to crop the image and submit the cropped image to a server and subsequently send to amazon S3 for storage. How can I access the image after cropping to attach to an ajax request?

**Comment by jmancherje** [comment]
I think I may have misunderstood the expected use of this library, with my use case above, would it be best to send the image and the crop object to the server and actually crop the image on the server with a image processing library?

**Comment by DominicTobias** [comment]
The traditional approach is to do it server side, however it is achievable on the client. I believe that @DPr00f has done that https://github.com/DominicTobias/react-image-crop/issues/21#issuecomment-188857644

To summarise -
- When the crop changes (onCropComplete) you need to create the cropped image on a canvas element. You can get a reference to the image from onImageLoaded(crop, image) (2nd param) if you need to.
- Then once you've created the canvas and draw the cropped image on it, you can extract the data with [toDataURL](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) or [toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) (only supported on latest Chrome and FF)

**Comment by jmancherje** [comment]
Thank you for the info. I followed your first comment and did the cropping server side with Jimp, works great. Love the component. Feel free to close this issue
