### ISSUE TITLE
how to use in .tsx   this.fileName && this.imageRef does not exist

### ISSUE THREAD

**Issue by shipcake** [DominicTobias/react-image-crop#320]
when I try .js file evething is OK. but I change to .tsx file this.fileName && this.imageRef throw Error and not use useRef :(

**Comment by siva2502** [comment]
you need to declare this variable within class.

export class ThumbnailDialogContent extends React.Component<IThumbnailDialogContentProps, IThumbnailDialogContentState> {
  imageRef = "";
  fileUrl ="";
.
.
.}

**Comment by DominicTobias** [comment]
Hi I’m not sure what you are referring to, there is nothing about
thumbnails or dialogs in this code?
