### ISSUE TITLE
Input fields gets disabled in renderSelectionAddon attribute

### ISSUE THREAD

**Issue by tikamchand06** [DominicTobias/react-image-crop#321]
I have put a text and added popover in **renderSelectionAddon** attributes. This popover contains the form fields like input, textarea and these fields are disabled. I'm unable to write anything in it.
I'm using **React-Semactic-UI**.

Here is the code.
`<ReactCrop
    src={task.image}
    crop={marker}
    onChange={crop => setState({ ...state, marker: { ...marker, ...crop }, activateMarker: false })}
    onComplete={marker => setState({ ...state, activateMarker: true })}
    renderSelectionAddon={state => (
        <Popup
            content={taskMarkerForm()}
            trigger={<div className="ReactCrop__crop-addon">{markerNames[task.markers.length]}</div>}
            position="top center"
            open={activateMarker}
        />
    )}
    minHeight="50"
    minWidth="50"
    keepSelection
/>`

**Comment by DominicTobias** [comment]
Hi are you able to make a codesandbox using the demo example with it?
Sounds like it’s more likely to be an issue with the actual content

**Comment by tikamchand06** [comment]
Please have a look at the sandbox demo

https://codesandbox.io/s/react-image-crop-demo-4o1t1

**Comment by tikamchand06** [comment]
@DominicTobias Are you fixing this issue?

**Comment by DominicTobias** [comment]
Hi not sure if this is fixable my side since I need the mouse down event to be able to drag the crop. You can fix this your side by stopping the event from bubbling up though: `<textarea rows="4" cols="20" onMouseDown={e => e.stopPropagation()}`

**Comment by DominicTobias** [comment]
Fixed in 8.4.1
