### ISSUE TITLE
minWidth minHeight

### ISSUE THREAD

**Issue by robjensen82** [DominicTobias/react-image-crop#322]
I found that in the `onChange` I needed to restrict `minHeight` and `minWidth`:
```
    onCropChange = (crop, percentCrop) => {
        if (crop.width < crop.minWidth || crop.height < crop.minHeight) {
            return false;
        }
        this.setState({ crop });
    };
```

Perhaps this shouldn't be required? Or the docs need updating?

**Comment by DominicTobias** [comment]
Hi, minWidth is a prop on ReactCrop rather than a prop on the crop object
itself

**Comment by robjensen82** [comment]
Hi Dominic, thanks for that. Works as expected now. Thanks also for your work on this software
