### ISSUE TITLE
Resetting the selection issue

### ISSUE THREAD

**Issue by ankitkanojia** [DominicTobias/react-image-crop#325]
The reset of the selected image for the crop does not work well. once you select image and then try crop and then selection of new file is not display, persisting of previous image is there.

**Comment by DominicTobias** [comment]
Hi again are you talking about the demo? https://codesandbox.io/s/72py4jlll6 ?

It's not part of the library just a quick demo, if you want to only accept images you can add `accept="image/*"` to the input. I'll add it now.
