### ISSUE TITLE
Allow providing explicit image width and height [isAspectInvalid problem]

### ISSUE THREAD

**Issue by chexex** [DominicTobias/react-image-crop#328]
Hello, guys, recently I've noticed a problem with incorrect width and height attributes, received in `onChange` handler.
To understand the problem I will explain my workflow:
1. Get an image info from an external source (image preview, original image height, original image width, original image coord data)
2. Construct new coord data for the preview image based on original data (use % units)
3. Receive data from Crop component, scale it back to original image dimensions
4. Send back to the external source

The problem.
`isAspectInvalid` func uses preview image's height and width, which leads to the creation of a new crop with px units with invalid data.

https://github.com/DominicTobias/react-image-crop/blob/fd4d44e5e87fd8887cb45108ea6b3f6484bf6bfa/lib/ReactCrop.js#L126-L144

My suggestion: add an opportunity to provide original image width and height.

Thanks. :-)

**Comment by DominicTobias** [comment]
Hi are you not displaying the image in it’s original aspect?

**Comment by chexex** [comment]
> Hi are you not displaying the image in it’s original aspect?

I would say yes, I dont display the image in its original aspect. To be precise: 
* original image `5742  x  4064` (1.4128937007874016)
* preview image `500 x 353` (1.4164305949008498)

**Comment by DominicTobias** [comment]
Ok thanks, looks like it's just caused by rounding. Maybe the best approach
is to use the displayed width and height anyway 🤔

**Comment by chexex** [comment]
Hello again :)
I've noticed that  the `makeNewCrop` function accepts the argument `unit`, but most functions call this function without providing this value. (https://github.com/DominicTobias/react-image-crop/search?q=makeNewCrop)
My intention is to add something like `this.props.crop.unit` as an argument to every `makeNewCrop` function call statement. Is it ok?

**Comment by DominicTobias** [comment]
Hi @chexex, Sorry for not looking at this yet. Started a new job last week and working all hours atm on that and a side project so not much inclination to work on this atm!

Looking at the code I think you're right. Not sure what I was thinking there but could move all unit logic to makeNewCrop, if none is present default to px and otherwise use the provided unit. Do you think this will fix something? I'm too tired to look at the code now :P

**Comment by DominicTobias** [comment]
P.S As far as using naturalWidth and naturalHeight for aspect, need to think as to whether this is a better default option to have anyway

**Comment by chexex** [comment]
I'm not sure that what i've wrote really solve the problem. (I've altered the code and this bring me to another set of problems such as unstable crop frame (happened when i changed `makeNewCrop`)

I close the issue for now. 

When I have stable solution, I will make a pull request.

Thanks for your time and this library :)
