### ISSUE TITLE
[loop infinity] keep re-render if using setState in onImageLoaded function

### ISSUE THREAD

**Issue by hieunguyendut** [DominicTobias/react-image-crop#329]
I used onImageLoaded to centered crop box. But It keep re-render component forever when I using setState here. I guess this function re-render image every time it called. Anyone have an idea to fix this. Thank you so much

```js
onImageLoaded = image => {
    console.log("onImageLoaded")
    const { width, height } = image;
    const x = width / 2 - 130;
    const y = height / 2 - 130;

    this.setState({
      crop: {
        unit: "px",
        x,
        y,
        width: 262,
        height: 262
      }
    });

    return false;
  };
```

My component
```js
  onImageLoaded = image => {
    console.log("onImageLoaded")
    const { width, height } = image;
    const x = width / 2 - 130;
    const y = height / 2 - 130;

    this.setState({
      crop: {
        unit: "px",
        x,
        y,
        width: 262,
        height: 262
      }
    });

    return false;
  };
```

result
![Screenshot 2019-12-16 at 14 02 18](https://user-images.githubusercontent.com/30219446/70885879-b49b6280-200c-11ea-9e1a-7b932dc9ad39.png)

Browser: chrome
Lib:
"react-image-crop": "^8.4.2",
"react": "16.10.2",

**Comment by DominicTobias** [comment]
Hi do you have an aspect set? And are you able to reproduce this issue on
the sandbox demo? Thanks

**Comment by hieunguyendut** [comment]
Hi,  I don't set aspect because I already set width and height. I will do reproduce problem on sandbox now.

**Comment by hieunguyendut** [comment]
Hi DominicTobias, apologize for me. After I setup on sandbox. I realized that work fine on sandbox.  I will close issue now. Thank you so much
