### ISSUE TITLE
Empty cropper while uploading .svg files without height/width attributes

### ISSUE THREAD

**Issue by Inveth** [DominicTobias/react-image-crop#330]
Hello,

I recently tried to crop several svg files and got an issue when the exported svg images from illustrator or any svg file that does not contain height/width attribute will render as 0x0px image in cropper.

Here's an sample SVG file :
https://image.flaticon.com/icons/svg/12/12096.svg

![aa](https://user-images.githubusercontent.com/26462649/71666828-f04f5f80-2d62-11ea-81a2-09025a83e952.jpg)

**Comment by DominicTobias** [comment]
Hi firstly update to 8.5.0 as the background of the component was set to black for some reason which made your SVG look entirely black. Next you have to have to give the component a width for the SVG to show - it won't automatically stretch the component out like an image will (that's just a browser thing which I can't change).

So make .ReactCrop fill a container with something like `flex`, or just give it a fixed width and you will see the SVG. e.g. `.ReactCrop { width: 500px }` or `<ReactCrop style={{ width: 500 }}>` or if you render it in a flexbox container then make ReacCrop fill the container with `<ReactCrop style={{ flex: 1 }}>`
