### ISSUE TITLE
Chrome 79.0.3945.88 not display preview image

### ISSUE THREAD

**Issue by leogoesger** [DominicTobias/react-image-crop#333]
It looks like the preview image is not being displayed in the newer version of Chrome. Downgrading Chrome works just fine.

I traced down to this css property:

`max-height: -webkit-fill-available;` under `.ReactCrop__image`. Removing that fixing the issue. `fill-available` is returning 0.

<img width="1160" alt="img" src="https://user-images.githubusercontent.com/16042023/71998756-0f337300-31f5-11ea-987c-ea005bc0decb.png">

**Comment by DominicTobias** [comment]
Hi this property is no longer in the codebase because of issues, what
version are you using?

**Comment by leogoesger** [comment]
I guess there is a version issue. Thank you
