### ISSUE TITLE
renderSelectionAddon disables drag / panning functionality

### ISSUE THREAD

**Issue by DominikHoffendahl** [DominicTobias/react-image-crop#334]
When using the `renderSelectionAddon` property to add content inside of the crop area, the corner handles work as before, whereas the user is not able to move the crop area itself anymore. This only happens the drag starts within the selection addon content.

![image](https://user-images.githubusercontent.com/29222809/72612979-9b991080-392e-11ea-8cd2-e2cf645591ba.png)
Start drag within the purple area: works ✅
Start drag within the red area: fails ❌

This can be reproduced with the following code:
```
const fullImageCrop = 
    unit: '%',
    x: 0,
    y: 0,
    width: 100,
    height: 100,
};

const [ crop, setCrop ] = useState(fullImageCrop);
const renderReadArea = (state) => <div style={{width: '100%', height: '100%, backgroundColor: 'red';}}>Sepp</div>;
... 

<ImageCrop
    src="my.jpg"
    crop={crop}
    onChange={setCrop}
    renderSelectionAddon={renderReadArea}
/>
```

**Expected behaviour**
Regardless of what I render as the selection addon, I want to be able to drag the whole area. Furthermore, I want the red area to cover the entire content of the crop area (height 100%), which is not possible without a style overwrite on the parent container.

**Solution**
Attaching the following style to `.ReactCrop__selection-addon` resolves the issue for me:

```
height: 100%; // solves the content styling issue
pointer-events: none; // solves the drag issue
```

**Comment by DominicTobias** [comment]
Thanks for the detailed issue, however I wouldn't describe this as a bug since I cannot predict what the user wants to do with the addon - it could well be that they don't want to effect the underlying crop. The feature was actually added by a user who wanted to add a text input, and in the case of adding inputs you don't want to affect the underlying crop when clicking them for example.
