### ISSUE TITLE
Not working on IE 10

### ISSUE THREAD

**Issue by ITSWYoo** [DominicTobias/react-image-crop#335]
![image](https://user-images.githubusercontent.com/16359727/72713321-318f9e00-3bb0-11ea-9a1b-57e19dd26e48.png)

Can i use on IE 10?

**Comment by DominicTobias** [comment]
Hi, sorry it is untested on IE10 and I don't intend to support it so I'm not surprised if it's broken!

**Comment by ITSWYoo** [comment]
@DominicTobias Thx 👍
