### ISSUE TITLE
Example with hooks and dataURL 

### ISSUE THREAD

**Issue by omikulcik** [DominicTobias/react-image-crop#336]
Sharing my example with hooks and dataURL image after crop. Might be helpful for someone.

https://codesandbox.io/embed/objective-curie-t13vy?fontsize=14&hidenavigation=1&theme=dark

**Comment by St1myL** [comment]
Thx for sharing the code!

**Comment by melotek** [comment]
also You can type  
const [crop, setCrop] = useState({
    aspect: "",
    unit: "%",
    x: 25,
    y: 25,
    width: 50,
    height: 50
  });

**Comment by DominicTobias** [comment]
Thanks I've made a fork of this and linked on Readme except switched back to using toBlob since it's a bad idea to use toDataURL unless you have some specific reason like supporting IE10
