### ISSUE TITLE
Same Image selected twice does not trigger a DOM event

### ISSUE THREAD

**Issue by nikitasheremet** [DominicTobias/react-image-crop#339]
If you were to select the same image twice (using an input with type file), the second selection of the file does not trigger a DOM event.

**How to reproduce**
This error occurs in your sandbox demo as well. To replicate add a console log to the function onSelectFile with any message and attempt to add the same file twice, you will only see one console log output.

**Comment by DominicTobias** [comment]
Hi, selecting a file is not part of the library just the demo. This is a
common issue you can google about -
https://stackoverflow.com/questions/12030686/html-input-file-selection-event-not-firing-upon-selecting-the-same-file#

That answer has a solution for example
