### ISSUE TITLE
The preview image is only available if the crop is manipulated manually (React-Admin)

### ISSUE THREAD

**Issue by g3n35i5** [DominicTobias/react-image-crop#341]
I like your cropping tool very much, it is easy to use and works very well.
Unfortunately it does not update my preview image after the image has been loaded. I used your sample code and adapted it to my needs (I use your tool in react-admin).

I'm afraid that my "imageRef" property on my state variable is not set in time and still an old "version" of the state variable is used. Could you maybe help me how to adjust my code so that the preview image is already displayed after loading the image?

You can find my code [here](https://github.com/g3n35i5/shop-db2-react-admin/blob/master/src/shared/fields/EditableImageField.tsx)

**Edit**: By the way, I already tried to use the code from PR #340, unfortunately that didn't work either.

<img src="https://i.stack.imgur.com/eaOaQ.gif" width="300">

**Comment by DominicTobias** [comment]
Hi, since imageRef is not something that needs to trigger a render you are better off using a ref object for it since setState is async.

const imageRef = useRef<HTMLImageElement>(null);

const onImageLoaded = image => {
       imageRef.current = image;
}

// Access with `imageRef.current`

**Comment by g3n35i5** [comment]
Thanks a lot @DominicTobias, with a little change your solution works great!
The type must be `HTMLImageElement | null` in order to work:
```typescript
const imageRef = useRef<HTMLImageElement|null>(null);
```
