### ISSUE TITLE
Make <img> not draggable

### ISSUE THREAD

**Issue by aalster** [DominicTobias/react-image-crop#348]
Currently the <img> element itself is draggable by default (when user misses crop element and starts dragging the image).

To prevent this you could:
```
<ReactCrop
    // ...
    className="disable-image-drag" // add css class to ReactCrop
/>
```
```
// with these styles
.disable-image-drag img {
    user-select: none;
    -moz-user-select: none;
    -webkit-user-drag: none;
    -webkit-user-select: none;
    -ms-user-select: none;
}
```

I think this should be enabled by default

**Comment by DominicTobias** [comment]
Thanks seems to make sense will have to check it has no unintended
consequences but probably fine. Are you using locked crops? usually if they
miss the crop it would start drawing another crop

**Comment by aalster** [comment]
Yes, crop is locked in my case

**Comment by DominicTobias** [comment]
Since this could be an accessibility concern I'll leave it up to people to implement in CSS if they wish to. P.S. The `.ReactCrop--locked` can also be used
