### ISSUE TITLE
Why the images are flipping while taking it from camera after cropping? 

### ISSUE THREAD

**Issue by mashish584** [DominicTobias/react-image-crop#350]
![IMG_0956](https://user-images.githubusercontent.com/33250693/79227887-3944a300-7e7e-11ea-8922-c934ae505a9c.PNG)

**Comment by DominicTobias** [comment]
This is a browser issue you can fix with an external library - refer to https://github.com/DominicTobias/react-image-crop#how-to-correct-image-exif-orientationrotation

**Comment by JustFly1984** [comment]
@DominicTobias  Have same issue on IPhone7+after cropping an image getting it rotated on the side.

**Comment by mashish584** [comment]
@JustFly1984  Have you tried the library mentioned by @DominicTobias . It worked for me.
