### ISSUE TITLE
Background transparent or can change a color

### ISSUE THREAD

**Issue by HidemitsuHashimoto** [DominicTobias/react-image-crop#351]
Hi. I used and liked this component in my project. I need to crop a image in png format with background transparent but i dont know how can i do it.

**Comment by DominicTobias-b1** [comment]
Hi it should just work as, if you are generating a crop preview then make sure you use toBlob with image/png not image/jpeg

**Comment by HidemitsuHashimoto** [comment]
Wow. Worked. Thank you so much.
