### ISSUE TITLE
Editable shape of the crop

### ISSUE THREAD

**Issue by oyeanuj** [DominicTobias/react-image-crop#352]
Hi @DominicTobias  , thank you for creating this library - this looks great!

I'm curious it is possible to let the user create the crop shape rather than giving a pre-determined width and height? So, a user could take an image and create a square crop or rectangular crop?

I noticed the section that states that if one dimension is specified, the other is calculated given the aspect ratio but in this case I want to let the user decide the aspect ratio.

Apologies if I missed this option that already exists!

**Comment by DominicTobias** [comment]
Hi the library is controlled so you pass the crop setting in, that means it
can start with no crop and allow the user to draw a free crop, or you can
have some control like a drop down or two input boxes and let the user
select aspect ratios - it’s up to you

**Comment by kinucris** [comment]
Would there be the possibility to give the user the option to do it like Photoshop's "_Polygonal Lasso Tool_" and select a part of the image through several clicks?

![uapqNRW](https://user-images.githubusercontent.com/1749118/80012590-e8e3cb80-84a3-11ea-84c8-fbceb06d8d30.gif)

**Comment by DominicTobias-b1** [comment]
@kinucris it's an interesting idea but this lib is written specifically for rectangles and doesn't think about custom shapes in any way - it would basically be a complete re-write so that rectangle crops could be swapped out with other types of crops. Not something I intend to do sorry!
