### ISSUE TITLE
align crop on center with aspect 16 / 9 

### ISSUE THREAD

**Issue by luansantosti** [DominicTobias/react-image-crop#353]
Hey guys, this isn't an issue, actually, I need a little help here.
I'm trying to align the crop when image loaded on the center (vertically), however, I need the width start with 100% and keep the aspect 16/9.

Current behavior: 
![Screen Shot 2020-04-30 at 12 55 29 PM](https://user-images.githubusercontent.com/6179731/80731962-fd4a4880-8ae1-11ea-8f52-9f32b9975eca.png)

Expected result:
![Screen Shot 2020-04-30 at 1 02 14 PM](https://user-images.githubusercontent.com/6179731/80732529-d4768300-8ae2-11ea-96b8-ac435a18f12c.png)

Initial crop: 
`const defaultCrop = { unit: '%', width: 100, aspect: 16 / 9 };`

Any ideas?

**Comment by DominicTobias-b1** [comment]
Hi, this requires knowing the image dimensions so you should set the crop in `onImageLoad` callback:

```js
const onLoad = useCallback(img => {
  setImgRef(img);

  const aspect = 16 / 9;
  const width = img.width > img.height ? 100 : ((img.height * aspect) / img.width) * 100;
  const height = img.height > img.width ? 100 : (img.width / aspect / img.height) * 100;
  const y = (100 - height) / 2;
  const x = (100 - width) / 2;

  setCrop({
    unit: '%',
    width,
    y,
    aspect,
  });

  return false; // Return false if you set crop state in here.
}, []);
```

**Comment by luansantosti** [comment]
Nice! it works, thanks man!
