### ISSUE TITLE
Image border causes "Maximum update depth exceeded" error

### ISSUE THREAD

**Issue by jonhaddow** [DominicTobias/react-image-crop#355]
- Go to https://codesandbox.io/s/wild-sun-bvg77?file=/src/App.js
- Click "Set bad crop data" in rendered view
- Error: Maximum update depth exceeded should be thrown

version 8.6.2

Possibly related to this https://github.com/DominicTobias/react-image-crop/issues/347 but in this scenerio, it only happens when a border is set on the image. (See `styles.css`)

**Comment by DominicTobias** [comment]
Hey thanks for the easy repro, I'll take a look but probably not for a while tbh. Is there a specific reason to set the border on the image rather than on `.ReactCrop`? i.e.

```css
.ReactCrop {
  border: 1px solid red;
}
```

**Comment by jonhaddow** [comment]
No particular reason, thanks for the workaround!

**Comment by DominicTobias** [comment]
Fixed in 8.6.3

**Comment by jacob-fueled** [comment]
@DominicTobias so actually, I do not experience this issue in 8.6.2, but I do on 8.6.3.

**Comment by DominicTobias** [comment]
Damn I know what's wrong, will fix in next release and deprecate 8.6.3

**Comment by jacob-fueled** [comment]
Yahoo! Cannot reproduce on 8.6.4 😁

**Comment by DominicTobias** [comment]
> Yahoo! Cannot reproduce on 8.6.4 😁

Cool thanks 👌
