### ISSUE TITLE
How to increase side cropping corners 4 to 8

### ISSUE THREAD

**Issue by ravichauchan** [DominicTobias/react-image-crop#356]
How to increase side cropping corners 4 to 8. Check below image :
![Screenshot from 2020 05 17 16 12 27 png  PNG Image  1366 × 768 pixels    Scaled  83  ](https://user-images.githubusercontent.com/18674799/82147344-b479ea00-986c-11ea-8605-edb67bc9a8b2.png)

And i am using below code:
crop: {
        unit: '%',
        width: 100,
        height: 100,
        aspect: 16/9,
      },
According to above code we are getting 4 side cropping corner only. like below images:
![testing-img-cropper](https://user-images.githubusercontent.com/18674799/82147972-fa37b200-986e-11ea-8ad1-8c5b55851cfe.png)

So please help me..

**Comment by DominicTobias** [comment]
Those are removed when using an aspect crop because you can’t change the
width or height individually they always move together, it wouldn’t work
just trying to change one of them

**Comment by DominicTobias** [comment]
(Otherwise it wouldn’t be a valid aspect)
