### ISSUE TITLE
Incorrectly cropped vertical photo

### ISSUE THREAD

**Issue by fivemru** [DominicTobias/react-image-crop#357]
Hello, thank you for a good tool!

I ran into a problem that vertical photos from some phones are cropped incorrectly. The photo was taken vertically, inserted also vertically. In metadata, the width is greater than the height, the orientation is vertical.

Details:
- https://codesandbox.io/s/beautiful-wildflower-kobkt
- [problem_photo.zip](https://github.com/DominicTobias/react-image-crop/files/4640996/problem_photo.zip) (2.4M)
- photo metadata https://www.metadata2go.com/result/d2c98b36-5daf-4f8f-b1b4-183e087b4c38
![image](https://user-images.githubusercontent.com/30273470/82159875-26b4f380-989a-11ea-9718-30dd7c5261a8.png)
But when I select a photo, it is inserted vertically (win 10 x64, chrome 81.0.4044.138)
- result 
![image](https://user-images.githubusercontent.com/30273470/82159971-b6f33880-989a-11ea-8061-a3d97ea93083.png)

**Comment by fivemru** [comment]
The solution I found - after creating and loading the photo via Image () - draw the photo in canvas, and only then transfer it to ReactCrop.

https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-07xj8?file=/src/App.js:2221-2230

Result:
![2020-05-18_005229](https://user-images.githubusercontent.com/30273470/82161048-523bdc00-98a2-11ea-9a1c-95512816635e.png)

**Comment by DominicTobias** [comment]
Hi, thanks closing as this is documented in https://github.com/DominicTobias/react-image-crop#how-to-correct-image-exif-orientationrotation

It's a general problem with some photos
