### ISSUE TITLE
Tainted canvas error if you are cropping an image from url

### ISSUE THREAD

**Issue by JuxhinB** [DominicTobias/react-image-crop#358]
ImageCropper.tsx:273 Uncaught (in promise) DOMException: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.

**Comment by DominicTobias-b1** [comment]
This is an issue with your crop preview and not specific to this lib - checking google - https://www.google.com/search?q=Uncaught+(in+promise)+DOMException%3A+Failed+to+execute+%27toBlob%27+on+%27HTMLCanvasElement%27%3A+Tainted+canvases+may+not+be+exported.&oq=Uncaught+(in+promise)+DOMException%3A+Failed+to+execute+%27toBlob%27+on+%27HTMLCanvasElement%27%3A+Tainted+canvases+may+not+be+exported.&aqs=chrome..69i57.1028j0j7&sourceid=chrome&ie=UTF-8

**Comment by DominicTobias-b1** [comment]
You can add `crossorigin="anonymous"` to ReactCrop

**Comment by JuxhinB** [comment]
Yeah it's not your issue but leave a note or something, not all of us are canvas experts, that's why we use the library. Thank you for your great work but don't migrate issues.

**Comment by namratasaun** [comment]
> You can add `crossorigin="anonymous"` to ReactCrop

this, doesnt load the image if seen on network tab, it just shows failed.
