### ISSUE TITLE
Big size images are not cropped properly.

### ISSUE THREAD

**Issue by thebinod7** [DominicTobias/react-image-crop#362]
Image cropper is working fine for small image size. But, I can't get exact cropped image for large images Like 4272 X 2824 image size. Here is my my code 
`const canvas = document.createElement("canvas");
  const scaleX = image.naturalWidth / image.width;
  const scaleY = image.naturalHeight / image.height;
  canvas.width = Math.ceil(crop.width);
  canvas.height = Math.ceil(crop.height);
  const ctx = canvas.getContext("2d");

  ctx.drawImage(
    image,
    crop.x * scaleX,
    crop.y * scaleY,
    crop.width * scaleX,
    crop.height * scaleY,
    0,
    0,
    crop.width,
    crop.height
  );`

**Comment by DominicTobias-b1** [comment]
Hi please try it here: https://codesandbox.io/s/72py4jlll6

If you have the problem please attach a screenshot showing it and also the image you are using and if you changed any settings there

**Comment by chadlittle** [comment]
I had the same issue and the sandbox (naturalHeight/naturalWidth) solved my problem.

**Comment by DominicTobias-b1** [comment]
This is using naturalWidth/Height in the sandboxes so I guess you're looking at an old version

https://codesandbox.io/s/72py4jlll6?file=/src/index.js:1317-1370
https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o?file=/src/App.js:2131-2184
