### ISSUE TITLE
onChange doesn't trigger second time !!

### ISSUE THREAD

**Issue by Moji0098** [DominicTobias/react-image-crop#366]
first time that click select file and select an image ReactCrop open and i crop image and upload it where i want , 
but second time that i select file and select _previous image_ **onChange** doesn't trigger !! 
i think that's problem is from core of browser! 
how do you solve this issue ?

**Comment by DominicTobias** [comment]
Hi as you thought this is a general browser issue since the `value` of the input doesn't change. In the change event you can set it to null e.g. `e.target.value = null`
