### ISSUE TITLE
unit on onChange going from % to px.

### ISSUE THREAD

**Issue by KevinMendes** [DominicTobias/react-image-crop#369]
Hello everyone, I set my initialState like this : 
```
    const [crop, setCrop] = useState({
        unit: '%',
        x: 40,
        y: 50,
        width: 20,
        height: 10,
    });
```

But when I use `onChange={newCrop => setCrop(newCrop)` , the unit get change into px. So my crop's console.log look like this one : 

```
aspect: undefined
height: 54
unit: "px"
width: 144
x: 288
y: 270`
```

Is anyone know how to fix unit at % ? 

Thank you

**Comment by DominicTobias** [comment]
Hi the [second parameter](https://github.com/DominicTobias/react-image-crop#onchangecrop-percentcrop-required) is the percent crop:

```js
onChange={(_, newCrop) => setCrop(newCrop)}
```

**Comment by KevinMendes** [comment]
Thanks you it's perfect now :)

**Comment by AJR07** [comment]
This should be clarified in the documentation
