### ISSUE TITLE
Unit going from % into px when onChange

### ISSUE THREAD

**Issue by KevinMendes** [DominicTobias/react-image-crop#370]
Hello. 
I have a problem with my hook setCrop. When I use onChange={newCrop => setCrop(newCrop)} my initialState's unit set in %, is change into px. But i really need to get the x, y, width et height in %, is someone know how to solve this problem?

**Comment by DominicTobias** [comment]
Hi, why are you raising this issue again? Did my answer not work over here? https://github.com/DominicTobias/react-image-crop/issues/369

**Comment by KevinMendes** [comment]
Sorry I post a second time because my issue wasn't in my github board, I close it
