### ISSUE TITLE
core-js dependency

### ISSUE THREAD

**Issue by nvlled** [DominicTobias/react-image-crop#371]
core-js is listed as a dependency in package.json. Is it required? How does it affect the size of the package?

**Comment by DominicTobias** [comment]
It shouldn’t do the Babel config is:

      "@babel/preset-env",
      {
        "useBuiltIns": "entry",
        "corejs": 3
      }

That means it will only poly fill on demand if needed. I noticed browser list is quite permissive I think I’ll change that to target modern browsers now, although I’m not using features that would require any extensive polyfilling to my knowledge. I’ll update browserlist anyway.

**Comment by DominicTobias** [comment]
core-js is now a dev dep, will go up in the next release (8.6.11)
