### ISSUE TITLE
Cropping without losing resolution

### ISSUE THREAD

**Issue by aliemami** [DominicTobias/react-image-crop#373]
Is there anyway to crop the image using this library without losing resolution. currently I'm using the library and it seems the quality and dimension of the image depends on the size of my browser window. I would like to keep the original resolution of the image. the below image is result of the cropping the same area of an image with different sizes of the browser window 
   
 const [crop, setCrop] = useState({ unit: "%", width: 30, aspect: 16 / 9 });

<img width="554" alt="Screen Shot 2020-06-25 at 6 44 31 PM" src="https://user-images.githubusercontent.com/382247/85803160-9083b100-b714-11ea-8e21-3c6b7fab1e36.png">

**Comment by DominicTobias** [comment]
Hi recently I updated the hook example to increase the quality of the crop preview, see my last comment here to see the difference: https://github.com/DominicTobias/react-image-crop/issues/263

However if you want to crop on the original image size then you either need to find a library which can programmatically crop an image without it needing to be visually on the screen, or you need to keep an off screen image as some people have mentioned doing in that thread, and generate a canvas from that instead

**Comment by aliemami** [comment]
Thank you, it makes sense, somewhere at #263 you mentioned that you are going to add the solution to the project, is that still a plan?

**Comment by aliemami** [comment]
modifying the getResizedCanvas function seems to be doing the job, this is my code, please let me know if you see a problem or a flow. thank you. 


    const getResizedCanvas = () => {
        const scaleX = imgRef.current.naturalWidth / imgRef.current.width;
        const scaleY = imgRef.current.naturalHeight / imgRef.current.height;
        const tmpCanvas = document.createElement("canvas");
        tmpCanvas.width = Math.ceil(crop.width*scaleX);
        tmpCanvas.height = Math.ceil(crop.height*scaleY);

        const ctx = tmpCanvas.getContext("2d");
        const image = imgRef.current;
        ctx.drawImage(
            image,
            crop.x * scaleX,
            crop.y * scaleY,
            crop.width * scaleX,
            crop.height * scaleY,
            0,
            0,
            crop.width*scaleX,
            crop.height*scaleY,
        );

        return tmpCanvas;
    }

**Comment by DominicTobias** [comment]
Hi are you doing the approach where imageRef is a reference to a full size
off screen image?

Since this is such a company problem I might make some utility functions to
help with it, but no plans to do it that soon tbh I’m busy with some other
stuff at the moment

**Comment by JanderSilv** [comment]
The solution of @aliemami works for me.

**Comment by samstanding** [comment]
I ran into this issue today and solved it by removing the getResizedCanvas function altogether. I saw the comment on the hooks codesandbox, "We resize the canvas down when saving on retina devices otherwise the image will be double or triple the preview size." but was unable to replicate this bug. I tested on an iPhoneXS, MacBook Pro and Chromebook and experienced the same results.

**Comment by DominicTobias** [comment]
Closing as the latest code in the demo should have good quality (and adjusts for retina), thanks for the problem solving ^
