### ISSUE TITLE
how to keep exif inside image after crop or resize or compression ?

### ISSUE THREAD

**Issue by congconnectiv** [DominicTobias/react-image-crop#376]
**Version**
"react": "^16.11.0",
"react-image-crop": "^8.6.4",

**Expected behaviour**
Cropping or compressing image remove the exif from the output image.
How to keep exif inside the output image ?

**Comment by DominicTobias-b1** [comment]
Hi, this is a general problem better asked or looked for on Google I haven't got any experience of it:

https://www.google.com/search?q=javascript+add+exif+data+to+canvas+toblob&oq=javascript+add+exif+data+to+canvas+toblob&aqs=chrome..69i57.14867j0j7&sourceid=chrome&ie=UTF-8

e.g.
https://stackoverflow.com/questions/33361443/is-it-possible-to-modify-the-exif-data-of-an-image-taken-from-canvas-in-html5
