### ISSUE TITLE
minWidth and minHeight

### ISSUE THREAD

**Issue by msalsas** [DominicTobias/react-image-crop#38]
Hi, I was trying your awesome component and all seems to work great except the `minWidth` and `minHeight` options. Looking at the code I see in ReactCrop.jsx at line 476:

    clamp(num, min, max) {
        return Math.min(Math.max(num, min), max);
    }

used at line 171 with `minWidth` option:

    newWidth = this.clamp(newWidth, this.props.minWidth || 0, maxWidth);

and at 196 with `minHeight`:

    newHeight = this.clamp(newHeight, this.props.minHeight || 0, maxHeight);

Below, at 245 and 246:

    crop.x = this.clamp(newX, 0, 100 - newSize.width);
    crop.y = this.clamp(newY, 0, 100 - newSize.height);

It seems to be calculating the cropping area without taking into account the `minWidth` and `minHeight`. All next `clamp` executions also define the `min` values as 0.
I've tried to change those `min` parameters with `this.props.minWidth || 0`, but then I get a weird behaviour (width becomes fixed). Any workaround?

**Comment by msalsas** [comment]
Oh! What a mistake! Sorry, I was using `minWidth` and `minHeight` as `crop` parameters instead of as a `props` directly.

**Comment by DominicTobias** [comment]
Hehe glad it worked! Let me know if there are any probs
