### ISSUE TITLE
Is it possible to customize some text captions to images?

### ISSUE THREAD

**Issue by shangdev** [DominicTobias/react-image-crop#382]
Sometimes, some images want to add some background elements as a short description. I only see that this library supports cropping images, Is it possible to customize some text captions to images?

**Comment by DominicTobias-b1** [comment]
Hi this lib is just a simple cropper with no annotations or filters etc, if you want something like that you could buy [doka](https://gumroad.com/a/611955827) or there might be some other free lib which does it but I'm not sure
