### ISSUE TITLE
[Feature] Add support for scale property

### ISSUE THREAD

**Issue by akshaybosamiya** [DominicTobias/react-image-crop#383]
Hello,

Image cropper stopped working properly whenver outer element of cropper having transform scale property. It won't work smooth as it expected. It will starting lag while moving cropper as well changing size of cropper.

Demo Link: https://codesandbox.io/s/react-image-crop-demo-with-scale-property-dj9ut?file=/src/index.js

Suggestion:
We can pass scale prop to react-image-crop lib. It should adjust this scale value while drawing/moving cropper.

**Comment by DominicTobias** [comment]
The lib has a scale property now (v9), though this is going away in v10 it will still be possible to directly scale the image (see v10 notes when released)
