### ISSUE TITLE
Crop area is hidden and the element appears below the image

### ISSUE THREAD

**Issue by ChrisJVoss** [DominicTobias/react-image-crop#385]
I am experiencing some weird behavior. The "ReactCrop__crop-selection" div appears below the uploaded image and dragging anywhere on the image causes the border surrounding the image to expand proportional to the drag.
Notice that there isn't any change in the cursor and no visual display of the crop area.

All the relevant code is below.

version: "react-image-crop": "^8.6.5",
```  
const [crop, setCrop] = useState({
    unit: '%',
    width: 20,
    aspect: 16 / 9,
  });
  const [file, setFile] = useState('');

  const onSelectFile = (e) => {
    if (e.target.files && e.target.files.length > 0) {
      const reader = new FileReader();
      reader.addEventListener('load', () =>
        setFile(reader.result),
      );
      reader.readAsDataURL(e.target.files[0]);
    }
  };

return (
  <input type="file" accept="image/*" onChange={onSelectFile} />
  {file && (
   <ReactCrop
      src={file}
      crop={crop}
      ruleOfThirds
      onChange={crop => setCrop(crop)}
    />
  )}
)
```
![cropBehavior](https://user-images.githubusercontent.com/29046393/93150065-044aaf80-f6ad-11ea-8e1f-6cdc890b406e.png)
![dragBehavior](https://user-images.githubusercontent.com/29046393/93150400-dfa30780-f6ad-11ea-8a85-3f4b4b055107.gif)

**Comment by tomiplaz** [comment]
@ChrisJVoss You need to `import "react-image-crop/dist/ReactCrop.css";`

**Comment by ChrisJVoss** [comment]
@tomiplaz Thank you! That was it.
