### ISSUE TITLE
How to crop large images from mobile device width?

### ISSUE THREAD

**Issue by gopinav** [DominicTobias/react-image-crop#391]
Hello,

I'm working on a feature where I need to upload images and crop them to a minimum of 1280x640. The original image is 1280px width and 640px height.  Once I upload the image, the image takes up the size of the container which is 640x320. Since I have set crop size to be 1280x640, I get half of the image blacked out after I 'Finish Cropping'. How should I go about solving this?

Below is the image after upload. Container is 640px wide so you can see the crop dash lines going beyond on the right hand side
<img width="672" alt="Screenshot 2020-10-29 at 2 45 50 PM" src="https://user-images.githubusercontent.com/13146172/97548749-87259080-19f5-11eb-83e6-15faeea427f4.png">

Below is screenshot after cropping
<img width="448" alt="Screenshot 2020-10-29 at 2 46 52 PM" src="https://user-images.githubusercontent.com/13146172/97548801-9ad0f700-19f5-11eb-8afa-9427ec3026c5.png">

**Comment by abhijeet-qure** [comment]
@gopinav Check this thread out, might solve your problem - https://github.com/DominicTobias/react-image-crop/issues/373#issuecomment-651906751

**Comment by DominicTobias** [comment]
Hi you will need to crop an offscreen version of the image that is full
size as canvas just copies the pixels it sees. Or you can send the image
and crop params to the server and do the cropping and there

**Comment by gopinav** [comment]
Hello, made changes to use aspect ratio instead of absolute dimensions.
