### ISSUE TITLE
How to create new image file with cropped image

### ISSUE THREAD

**Issue by marco910** [DominicTobias/react-image-crop#392]
Hello,

currently, I'm working on an image manager application with React and want to integrate "react-image-crop" into it. My problem at the moment is, that I don't know how to create a new image file from the cropped image. How can I do that?

**Comment by DominicTobias** [comment]
Hi there is an example of doing this in the hook codesandbox - https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o
