### ISSUE TITLE
Crop `onImageLoaded` callback produces warning

### ISSUE THREAD

**Issue by j-meiring** [DominicTobias/react-image-crop#393]
Hi there

I get the following error when unmounting the component (in our case, a modal) that uses this package
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```
I've looked at [this issue](https://github.com/DominicTobias/react-image-crop/issues/283), and so my implementation of the component now looks like this:

`<ReactCrop src={tempImgSrc} onImageLoaded={img => onLoad(img)} crop={crop} onChange={c => setCrop(c)} onComplete={() => makeClientCrop()} />`

but I'm still getting this error. Could you perhaps suggest what else may be causing this issue? 

Thanks in advance!

**Comment by DominicTobias** [comment]
This means that after the component that uses ReactCrop unmounts, it's setting state. But this library doesn't have any state in it. I would recommend putting some console logs in the places where you're setting state and also one when the component unmounts maybe that will help to see what's happening

**Comment by j-meiring** [comment]
Thanks @DominicTobias, I found the offending set state in the function that I call on `onComplete`. Thanks for your guidance, it seems like the issue here is that the function I'm invoking on complete has to be `async` to get the blob, and my state was update when the promise is resolved.
