### ISSUE TITLE
Possibility for loading CSS via component level instead of import?

### ISSUE THREAD

**Issue by chaitanya-bendalam** [DominicTobias/react-image-crop#394]
Hi Team,

We are using the react-image-crop library in our development for a long back and we are trying to integrate the CSS into the component level. Is there any possibility of loading CSS via component level instead of import?. Please help me with this

**Comment by DominicTobias** [comment]
Hi do you mean a CSS-in-JS solution like Emotion or Styled Components? The only way to do that is to copy the CSS from the package, which is ok as I semantically version it and it hasn't changed for a long time. I'll think about doing it myself some day but not using any of the existing "full blown" solutions as they are many times bigger than the library itself.

**Comment by chaitu0609** [comment]
Hi @DominicTobias, Yes I am expecting the CSS -in-JS like Styled Component. Is there any way to copy the styles from the package and included into the Component?

**Comment by DominicTobias** [comment]
You would have to take the .scss convert to css (e.g. use codepen), and insert but ensure you are using the global option of the css-in-js library so that classnames aren't change (for example https://emotion.sh/docs/globals)

**Comment by DominicTobias** [comment]
Closing as I don't intend to add this for the library
