### ISSUE TITLE
Tainted canvas issue when pass image URL coming from back-end in the src props

### ISSUE THREAD

**Issue by pranaysharma995** [DominicTobias/react-image-crop#396]
Module works well when passed any local system image in the src, but when passed image URL as src then it throws an error of tainted canvas can't be exported.

**Comment by DominicTobias-b1** [comment]
This is a general problem with remote images and canvas you can read about it here - https://www.google.com/search?q=Tainted+canvas&oq=Tainted+canvas&aqs=chrome..69i57j0i457j0j46i175i199j0j69i61l3.302j0j7&sourceid=chrome&ie=UTF-8

I can't offer a solution or fix as it's something you have to work out with the origin or the image (the image HTTP response headers) and such, it's not something I can fix in the library
