### ISSUE TITLE
Make aspect ratio crop feature gone in the newest version?

### ISSUE THREAD

**Issue by supasus** [DominicTobias/react-image-crop#399]
Hi. I've been trying to get my pictures cropped to the maximum according to the aspect ratio on load. I found a nice example, but I've come to realize that this feature plainly doesn't work in the newest version, although it it's there in 6.0.4. I would have downgraded but I am looking for the circular crop option which is a newer feature. Am I missing something or is it gone for good? 

[Here's](https://codesandbox.io/s/yqmnr4k5yv) the demo I followed 

![S1QDKhM](https://user-images.githubusercontent.com/48766933/104073090-812e0600-5215-11eb-8182-311d2fd1d555.gif)
6.0.4 - works as intended, on upload the crop is stretched to the maximum
8.6.6 - on upload the crop is not defined and you have to do it by hand.

**Comment by DominicTobias** [comment]
Hi, that function signature has changed a bit it should be:

```js
onImageLoaded = image => {
    this.setState({
      crop: makeAspectCrop(
        {
          x: 10,
          y: 0,
          aspect: 4 / 3,
          height: 100,
        },
        image.width,
        image.height
      ),
    })
    return false;
  }
```

To fit and center a percentage crop if that's what you're trying to do check out the code in `onLoad` here - https://github.com/DominicTobias/react-image-crop/blob/master/README.md#how-can-i-center-the-crop
