### ISSUE TITLE
Crop lost when parent state changes

### ISSUE THREAD

**Issue by jereddanielson** [DominicTobias/react-image-crop#40]
I have a ReactCrop component inside of another component within my app, and without fail whenever I change the state of the parent component with setState(), the ReactCrop component seems to reset and lose its crop box. I am not changing any of the props or state related to the ReactCrop component, the state I am changing is completely unrelated. I've tried adding a unique key to the ReactCrop component and it has not helped. Any ideas why this might be?

**Comment by DominicTobias** [comment]
Hi, can you post your code? It sounds like something related to your parent code

**Comment by jereddanielson** [comment]
Sure. I even initialized a new project that's as simple as can be.

`import React, { Component } from 'react';
var myImage = require("../assets/praisethesun.png");

var ReactCrop = require("react-image-crop");
require("../../node_modules/react-image-crop/dist/ReactCrop.css");

export default class App extends Component {
	render() {
		return (
			<div className="container">
				<h1>Hello, World!</h1>
				<ReactCrop src={myImage} />
				<br />
				<button onClick={() => {this.setState({foo: Date.now()})}} >click me</button>
			</div>
		);
	}
}`

Clicking on the button resets any existing crop selection on the ReactCrop component even though the "foo" state is unconnected to it.

Here's a repo with my exact project test code: https://github.com/jereddanielson/crop-bug-demo

**Comment by DominicTobias** [comment]
Thanks I'm able to replicate it, pretty bad regression :o taking a look now

**Comment by DominicTobias** [comment]
Note: need to test something related to the build before I release this tomorrow
