### ISSUE TITLE
getCroppedImg function in the FAQ section loses resolution

### ISSUE THREAD

**Issue by ryshep111** [DominicTobias/react-image-crop#402]
See the screenshot below which was cropped from a very high res image and run through the example function:

![image (4)](https://user-images.githubusercontent.com/5770228/105366689-a0417600-5bcd-11eb-9384-7c1f0159f100.png)

We were able to modify the function like so to not lose quality (while limiting the final size of the image):

```
export const getBlobFromCroppedImage = (image, crop, maxHeight) => {
  const canvas = document.createElement('canvas');
  console.warn(image.naturalWidth, image.naturalHeight);
  const scaleX = image.naturalWidth / image.width;
  const scaleY = image.naturalHeight / image.height;
  const aspectRatio = crop.width/crop.height;

  let canvasHeight = crop.height * scaleY;
  let canvasWidth = crop.width * scaleX;

  if (maxHeight && (canvasHeight > maxHeight)) {
    canvasHeight = maxHeight;
    canvasWidth = Math.round(canvasHeight * aspectRatio);
  }

  canvas.height = canvasHeight;
  canvas.width = canvasWidth;

  const ctx = canvas.getContext('2d');

  ctx.drawImage(
    image,
    crop.x * scaleX,
    crop.y * scaleY,
    crop.width * scaleX,
    crop.height * scaleY,
    0,
    0,
    canvasWidth,
    canvasHeight,
  );

  return new Promise((resolve) => {
    canvas.toBlob((blob) => {
      resolve(blob);
    }, 'image/jpeg', 1);
  });
};
```

Could we consider updating the example, or make it clear that the current example doesn't work well for cases where the displayed image/crop is much smaller than the natural size of the image?

**Comment by DominicTobias** [comment]
Hi, can you explain what you're doing here? Where does maxHeight come from?

There is a more advanced example in the demo here: https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o?file=/src/App.js:1317-1351 because it also requires extra things like device pixel ratio and `imageSmoothingQuality` to look sharp on all screens

**Comment by ryshep111** [comment]
maxHeight was specific to our use case where we are trying to limit the size of the final image, but it's not important. The main point was that the example shown in the readme was causing a lot of resolution to be lost when cropping high resolution images. I think the main difference is the example had the canvas dimensions at crop.width and crop.height, whereas we scaled the canvas dimensions.

**Comment by ryshep111** [comment]
You should be able to replicate with a high res image (ours was roughly 10000 by 3000, and we took a 4:3 ratio crop)

**Comment by SkrewEverything** [comment]
@ryshep111  Some lines were missing in the FAQ code, which are present in the codesandbox. 

@DominicTobias Maybe you need to update the code snippet in the FAQ

These 5 lines must be added:
```
  const pixelRatio = window.devicePixelRatio;
  canvas.width = crop.width * pixelRatio;
  canvas.height = crop.height * pixelRatio;

  ctx.setTransform(pixelRatio, 0, 0, pixelRatio, 0, 0);
  ctx.imageSmoothingQuality = "high";
```

The full code in the FAQ must be:
```
/**
 * @param {HTMLImageElement} image - Image File Object
 * @param {Object} crop - crop Object
 * @param {String} fileName - Name of the returned file in Promise
 */
export function getCroppedImg(image, crop, fileName) {
  const canvas = document.createElement("canvas");
  const scaleX = image.naturalWidth / image.width;
  const scaleY = image.naturalHeight / image.height;
  canvas.width = crop.width;
  canvas.height = crop.height;
  const ctx = canvas.getContext("2d");

  // New lines to be added
  const pixelRatio = window.devicePixelRatio;
  canvas.width = crop.width * pixelRatio;
  canvas.height = crop.height * pixelRatio;
  ctx.setTransform(pixelRatio, 0, 0, pixelRatio, 0, 0);
  ctx.imageSmoothingQuality = "high";

  ctx.drawImage(
    image,
    crop.x * scaleX,
    crop.y * scaleY,
    crop.width * scaleX,
    crop.height * scaleY,
    0,
    0,
    crop.width,
    crop.height
  );

  // As Base64 string
  // const base64Image = canvas.toDataURL("image/jpeg");
  // return base64Image;

  // As a blob
  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (blob) => {
        blob.name = fileName;
        resolve(blob);
      },
      "image/jpeg",
      1
    );
  });
}
```

**Comment by DominicTobias** [comment]
Thanks @SkrewEverything will update it
