### ISSUE TITLE
Accessibility: Resize image via keyboard & descriptive text

### ISSUE THREAD

**Issue by bryce-pearce** [DominicTobias/react-image-crop#403]
First off, thank you for your awesome work on this package.

1.)  There is a minor issue regarding accessibility, when a user adds an image to crop, they are able to move the crop selection around via arrow keys, but are not able to resize the crop selection via the keyboard (requires mouse usage to resize crop size). 

2.) When a user tabs to the crop handle, after uploading an image, screen readers will read the word 'Blank' instead of a descriptive description like 'Crop handles use the arrow keys to resize the image'.

Thank you again for your work on this project.

**Comment by ccveer** [comment]
I am working on a fix for this here: https://github.com/sekoyo/react-image-crop/pull/467.  Would happily take feedback.

**Comment by DominicTobias** [comment]
This was implemented in v9
