### ISSUE TITLE
onChange callback being called infinitely.

### ISSUE THREAD

**Issue by WaqqarSuleman** [DominicTobias/react-image-crop#404]
Hi,

I am using React Image Crop inside a Formik component and the onChange Callback is being called infinitely. 

Here is my code:

```
const INITIAL_CROP = { unit: 'px', width: 320, aspect: 16 / 9 };

const SaveBanner = ({ show, handleClose, onSubmit, defaultValues }) => {
	const [crop, setCrop] = useState(INITIAL_CROP);
	const imgRef = useRef(null);
	const initialValues = { <some values> };
	const validationSchema = Yup.object({<some schema>});

	const onLoad = useCallback(img => {
		imgRef.current = img;
	}, []);

	return (
		<div className='SaveBanner'>
			<Modal show={show} onHide={handleClose} size='lg' scrollable>
				<Modal.Header closeButton>
					<Modal.Title>{!defaultValues ? 'Create' : 'Update'} Banner</Modal.Title>
				</Modal.Header>
				<Modal.Body>
					<Formik
						initialValues={defaultValues || initialValues}
						validationSchema={validationSchema}
						onSubmit={onSubmit}
					>
						{({ dirty, isSubmitting, values, setFieldValue }) => {
							return (
								<>
									<Form noValidate className='d-flex flex-column'>
										<div className='d-flex flex-row align-items-center'>
											<FormikControl
												control='text'
												name='name'
												label='Title'
												placeholder='Enter Banner Title'
												required={true}
												containerClassName='form-group col-md-6'
											/>

											<FormikControl
												control='file'
												name='image'
												label='Banner Image'
												required={true}
												containerClassName='form-group custom-file col-md-6 mt-2'
											/>
										</div>							

										<ReactCrop
											src={values.image && URL.createObjectURL(values.image)}
											onImageLoaded={onLoad}
											crop={crop}
											onChange={c => setCrop(c)}
										/>

										<div className='d-flex justify-content-end mt-3'>
											<Button
												variant='danger'
												className='mr-2'
												type='button'
												onClick={handleClose}
												disabled={isSubmitting}
											>
												Cancel
											</Button>
											<Button variant='primary' type='submit' disabled={!dirty || isSubmitting}>
												{!defaultValues ? 'Create' : 'Update'}
											</Button>
										</div>
									</Form>
								</>
							);
						}}
					</Formik>
				</Modal.Body>
			</Modal>
		</div>
	);
};

export default SaveBanner;
```

Can someone please tell me where the problem lies?
Thanks.

**Comment by przemyslawzalewski** [comment]
I think this is related to [changes to the event delegation since React 17](https://reactjs.org/blog/2020/10/20/react-v17.html#changes-to-event-delegation). The crop view worked fine for me until I updated to React 17.
From the source code, I see that the component binds to the document node to handle events outside of the crop view and this seems to cause the "sticky" issue, where after releasing the mouse button, the handlers still follow my mouse and the `onChange` is called indefinitely.
@WaqqarSuleman Could you confirm my guess?

**Comment by WaqqarSuleman** [comment]
> I think this is related to [changes to the event delegation since React 17](https://reactjs.org/blog/2020/10/20/react-v17.html#changes-to-event-delegation). The crop view worked fine for me until I upgraded to React 17.
> From the source code, I see that the component binds to the document node to handle events outside of the crop view and this seems to cause the "sticky" issue, where after releasing the mouse button, the handlers still follow my mouse and the `onChange` is called indefinitely.
> @WaqqarSuleman Could you confirm my guess?
> 
> Edit: I've reverted to 16.14.0 and the issue is gone. This seems to validate my initial assumptions.

I was working on React 17 only, may be that's why I faced that issue.

**Comment by przemyslawzalewski** [comment]
@WaqqarSuleman It seems that there was an issue with the component being placed within modals where they capture outside clicks and prevent the component from stopping listening for mouse/touch move events. I have introduced some fixes that work for our setup and submitted the PR https://github.com/DominicTobias/react-image-crop/pull/417. Could you see if the fork (https://www.npmjs.com/package/@sandstreamdev/react-image-crop) works for your use case? 

You can simply replace `react-image-crop` to `@sandstreamdev/react-image-crop` (and run `npm install`/`yarn`) and replace the imports with:

```diff
-import ReactImageCrop from 'react-image-crop';
-import 'react-image-crop/dist/ReactCrop.css';
+import ReactImageCrop from '@sandstreamdev/react-image-crop';
+import '@sandstreamdev/react-image-crop/dist/ReactCrop.css';
```

**Comment by DominicTobias-b1** [comment]
Thanks a lot @przemyslawzalewski I will publish this today
