### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation

### ISSUE THREAD

**Issue by Parth909** [DominicTobias/react-image-crop#405]
First of all , thanks for creating react-image-crop.
It is specially useful for people like me, who don't work with canvases .

I am getting this error whenever i test this functionality in mobile mode, like selecting some part or simply clicking of the canvas
```
Unable to preventDefault inside passive event listener invocation
```

![image](https://user-images.githubusercontent.com/59220026/107916558-77be5900-6f8c-11eb-9aa0-525d1f8536e8.png)

**Comment by Parth909** [comment]
Okay thanks

**Comment by dhwalin** [comment]
Do I need to downgrade react npm version as well for this? I am using react-image-crop in Capacitor Ionic App and it has all react 17 version. 

& with that, this error is appearing.

**Comment by DominicTobias** [comment]
> Do I need to downgrade react npm version as well for this? I am using react-image-crop in Capacitor Ionic App and it has all react 17 version.
> 
> & with that, this error is appearing.

Thanks for pointing that out, please use `8.6.11` instead

**Comment by DominicTobias** [comment]
> Do I need to downgrade react npm version as well for this? I am using react-image-crop in Capacitor Ionic App and it has all react 17 version.
> 
> & with that, this error is appearing.

Thanks I am looking into this will publish a fix @ 8.6.11

**Comment by dhwalin** [comment]
Is that sorted in this commit?

**Comment by DominicTobias** [comment]
> Is that sorted in this commit?

Yep please try 8.6.12

**Comment by dhwalin** [comment]
But with react 17 or lower? In 17 its still same. Here is my list of packages.

```
"react": "^17.0.2",
    "react-color": "^2.19.3",
    "react-dom": "^17.0.2",
    "react-image-crop": "^8.6.12",
    "react-konva": "^17.0.2-4",
```

**Comment by DominicTobias** [comment]
> But with react 17 or lower? In 17 its still same. Here is my list of packages.
> 
> ```
> "react": "^17.0.2",
>     "react-color": "^2.19.3",
>     "react-dom": "^17.0.2",
>     "react-image-crop": "^8.6.12",
>     "react-konva": "^17.0.2-4",
> ```

Hm that's strange, are you able to repro the issue here? https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o

I was able to repro on 8.6.10 because I removed something with passive events that I shouldn't have, but I added it back and the warning went away for me

**Comment by dhwalin** [comment]
Ok let me check. Thanks for your help.

**Comment by dhwalin** [comment]
8.6.9 is same. 

1. I am changing the version
2. run npm install command
3. npx cap sync android

& done. Then I am checking.

I hope I am not missing anything.

**Comment by dhwalin** [comment]
Could not find a declaration file for module 'react-image-crop'. '/Volumes/MAIN/BJPFrames/PF2.0/PoliticalFrames/node_modules/react-image-crop/dist/ReactCrop.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-image-crop` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-image-crop';`ts(7016)

After updates to react 17, this warning is showing here:

```
import ReactCrop from 'react-image-crop';
```

**Comment by DominicTobias** [comment]
> Could not find a declaration file for module 'react-image-crop'. '/Volumes/MAIN/BJPFrames/PF2.0/PoliticalFrames/node_modules/react-image-crop/dist/ReactCrop.min.js' implicitly has an 'any' type.
> Try `npm i --save-dev @types/react-image-crop` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-image-crop';`ts(7016)
> 
> After updates to react 17, this warning is showing here:
> 
> ```
> import ReactCrop from 'react-image-crop';
> ```

Did you try as the message prompts `npm i --save-dev @types/react-image-crop`? As with the passive warning I'm not sure why that's coming up for you as it should only be a problem in 8.6.10 🤔

**Comment by dhwalin** [comment]
Yes I have run that command. Now failed to compile.

![image](https://user-images.githubusercontent.com/10140916/122222682-1b366080-ced0-11eb-94da-6d72635de238.png)

![image](https://user-images.githubusercontent.com/10140916/122222763-3012f400-ced0-11eb-9287-eb005211d8f4.png)

**Comment by dhwalin** [comment]
Hello, its started working without doing anything. Seriously. I turned off computer and after few hours I started to check and it was miracle. Thank you for your update.

**Comment by DominicTobias** [comment]
> Hello, its started working without doing anything. Seriously. I turned off computer and after few hours I started to check and it was miracle. Thank you for your update.

Hah ok that's good as I was out of ideas ;)
