### ISSUE TITLE
Crop Selection Tool Goes Beyond the Image

### ISSUE THREAD

**Issue by WaqqarSuleman** [DominicTobias/react-image-crop#407]
Hi,

I have an issue where the crop selection tools goes beyond the image. In the `initialState` of my crop, I have set the width to `320` and aspect ratio to 16/9. Following is the isse:
![cropper issue](https://user-images.githubusercontent.com/74898820/109498841-0a491700-7aba-11eb-921f-05703eab12fe.png)

The width of the image under test in **200px** and as you can see the crop selection tool goes beyond the image.
Is there any way to fix this?
Thanks.

**Comment by mudassirmmt** [comment]
@WaqqarSuleman 
it was just a css issue that you are facing. please disable or remove display flex from your div element.

**Comment by WaqqarSuleman** [comment]
@mudassirmmt Thanks a lot!
