### ISSUE TITLE
Couldn't get the circular shaped cropped output image when passing 'circularCrop' props TRUE

### ISSUE THREAD

**Issue by AndiswamyDev** [DominicTobias/react-image-crop#409]
Hi,
I'm using our REACT IMAGE CROP package and trying a thing like to crop the image into circular shape.

What I did is, as per our documentation, the cropper can be converted into CIRCLE shape when passing circularCrop props as true. Like below,
`<ReactCrop
            src={src}
            keepSelection={true}
            circularCrop={true}
            crop={crop}
            ruleOfThirds={true}
            onImageLoaded={this.onImageLoaded}
            onComplete={this.onCropComplete}
            onChange={this.onCropChange}
          />`

Successfully I can get the cropper as circular shape, but the output of that cropper images is not in circular, instead its still in square/rectangle.

Is there any way to get the circle cropped image from it ?

Please find below screen grab mates,
![Screenshot from 2021-03-09 20-26-10](https://user-images.githubusercontent.com/62993721/110490008-e159ff00-8115-11eb-97c8-8fbbcbfc4b7e.png)

CC: @DominicTobias , @DPr00f , @littleiffel , @PetrochukM , @DominicTobias-b1 , @arendjr, @virgofx

**Comment by jmj90** [comment]
Having the same issue.

**Comment by DominicTobias** [comment]
The image preview is a pretty simple example and part of the demo not the
library. I’ve never done circular canvas images but if you google you can
find examples.

However I wouldn’t personally do them - a circle border is a stylistic
thing I would apply with CSS rather than “bake” into the image (which would
also be black for a JPG since it doesn’t support transparency). Later on
your designers might decide to have square images for example which would
just be a CSS change

**Comment by jmj90** [comment]
Yep that's what I ended up doing. 

I cropped the image with a 4/4 ratio and added a border radius to make it circular since I don't need to download the image at all, just display it.

Thanks!

**Comment by AndiswamyDev** [comment]
Then, @DominicTobias Do you think to have it in further releases if we find some solutions to crop it into circular canvas or to mask like circular white mask thereby can make it into circle?

**Comment by jmj90** [comment]
@AndiswamyDev do you need the circular image to be downloaded or just displayed? I can provide you with my css solution if that'd help, then add that class to any image you want displayed as a circle. Like Dominic was saying, it makes more sense to apply the circular styling than bake it into the image. If you view the image source behind any popular social media (twitter, ig, twitch) their profile images are squares displayed with a class to make them circular. 

my example: ![image](https://user-images.githubusercontent.com/31748121/111325079-57d88e80-8639-11eb-8a4c-5e36ae26d0ce.jpeg)

**Comment by AndiswamyDev** [comment]
Thanks @jmj90 , Actually my requirement is like uploading the cropped images that may be square/circle tinto S3, and using that url. So applying css into the preview cropped image won't work as they cant bundled to upload into s3.

**Comment by DominicTobias-b1** [comment]
@AndiswamyDev In that case have a look at Google there are many examples as I don't intend to add it to the library: https://www.google.com/search?q=canvas+circle+image&oq=canvas+circle+image&aqs=chrome.0.0j0i22i30l2j0i10i22i30.6221j0j7&sourceid=chrome&ie=UTF-8

e.g.
https://stackoverflow.com/questions/7166471/how-to-draw-only-a-circular-part-of-an-image-with-html-5-canvas
https://stackoverflow.com/questions/4276048/html5-canvas-fill-circle-with-image/6889378

**Comment by AndiswamyDev** [comment]
Yeah @DominicTobias-b1 , That's what I tried and formed a circular clip, my friend. Thanks much for all your hands. 
And Can i close this Issue?

**Comment by DominicTobias-b1** [comment]
Cool, sure thanks 😉

On Wed, 17 Mar 2021 at 15:06, Andiswamy Rajagopal ***@***.***>
wrote:

> ------------------------------
> *[External Email: Use caution with links and attachments]*
> ------------------------------
>
> Yeah @DominicTobias-b1
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DominicTobias-2Db1&d=DwMCaQ&c=sSVGO1PAPMGyxGLZsRfH-A&r=81xxP-d5LtxAiZTPPBF-agkqmFiZwGE6R06efZglang&m=i7Vt_QdjtT4JWlj3JuuJdWJAPG9CqlN-Yaot3iH0Aq0&s=wp75rCD9AHl3aOafpLFZOBJl4Nx2sLYDF6XEawFLSvE&e=>
> , That's what I tried and formed a circular clip, my friend. Thanks much
> for all your hands.
> And Can i close this Issue?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DominicTobias_react-2Dimage-2Dcrop_issues_409-23issuecomment-2D800850201&d=DwMCaQ&c=sSVGO1PAPMGyxGLZsRfH-A&r=81xxP-d5LtxAiZTPPBF-agkqmFiZwGE6R06efZglang&m=i7Vt_QdjtT4JWlj3JuuJdWJAPG9CqlN-Yaot3iH0Aq0&s=r6IByJYUEdQRO38z5Rl4KeHC_LCP3PhrU8z1cIz644k&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AN7W7SLSLTWNMDSAPYIGLKTTEBIH3ANCNFSM4Y3ZGWYQ&d=DwMCaQ&c=sSVGO1PAPMGyxGLZsRfH-A&r=81xxP-d5LtxAiZTPPBF-agkqmFiZwGE6R06efZglang&m=i7Vt_QdjtT4JWlj3JuuJdWJAPG9CqlN-Yaot3iH0Aq0&s=Cu5ncFWySK77ujkNNPhSoH5txGSV1nsQwshJpHyLuUA&e=>
> .
>
-- 

*Dominic Tobias*
*Engineer, UI, Exchange Engineering*
Email: ***@***.***
Direct:
Address:  Level 26, The Centrium, No. 60 Wyndham Street, Central, Hong Kong
Website: block.one <https://www.block.one>


*The information contained in this email is confidential together with any
information contained in any attachments to this email. You should not
disclose, give or copy the information to anyone other than the person(s)
who are named or referenced above. The law may also protect the information
as a legally privileged document and/or as a copyright work. If you have
received this email and you are not the person named or referenced above,
please let the sender know and delete the email from your computer (and, if
applicable, your computer system(s) and server(s)). For information about
how we process personal data and monitor communications please see our
privacy policy <https://block.one/privacy-policy/> and for terms of use
please see our terms of use here. <https://block.one/terms-of-use/>*

**Comment by AndiswamyDev** [comment]
Hi @DominicTobias , @DominicTobias-b1 , Hope you do well and safe.
Just a head sup mate, I got a way to crop an image as a perfect ready made canvas draw image circle.

So the workflow is like whenever we pass circularCrop: true, then the cropper will become circle as always, and the enhancement we can do is like making the end resultant of an image into as circle(not as a square when cropper is circle selected).

Need your thoughts on this enhancement workflow Dominic, If that's an awesome feature to go, Please let me know I will create a PR mate.

Thanks & Regards,
Andiswamy Rajagopal

**Comment by mvivonetto** [comment]
@AndiswamyDev I would be interested and seeing how you made it work.  Im getting close but the circular cropped portion doesn't always scale properly.  Would you mind posting your solution on how you made it work?  Thanks in advance!!!

Ps.  @DominicTobias, @DominicTobias-b1, I think this would be a great addition to the library and almost necessary since the crop area can be shaped as a circle...Otherwise whats the point of circularCrop option when the result crops as a square?

**Comment by DominicTobias** [comment]
> @AndiswamyDev I would be interested and seeing how you made it work. Im getting close but the circular cropped portion doesn't always scale properly. Would you mind posting your solution on how you made it work? Thanks in advance!!!
> 
> Ps. @DominicTobias, @DominicTobias-b1, I think this would be a great addition to the library and almost necessary since the crop area can be shaped as a circle...Otherwise whats the point of circularCrop option when the result crops as a square?

@mvivonetto please see my answer above:

> The image preview is a pretty simple example and part > of the demo not the
> library. I’ve never done circular canvas images but if > you google you can
> find examples.
> 
> However I wouldn’t personally do them - a circle border > is a stylistic
> thing I would apply with CSS rather than “bake” into > the image (which would
> also be black for a JPG since it doesn’t support > transparency). Later on
> your designers might decide to have square images for > example which would
> just be a CSS change

**Comment by AndiswamyDev** [comment]
Yes , If @DominicTobias is ok to go, we can add some PR on this, else as he said you might go with some additional css to make them circle :( @mvivonetto

**Comment by AndiswamyDev** [comment]
And my personal view is, as like square , we can do for circle too, without any additional css. That would help a lot of developers who adopts for this cropper plugin and they will feel more handy and wise to use then :)
