### ISSUE TITLE
How to remove dash line?

### ISSUE THREAD

**Issue by mcntai** [DominicTobias/react-image-crop#411]
I'm using circular model of the crop element because profile avatars in my app are also circles. Is there a way to remove the dash line and just keep the circle zone?

Example: http://joxi.ru/gmvxJbzH1g9KvA

I want to remove somehow the square from dash line and just keep circle. Is this possible?

**Comment by DominicTobias** [comment]
You can disable it with CSS, set `border-image-source` to none
