### ISSUE TITLE
Works in mobile browsers but throw an error in the console. 

### ISSUE THREAD

**Issue by mjza** [DominicTobias/react-image-crop#413]
When I use it with latest version of react and only in mobile browsers like chrome, it shows the following error in the console. 

> Unable to preventDefault inside passive event listener invocation.
> preventDefault @ react-dom.development.js:6202
> (anonymous) @ ReactCrop.min.js:formatted:1
> callCallback @ react-dom.development.js:3945
> invokeGuardedCallbackDev @ react-dom.development.js:3994
> invokeGuardedCallback @ react-dom.development.js:4056
> invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
> executeDispatch @ react-dom.development.js:8243
> processDispatchQueueItemsInOrder @ react-dom.development.js:8275
> processDispatchQueue @ react-dom.development.js:8288
> dispatchEventsForPlugins @ react-dom.development.js:8299
> (anonymous) @ react-dom.development.js:8508
> batchedEventUpdates$1 @ react-dom.development.js:22396
> batchedEventUpdates @ react-dom.development.js:3745
> dispatchEventForPluginEventSystem @ react-dom.development.js:8507
> attemptToDispatchEvent @ react-dom.development.js:6005
> dispatchEvent @ react-dom.development.js:5924
> unstable_runWithPriority @ scheduler.development.js:468
> runWithPriority$1 @ react-dom.development.js:11276
> discreteUpdates$1 @ react-dom.development.js:22413
> discreteUpdates @ react-dom.development.js:3756
> dispatchDiscreteEvent @ react-dom.development.js:5889

**Comment by mjza** [comment]
It seems it has problem with the new release of react, I updated your sandbox to use react 17.0.2 and when I open the https://g0zsx.csb.app/ URL in my mobile chrome can see the error 

https://codesandbox.io/s/react-image-crop-demo-with-classes-forked-g0zsx?file=/package.json

**Comment by mjza** [comment]
The problem is on this function in minified version line 444, `t.preventDefault();` will cause the error:

```
function a() {
                    var e;
                    d(this, a);
                    for (var t = arguments.length, r = new Array(t), n = 0; n < t; n++)
                        r[n] = arguments[n];
                    return g(l(e = i.call.apply(i, [this].concat(r))), "window", "undefined" != typeof window ? window : {}),
                    g(l(e), "document", "undefined" != typeof document ? document : {}),
                    g(l(e), "state", {}),
                    g(l(e), "keysDown", new Set),
                    g(l(e), "onCropMouseTouchDown", (function(t) {
                        var r = e.props
                          , n = r.crop
                          , o = r.disabled
                          , i = e.mediaDimensions
                          , a = _(n, i.width, i.height);
                        if (!o) {
                            t.preventDefault();
                            var c = O(t);
                            e.componentRef.setActive ? e.componentRef.setActive({
                                preventScroll: !0
                            }) : e.componentRef.focus({
                                preventScroll: !0
                            });
                            var s, d = t.target.dataset.ord, u = "nw" === d || "w" === d || "sw" === d, p = "nw" === d || "n" === d || "ne" === d;
                            a.aspect && (s = e.getElementOffset(e.cropSelectRef)),
                            e.evData = {
                                clientStartX: c.x,
                                clientStartY: c.y,
                                cropStartWidth: a.width,
                                cropStartHeight: a.height,
                                cropStartX: u ? a.x + a.width : a.x,
                                cropStartY: p ? a.y + a.height : a.y,
                                xInversed: u,
                                yInversed: p,
                                xCrossOver: u,
                                yCrossOver: p,
                                startXCrossOver: u,
                                startYCrossOver: p,
                                isResize: t.target.dataset.ord,
                                ord: d,
                                cropOffset: s
                            },
                            e.mouseDownOnCrop = !0,
                            e.setState({
                                cropIsActive: !0
                            })
                        }
                    }
```

**Comment by DominicTobias** [comment]
Please try 8.6.7

**Comment by Wamboot** [comment]
Can confirm it still does the same. 
As seen on this website : [https://www.uriports.com/blog/easy-fix-for-intervention-ignored-attempt-to-cancel-a-touchmove-event-with-cancelable-false/](url)
Replacing `e.preventDefault();`
for `if (e.cancelable) e.preventDefault()`
Does fix it.

**Comment by DominicTobias** [comment]
Publish in 8.6.9

**Comment by mjza** [comment]
I confirm it works.
