### ISSUE TITLE
v8.6.7 does not include `lib` folder.

### ISSUE THREAD

**Issue by dardanos** [DominicTobias/react-image-crop#418]
I just updated to `v8.6.7` and found that the scss imports fails.
```js
import 'react-image-crop/lib/ReactCrop.scss';
```

Looking at the folder in `node_modules` I don't see the `lib` folder.

![image](https://user-images.githubusercontent.com/52110045/115970860-49707300-a513-11eb-9119-7fd995857074.png)

**Comment by DominicTobias** [comment]
Thanks for pointing that out, please try `8.6.8`

**Comment by dardanos** [comment]
Thanks @DominicTobias
