### ISSUE TITLE
最新发版打包有问题

### ISSUE THREAD

**Issue by wendaoshuai66** [DominicTobias/react-image-crop#420]
![image](https://user-images.githubusercontent.com/31531781/116498258-ea787880-a8db-11eb-9e8a-5fa17eba82a1.png)

如图 打包包含了 es6 箭头函数导致最近的项目ie 浏览器有问题

**Comment by DominicTobias-b1** [comment]
Hi what browser are you using? I updated the browserlist quite recently to `"browserslist": "last 3 versions, not IE > 0",`, all modern browsers have supported arrow functions for a long time now. I know that in China some very outdated browsers are still used sometimes.

**Comment by wendaoshuai66** [comment]
The reason why we are compatible with IE is because Japanese customers use IE more, so it must be compatible, and our headless browser is not compatible with this syntax.

**Comment by DominicTobias-b1** [comment]
I'm afraid this library doesn't maintain compatibility with IE, the last version which may have been compatible is `8.6.4`

**Comment by wendaoshuai66** [comment]
OK， thanks
