### ISSUE TITLE
v8.6.10 broke our build, rolling back to 8.6.9 resolved issue

### ISSUE THREAD

**Issue by stee-ren** [DominicTobias/react-image-crop#429]
I didn't yet look into what exactly is wrong with recent changes, but locally on windows it caused no issues, but on our Linux based CI build, the recent changes (8.6.10) caused the following error:

`
ERROR in ./node_modules/react-image-crop/lib/ReactCrop.scss
20:57:47
  Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
20:57:47
  ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
20:57:47
  SassError: Invalid CSS after "...le-height: math": expected expression (e.g. 1px, bold), was ".div($drag-handle-h"
20:57:47
          on line 21 of node_modules/react-image-crop/lib/ReactCrop.scss
20:57:47
  >> $half-drag-handle-height: math.div($drag-handle-height, 2);
20:57:47
  
20:57:47
     ------------------------------^
20:57:47
  
20:57:47
      at C:\BuildAgent\work\b859c7b6b98da306\node_modules\webpack\lib\NormalModule.js:316:20
20:57:47
      at C:\BuildAgent\work\b859c7b6b98da306\node_modules\loader-runner\lib\LoaderRunner.js:367:11
20:57:47
      at C:\BuildAgent\work\b859c7b6b98da306\node_modules\loader-runner\lib\LoaderRunner.js:233:18
20:57:47
      at context.callback (C:\BuildAgent\work\b859c7b6b98da306\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
20:57:47
      at Object.callback (C:\BuildAgent\work\b859c7b6b98da306\node_modules\sass-loader\dist\index.js:62:7)
20:57:47
      at Object.done [as callback] (C:\BuildAgent\work\b859c7b6b98da306\node_modules\neo-async\async.js:8069:18)
20:57:47
      at options.error (C:\BuildAgent\work\b859c7b6b98da306\node_modules\node-sass\lib\index.js:293:32)
20:57:47
   @ ./src/modules/common/components/file-upload-dialog/image-cropper/image-cropper.tsx 11:0-45
20:57:47
   @ ./src/modules/common/components/file-upload-dialog/file-upload-dialog.tsx
20:57:47
   @ ./src/modules/settings/profile-settings/components/profile-avatar/profile-avatar.tsx
20:57:47
   @ ./src/modules/settings/profile-settings/components/profile-settings-list/profile-settings-list.tsx
20:57:47
   @ ./src/modules/settings/profile-settings/profile-settings.tsx
20:57:47
   @ ./src/modules/settings/settings.tsx
20:57:47
   @ ./src/router/routes.tsx
20:57:47
   @ ./src/app.tsx
20:57:47
   @ ./src/index.tsx
20:57:47
   @ multi ./src/index
`

**Comment by DominicTobias-b1** [comment]
Ah damn should have realised this is a breaking change - what package are you using to compile sass? This is compatible with the non-deprecated https://www.npmjs.com/package/sass instead of `node-sass` or `dart-sass` which are now deprecated

**Comment by stee-ren** [comment]
We're unfortunately using node-sass, which I guess is the issue. Its a good hint, we should plan to move away from node-sass but we're in end-game and I'm not sure of the impact of switching right now. We will look into this.

**Comment by DominicTobias-b1** [comment]
@stee-ren understood, I can't unpublish the package anymore and concerned deprecating that version will cause other issues (haven't done a deprecation before)

Updating to `sass` may have no impact but hard to say. Alternatively you can pin the version as you've done, or if you're not changing any SCSS variables for the lib then you can import `ReactCrop.css` instead and use `8.6.10`

**Comment by stee-ren** [comment]
Thanks for the tip. I think it makes sense to at least trying to abandon node-sass first and go from there.

**Comment by mjza** [comment]
I have the same problem:

> ./node_modules/react-image-crop/lib/ReactCrop.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./node_modules/react-image-crop/lib/ReactCrop.scss)
> SassError: Invalid CSS after "...le-height: math": expected expression (e.g. 1px, bold), was ".div($drag-handle-h"
>         on line 21 of node_modules/react-image-crop/lib/ReactCrop.scss
> >> $half-drag-handle-height: math.div($drag-handle-height, 2);

I cannot leave the sass

**Comment by stee-ren** [comment]
Like Tobias already pointed out, you can always fix it to 8.6.9 in your package.json

`"react-image-crop": "8.6.9",`

Notice the ^ or ~ are missing (important)

**Comment by asharafshahi** [comment]
I just installed version 10.0.1 and I'm getting the same error.  I don't even see a css version of styles in node_modules for this lib.  Is the only option to revert back and pin to 8.6.9?  Any other options?

**Comment by eiglow** [comment]
I'm also encountering this issue on version `10.0.4`. We don't use `node-sass` or `dart-sass`.

Is there a required `sass` version, or something else?

I think this situation might have been avoided with use of dependencies, since this package clearly depends on specific other packages. "No dependencies" seems like a bit of a lie?

**Comment by DominicTobias** [comment]
> I'm also encountering this issue on version `10.0.4`. We don't use `node-sass` or `dart-sass`.
> 
> Is there a required `sass` version, or something else? We have `sass` `1.49.9` and `sass-loader` `10.1.1`. Falling back to the `.css` file works for us though.

You don't need to import the .scss file unless you have some reason to like override scss variables (but you can still override things in css instead). The version used is `1.52.2` though it doesn't use many features and I'd expect any v1 should work
