### ISSUE TITLE
node-sass not support @use rule, build failed

### ISSUE THREAD

**Issue by shifengdiy** [DominicTobias/react-image-crop#430]
reactCrop.scss build error in line 21, 22; node-sass has not supported @use rule; this is answer in stackoverflow [https://stackoverflow.com/questions/62332967/sass-module-error-when-trying-to-use-use-rule#](url)
react-image-crop version: 8.6.10
node-sass version: 4.14.1

**Comment by DominicTobias-b1** [comment]
Hi please check this thread - https://github.com/DominicTobias/react-image-crop/issues/429

I should have made 8.6.10 a breaking change but too late, you can pin your version to 8.6.9 or one of the other solutions mentioned there

**Comment by shifengdiy** [comment]
i saw version 8.6.9 not use @use rule,it's should be work;thanks
