### ISSUE TITLE
run script build failed  - UglifyJs

### ISSUE THREAD

**Issue by nehal-karanjekar** [DominicTobias/react-image-crop#433]
The library is working properly in development but when am trying to create build it is getting failed with following error

static/js/main.5310c3fe.js from UglifyJs
SyntaxError: Unexpected token: punc ()) [./~/react-image-crop/dist/ReactCrop.min.js:1,263]

i am using "react-image-crop": "^8.6.6"

**Comment by DominicTobias** [comment]
Uglify has been deprecated for a long time and doesn’t support ES6+ syntax well, it’s probably choking on some. You should be using Terser but more importantly you shouldn’t be running minification or probably anything else on files inside node_modules (and the file is already minified)

**Comment by nehal-karanjekar** [comment]
I am running this commond only "npm run-script build"

**Comment by DominicTobias** [comment]
On which package? You don’t need to run the build command manually when installing the package as an NPM module

**Comment by nehal-karanjekar** [comment]
> On which package? You don’t need to run the build command manually when installing the package as an NPM module

on dev environment it is working. but when I try to create a build it gives uglify error

**Comment by hzburki** [comment]
I have the same issue in a 3-year-old CRA project. It had already been ejected so I could access the `webpack.config.prod` file where you need to replace the deprecated `uglifyjs` package with `terser` package.

I am listing the steps I took below;

1. Install `"terser-webpack-plugin-legacy": "^1.2.5"` package.
2. Import `const TerserPlugin = require('terser-webpack-plugin-legacy');` into the `webpack.config.prod` file. 
3. Comment the code for `webpack.optimize.UglifyJsPlugin` object.
4. Place `new TerserPlugin(),` right below the commented code.
5. Build the app as normal and it works 🎆

**Comment by DominicTobias** [comment]
It sounds as though you are running webpack on node_modules which is generally not a good idea, it should work ok if you exclude your rules from running on node_modules e.g

```js
{
  test: /\.tsx?$/,
  exclude: /node_modules/,
  use: 'ts-loader',
}
```
