### ISSUE TITLE
How should the minWidth for the crop tool work?

### ISSUE THREAD

**Issue by philmetzger** [DominicTobias/react-image-crop#441]
I have set a minWidth for the crop attribute. But then when I drag the cropper tool to make the width smaller, it shrinks to clearly below the minWidth I set.
Have a look here: https://codesandbox.io/s/react-image-crop-demo-with-classes-forked-qdebp
I have set a mins and maxs for the cropper yet it does not listen to those values and can still be any size.
Is there something I am missing?

**Comment by monossido** [comment]
reading old issue the minWidth and minHeigth are not props of crop, but should be props of ReactCrop itself

**Comment by philmetzger** [comment]
Ah yes true! i have been doing this wrong the whole time. thanks!
