### ISSUE TITLE
Download cropped images without showing the canvas. is it possible?

### ISSUE THREAD

**Issue by amerfathullah** [DominicTobias/react-image-crop#445]
as far as I know, the downloaded cropped images are taken from the canvas. is it possible to download cropped images without showing the canvas preview? if I try to hide the canvas, images cannot be download

**Comment by DominicTobias** [comment]
How are you hiding the canvas? It should be possible by rendering it offscreen for example

**Comment by amerfathullah** [comment]
Hi @DominicTobias , actually, I have successfully hide the canvas using style={display: none}. but now I got another problem. The downloaded cropped image size is bigger than the original image. probably about image scaling I guess but I'm not sure where is the problem. Can you help me on this?

**Comment by DominicTobias** [comment]
I couldn't say without seeing code, my first guess is that your image is being sized down, but the scale factor is taking the dimensions from the "natural" image size:

```js
const scaleX = image.naturalWidth / image.width;
const scaleY = image.naturalHeight / image.height;
```

**Comment by DominicTobias** [comment]
What does your code look like? I recommend taking it from here rather than the README: https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o?file=/src/App.js

**Comment by amerfathullah** [comment]
ah yes, I take it from that link, only modify some of it, but I didn't change anything in the canvas part

**Comment by amerfathullah** [comment]
Solved it by initializing pixelRatio to a lower value (0.5)
