### ISSUE TITLE
How can set originial crop after selecting an another image

### ISSUE THREAD

**Issue by thongle12** [DominicTobias/react-image-crop#448]
Hello everyone. I am new here, and I need a guide on this issue. 

My question is: **I want the crop area should be reset if I choose another image.** 

Please help me. **Thanks a bunch in advance.**

**Comment by thongle12** [comment]
![image](https://user-images.githubusercontent.com/86275790/134898609-cb4f3203-a419-4cf9-b526-3af6b93d5c0b.png)

If I drag like this. I want the next image I chosen, will have the original crop area ( Not the same like this)

**Comment by DominicTobias** [comment]
Since the crop is controlled by you, you just need to change it back when a new image is loaded.

```js
const defaultCrop = { ... }

function handleImageLoaded() {
  setCrop(defaultCrop)
}

<ReactCrop crop={crop} onImageLoaded={handleImageLoaded} />

```
