### ISSUE TITLE
Drawing new crop with spin prop 90deg has wrong coords

### ISSUE THREAD

**Issue by DominicTobias** [DominicTobias/react-image-crop#449]
@Tenpi any ideas what is going on here 🤔? If I initialize with a crop it works fine:

```js
const [crop, setCrop] = useState({ unit: '%', width: 30, aspect: 16 / 9 });
```

However drawing a new crop has the wrong coords:

https://codesandbox.io/s/react-image-crop-demo-using-spin-and-rotate-c6dsd?file=/src/App.js:733-811

**Comment by Tenpi** [comment]
It looks like you need to factor in the `spin` prop into the code that draws a new crop. I usually initialize the crop to the image width/height and use `keepSelection={true}`, so I never caught that sorry.

You could probably copy over this logic to correct the `crop.x` and `crop.y` coordinates. 

```ts
let degrees = spin;
let radians = Math.abs((degrees * Math.PI) / 180.0);
if ((degrees > -45 && degrees <= 45) || (Math.abs(degrees) > 135 && Math.abs(degrees) <= 180)) {
  // Top and Bottom
  crop.x = crop.x * Math.cos(radians);
  crop.y = crop.y * Math.cos(radians);
} else if (degrees > 45 && degrees <= 135) {
  // Left
  crop.x = crop.y * Math.sin(radians);
  crop.y = crop.x * Math.sin(radians) * -1;
} else if (degrees > -135 && degrees <= -45) {
  // Right
  crop.x = crop.y * Math.sin(radians) * -1;
  crop.y = crop.x * Math.sin(radians);
}
```

Might also need to factor in `zoom` prop as well. Not tested, but it should be either one of these. It should be put before the above.

```ts
crop.x = crop.x / zoom; // or crop.width / zoom, I am not sure.
crop.y = crop.y / zoom; // or crop.height / zoom, I am not sure.
```

**Comment by DominicTobias** [comment]
Thanks for the tips I’ll take a look 👍

**Comment by 3vilguy** [comment]
Hello there! I just ended up here because I had similar issue with `rotate`. Is it something likely to be fixed? Or does it have super low priority?

**Comment by DominicTobias** [comment]
Closing as no longer supported in v10 as it was too complex for me to maintain/fix ^ Sorry! v9 still has the same features as v10 so you can continue using that if it was working ok for your use case

**Comment by 3vilguy** [comment]
Hi, thanks for the update. No problem at all, thanks for all the hard work and all the best with v10 :)

**Comment by Tenpi** [comment]
I am still using the said removed props, so I will just use and maintain my own fork of this project if you don't want to support those features. Though I understand why you don't want to maintain them as they added a fair amount of complexity, it's not a problem though really.
