### ISSUE TITLE
Width does not go up to 100% when using aspect ratio

### ISSUE THREAD

**Issue by johneriksson** [DominicTobias/react-image-crop#45]
This is not a huge problem in my case, but it's bugging me =)

When an aspect ratio is set (for example 16/9), the width will not go up to 100% when you maximize the crop area. Instead I get values like 99.999999999... I'm guessing the height has a higher priority in the aspect-ratio-check or something?

**Comment by DominicTobias** [comment]
This is probably a browser rounding issue - the nice thing about percentages is that they're responsive, but unfortunately the browser sometimes doesn't perfectly do it. Anyway I'll check to verify but I have a feeling there's nothing that can be done (except maybe rounding up if it looks like it should be doing it)

**Comment by johneriksson** [comment]
Yeah, I was using Chrome earlier but I just tested in Safari and it rounds to 100.
