### ISSUE TITLE
Download fails when i pass image src in ReactCrop

### ISSUE THREAD

**Issue by prakash2091** [DominicTobias/react-image-crop#450]
I am facing issue when I have passed image URL in src attributes of <ReactCrop> component. i am able to crop the image . but its failing when i click on downlad.

is it due to CORS ? do we have any fix for it?

i have tried with crossorigin={null} . still it did not help
Steps:
https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o?file=/src/App.js:2211-2220

pls pass url of the image in src and try crop first. then download

"Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported"

**Comment by DominicTobias** [comment]
Hi did you see the note above the download button? "Note that the download below won't work in this sandbox due to the iframe missing 'allow-downloads'. It's just for your reference."? I can't remember if tainted canvas is the same problem but try it outside an iframe (i.e. outside of Codesandbox)

**Comment by DominicTobias** [comment]
Closing as this is a general security issue with HTML canvas element and not related to the lib - if you encounter this issue I recommend you google as there are a number of discussions on the topic
