### ISSUE TITLE
Resize width drifting

### ISSUE THREAD

**Issue by AlexxIV** [DominicTobias/react-image-crop#452]
Hello,

First of all I want to say huge thanks for this library. It perfectly suits our needs because it's super flexible and easy to use.

In our use case we don't specify the aspect ratio of the crop. The user can change the width or the height of the crop area freely. I'm not sure If I can describe the bug (we are not sure if it's a bug or it is meant to work this way) with words so I will attach a video which is self explanatory.

https://user-images.githubusercontent.com/19311875/140638295-afc3777c-eee9-4ca8-92fb-3eb46b110a68.mp4

[If you also think this is a bug, I have an open pull request to address this issue.](https://github.com/DominicTobias/react-image-crop/pull/453)

**Comment by DominicTobias** [comment]
Fixed in 9.0.5, thanks for the PR
