### ISSUE TITLE
Image crop out of bounds on load

### ISSUE THREAD

**Issue by supasus** [DominicTobias/react-image-crop#455]
Hello. I am trying to get my image cropped immediately on load within set aspect road. however when using the code below, from the documentation here, my crop ends up being incorrect.
```
  const onLoad = useCallback(img => {
    imgRef.current = img;
  
    const aspect = 16 / 9;
    const width = img.width / aspect < img.height * aspect ? 100 : ((img.height * aspect) / img.width) * 100;
    const height = img.width / aspect > img.height * aspect ? 100 : (img.width / aspect / img.height) * 100;
    const y = (100 - height) / 2;
    const x = (100 - width) / 2;
  
    setCrop({
      unit: '%',
      width,
      height,
      x,
      y,
      aspect,
    });
  
    return false; // Return false if you set crop state in here.
  }, []);

```
https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-forked-sy59w?file=/src/App.js:1127-1683

This is the image:

![132-21-24 (2)](https://user-images.githubusercontent.com/48766933/144512836-4c4fcb41-1079-43ba-9cd4-684cd93901a1.jpg)

and here is how it looks after load:
![image](https://user-images.githubusercontent.com/48766933/144512901-813380f1-7a05-4f3d-8b09-896155fdce38.png)

and here is how i expect it to look:
![image](https://user-images.githubusercontent.com/48766933/144679078-835077af-660e-4622-ae24-23b036017ee6.png)

**Comment by gschier** [comment]
It seems like the percentage unit is a bit buggy. I switched to `px` for this reason.

```tsx
function getDefaultCrop(img: ResizeImageResult): Crop {
  const aspect = 0.6;
  const padding = 20;
  const width = (img.width / aspect < img.height * aspect ? img.width : img.height * aspect) - padding;
  const height = (img.width / aspect > img.height * aspect ? img.height : img.width / aspect) - padding;
  const x = (img.width - width) / 2;
  const y = (img.height - height) / 2;
  return { aspect, width, height, x, y, unit: 'px' };
}
```

**Comment by supasus** [comment]
Can you please try the image included above? My code is just about the same, but the crop on load is still out of bounds.

**Comment by gschier** [comment]
I actually noticed it too later, if the image is larger than the crop element. I had to add some math to calculate the scaled size of the image based on the width of the container element.

**Comment by supasus** [comment]
Could you please share exactly what you did to avoid this issue. This would be really helpful, thanks.

**Comment by gschier** [comment]
> Could you please share exactly what you did to avoid this issue. This would be really helpful, thanks.

Sure, here's my full function that gets the default crop based on the image size and the size of the element that contains the crop component. I hope it helps @supasus!

```ts
function getDefaultCrop(img: ResizeImageResult, clientWidth: number, clientHeight: number): Crop {
  const aspect = 0.6;
  const padding = 20;

  const imgAspect = img.width / img.height;
  const imgWidthMax = Math.min(img.width, clientWidth);
  const imgHeightMax = Math.min(img.height, clientHeight);

  const imgWidth = imgHeightMax * imgAspect < clientWidth ? imgHeightMax * imgAspect : imgWidthMax;
  const imgHeight = imgWidthMax / imgAspect < clientHeight ? imgWidthMax / imgAspect : imgHeightMax;

  const width = (imgHeight * aspect < imgWidth ? imgHeight * aspect : imgWidth) - padding;
  const height = (imgWidth / aspect < imgHeight ? imgWidth / aspect : imgHeight) - padding;

  const x = (imgWidth - width) / 2;
  const y = (imgHeight - height) / 2;

  return { aspect, width, height, x, y, unit: 'px' };
}
```

**Comment by supasus** [comment]
> ```ts
>   // Calculate the max width/height of the image based on its size and the crop container
>   const imgAspect = img.width / img.height;
>   const imgWidthMax = Math.min(img.width, clientWidth);
>   const imgHeightMax = Math.min(img.height, clientHeight);
> 
>   // Calculate size of image based on aspect and max width/height
>   const imgWidth = imgHeightMax * imgAspect < clientWidth ? imgHeightMax * imgAspect : imgWidthMax;
>   const imgHeight = imgWidthMax / imgAspect < clientHeight ? imgWidthMax / imgAspect : imgHeightMax;
> 
>   // Calculate the default crop rectangle based on image size and crop aspect
>   const width = (imgHeight * aspect < imgWidth ? imgHeight * aspect : imgWidth) - padding;
>   const height = (imgWidth / aspect < imgHeight ? imgWidth / aspect : imgHeight) - padding;
> 
>   // Position crop rectangle in the exact center
>   const x = (imgWidth - width) / 2;
>   const y = (imgHeight - height) / 2;
> ```

Thank you very much! That was exactly what I needed.

**Comment by gschier** [comment]
Awesome! 🕺🏻

**Comment by DominicTobias** [comment]
Thanks I've updated the documentation and added some helpers to make it easier to do % images now, in v10:

```ts
function onImageLoad(e) {
  const { width, height } = e.currentTarget

  const crop = centerCrop(
    makeAspectCrop(
      {
        unit: '%',
        width: 100,
      },
      16 / 9,
      width,
      height
    ),
    width,
    height
  )

  setCrop(crop)
}
```

It's also on the codesandbox link: https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o
