### ISSUE TITLE
Scaled Image not Updating on the Cropped Parts

### ISSUE THREAD

**Issue by 87brandonn** [DominicTobias/react-image-crop#456]
Hi, i want to ask something regarding the scale and zoom props on the library. Here is the reproduced behaviour:

<img width="1440" alt="Screen Shot 2021-12-05 at 13 38 57" src="https://user-images.githubusercontent.com/53943296/144736524-2b8fd387-3cc2-4727-ab84-d10a3a387267.png">

When i set the slider scale to default scale (which is 1 by default), the cropped image looks good (shown below the real image).

But when i tried to adjust the scale with dynamic value (by triggering scale state changes everytime i slide the slider), the cropped would not adjust itself and still persist on the initial scale value. Here is the screenshot:

<img width="1440" alt="Screen Shot 2021-12-05 at 13 40 56" src="https://user-images.githubusercontent.com/53943296/144736587-04f202a6-ec55-457e-a77b-e2f3eb453076.png">

Maybe there should be another line of code that i should i add? Like on the completedCrop state? Here is the code anyway:
`import React, { useCallback, useEffect, useRef, useState } from 'react';
import ReactCrop from 'react-image-crop';
import Slider, { Range } from 'rc-slider';
import 'rc-slider/assets/index.css';
import 'react-image-crop/dist/ReactCrop.css';
import CustomModal from '../Modal';

function CropImageModal({
  show,
  setShow,
  upImg,
  handleDownload,
  crop,
  setCrop,
  circular,
}: any) {
  const previewCanvasRef = useRef(null);
  const imgRef = useRef<any>(null);

  const [completedCrop, setCompletedCrop] = useState<any>(null);

  const [scale, setScale] = useState(1);

  const onLoad = useCallback((img: any) => {
    imgRef.current = img;
  }, []);

  function generateDownload(canvas: any, cropped: any) {
    if (!cropped || !canvas) {
      return;
    }

    canvas.toBlob(
      (blob: any) => {
        const reader = new FileReader();
        reader.readAsDataURL(blob);
        console.log('converting');

        reader.onloadend = () => {
          console.log('converted');
          const base64data = reader.result;
          handleDownload(base64data);
        };
      },
      'image/png',
      1
    );
  }

  const handleSaveCrop = () => {
    generateDownload(previewCanvasRef.current, completedCrop);
    setShow(false);
  };

  useEffect(() => {
    if (!completedCrop || !previewCanvasRef.current || !imgRef.current) {
      return;
    }

    const image = imgRef.current;
    const canvas: any = previewCanvasRef.current;
    const cropClone = completedCrop;

    const scaleX = image.naturalWidth / image.width;
    const scaleY = image.naturalHeight / image.height;
    const ctx = canvas.getContext('2d');
    const pixelRatio = window.devicePixelRatio;

    canvas.width = cropClone.width * pixelRatio * scaleX;
    canvas.height = cropClone.height * pixelRatio * scaleY;

    ctx.setTransform(pixelRatio, 0, 0, pixelRatio, 0, 0);
    ctx.imageSmoothingQuality = 'high';

    ctx.drawImage(
      image,
      cropClone.x * scaleX,
      cropClone.y * scaleY,
      cropClone.width * scaleX,
      cropClone.height * scaleY,
      0,
      0,
      cropClone.width * scaleX,
      cropClone.height * scaleY
    );
  }, [completedCrop]);

  return (
    <CustomModal show={show} onHide={() => setShow(false)}>
      <div className="modal-crop">
        <h5 className="title">Crop Image</h5>
        <div className="crop-section">
          <div className="crop-wrapper">
            <ReactCrop
              src={upImg}
              onImageLoaded={onLoad}
              crop={crop}
              onChange={(c) => setCrop(c)}
              onComplete={(c) => setCompletedCrop(c)}
              circularCrop={circular}
              style={{
                width: '100%',
                height: 'auto',
                objectFit: 'cover',
                display: 'block',
              }}
              scale={scale}
            />
          </div>
        </div>
        <Slider
          onChange={(val) => setScale(val / 10)}
          min={10}
          startPoint={10}
        />
        <div className="crop-result">
          <div className="subtitle canvas-title">Cropped Result</div>
          <div>
            <canvas
              ref={previewCanvasRef}
              style={{
                width: Math.round(completedCrop?.width ?? 0),
                height: Math.round(completedCrop?.height ?? 0),
              }}
            />
          </div>
        </div>
        <div className="actions">
          <button type="button" className="btn btn-light">
            Cancel
          </button>
          <button
            type="button"
            className="btn btn-primary"
            onClick={() => handleSaveCrop()}
          >
            Save
          </button>
        </div>
      </div>
    </CustomModal>
  );
}

export default CropImageModal;
`

Anyway, appreciate your library so much. I was looking for the pintura things but seems to must use the pricing so i would prefer your library :)

**Comment by DominicTobias** [comment]
Hi do you still experience this issue with v10? https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o?file=/src/App.tsx

**Comment by DominicTobias** [comment]
Np, closing the issue now, feel free to open a new one if you have issues in v10
