### ISSUE TITLE
Change styling of crop boarder

### ISSUE THREAD

**Issue by zainen** [DominicTobias/react-image-crop#458]
Is it possible to change the styling of the crop border for this project? 
So far I have only been able to change the boarder of the entire area not the crop box directly

**Comment by DominicTobias** [comment]
<img width="494" alt="Screenshot 2021-12-11 at 19 58 16" src="https://user-images.githubusercontent.com/760314/145689914-5d3f6854-76e1-420a-bc6b-83659e916172.png">

You can target the class and change the border etc

**Comment by zainen** [comment]
Awesome! thank you :D

**Comment by DominicTobias** [comment]
I realise in hindsight the latest patch update may be a breaking change for you - the CSS was simplified to just `border: 1px dashed white;`
