### ISSUE TITLE
ES5 support

### ISSUE THREAD

**Issue by dnsmob** [DominicTobias/react-image-crop#459]
hiya
i am using version 8.6.12 and i'm getting a crash with the IE11. i can see `import` and `() =>` used in the transpiled/compiled code, which obviously isnt ES5 friendly. is this change by design or has it gone unnoticed?
looking at 9.0.5, the tsconfig seems unchanged, so i'm assuming it will crash in the same way.. 🧐
cheers

**Comment by dnsmob** [comment]
ok, i just been told IE is not supported. maybe a supported browsers in read me would be good? closing now.

**Comment by DominicTobias** [comment]
This sounds odd as I only export a UMD module (not using import) -
https://github.com/DominicTobias/react-image-crop/blob/master/webpack.config.js#L13

However yes you’re right IE is no longer supported, definitely should
mention in the Readme ;)
