### ISSUE TITLE
onClick cop area do not apear

### ISSUE THREAD

**Issue by revelict** [DominicTobias/react-image-crop#461]
Hi, I found an issue where area do not appear even if we have minimal width and height provided.
On mouse click  onChange callback is triggered but crop object is returned with width and height as 0.

is it expected behaviour?  When we do mouse move during mousedown, then te crop area is properly calculated for minimal dimensions.

![image](https://user-images.githubusercontent.com/17120146/150519149-f994361a-a20c-4b40-b601-7cf0c672c5d6.png)

Steps to reproduce,
provide minWidth and minHeight
click on image without movement

**Comment by DominicTobias** [comment]
Hi the behaviour at the moment is that you need to drag to get a crop, this allows you to click outside a crop to remove it.

The behaviour could be augmented like this:

```
onClick() {
  if (!there_is_a_crop) {
     // no crop so make one if both min dimensions are set 
  }
}
```

I'm working on other stuff and just doing important bug fixes atm, if you want to add this behavior though I'll accept the PR

**Comment by DominicTobias** [comment]
Closing as this is expected behaviour, if you don't want to allow the user to cancel a crop then you could force one to always be present with `keepSelection={true}`
