### ISSUE TITLE
How can I zoom an image while using react-image-crop?

### ISSUE THREAD

**Issue by Nurtilekk** [DominicTobias/react-image-crop#463]
I have to add crop image feature. I have used the react-image-crop to crop the specific part of the image. But now I need to zoom in the image and then crop the specific zoomed part of the image. How can I add zoom feature using react-image-crop?

**Comment by sekoyo** [comment]
You need to change the `scale` prop to a number above 1. You need to actually listen for mousewheel or pinch gesture etc and plug it into the prop.
