### ISSUE TITLE
Can't show crop selector on load without setting aspect ratio - then unable to free-form select

### ISSUE THREAD

**Issue by vgjenks** [DominicTobias/react-image-crop#468]
At least, not that I can find in your documentation, or by fumbling around w/ settings, myself. I want a 1/1 aspect ratio, but I want the selection to be freeform, like it would be when the aspect ratio is set. Problem is; without aspect ratio, the selection border doesn't appear w/o clicking and dragging...which is confusing my users.

**Comment by DominicTobias** [comment]
Hi what do you mean by free form selection? Do you mean drawing a new crop?

**Comment by vgjenks** [comment]
Free-form = Move x and y independently.

**Comment by DominicTobias** [comment]
Hm still not sure what you mean - how can you move x/y independently if it's always supposed to be a fixed aspect e.g. a 1:1 square?

**Comment by vgjenks** [comment]
OK, good point - How can I make the selector show up on load, and select 100% of the image? This is really what I'm trying to arrive at.

**Comment by DominicTobias** [comment]
I guess what you want is to center the largest possible crop given an aspect ratio? There is a discussion about that here which I didn't check yet but it seems they came to a solution: https://github.com/DominicTobias/react-image-crop/issues/455
