### ISSUE TITLE
Crop 1:1 aspect ratio seems to have regressed, or something

### ISSUE THREAD

**Issue by codenamegary** [DominicTobias/react-image-crop#470]
Version 9.1.0, all is well.

Version 9.1.1, no bueno.

I am using a 1/1 aspect ratio and I'm scratching my head a little. My code works perfect when I install 9.1.0. When I use 9.1.1, somehow the crop is sometimes allowed to expand along the X dimension, while maintaining the Y dimension. In other words, it doesn't respect the aspect ratio. I think this only happens when the crop is anchored to the bottom left corner.

Grabbed a gif of the behavior.

<a href="https://imgur.com/a/Qtbk0Fi">https://imgur.com/a/Qtbk0Fi</a>

**Comment by DominicTobias** [comment]
Thanks for the GIF. I'll fix it in v10 which might take a few days or so as I'm doing a large refactor.

**Comment by codenamegary** [comment]
Thanks for creating an awesome library!

**Comment by DominicTobias** [comment]
Please try v10 when you get a chance but note there are many breaking changes: https://github.com/DominicTobias/react-image-crop/releases

**Comment by DominicTobias** [comment]
Closing now, feel free to reopen if you have issues in v10
