### ISSUE TITLE
Height in parent element not followed

### ISSUE THREAD

**Issue by matthew-jones-uk** [DominicTobias/react-image-crop#475]
I have the following code:
```javascript
<Box width="100%" height="50vh">
    {validCrop ? <canvas ref={canvasRef} /> :
        <ReactCrop crop={crop} onChange={c => setCrop(c)}>
            <img alt="Highlight your cactus" src={imgSrc} />
        </ReactCrop>
    }
</Box>
```
Width is obeyed, but height is ignored. I expected the behaviour to be either that the image is warped to fit the size or, preferably, the lowest dimension is chosen to keep the aspect ratio of the image.

Am I doing anything wrong? Is this intended behaviour, and if so, is there any way to set the image size based on height?

**Comment by DominicTobias** [comment]
Are you talking about the canvas or the image?

**Comment by matthew-jones-uk** [comment]
Sorry, the image along with the ReactCrop. If I apply the size with style to ReactCrop, it works, but the images is just cut off (it isn't scaled to be visible).

**Comment by DominicTobias** [comment]
Can you post a screenshot? Normally only width is obeyed on an image, it's an [age old problem](https://stackoverflow.com/questions/3751565/css-100-width-or-height-while-keeping-aspect-ratio) but not quite sure what you're expecting since "warped" and keeping aspect ratio are two different things ;) Maybe `object-fit: contain` can help

**Comment by matthew-jones-uk** [comment]
> Can you post a screenshot?
Sure 🙂

The code in the original post produces:
![Screenshot_20220313_121907](https://user-images.githubusercontent.com/7196594/158059065-473ae037-2187-47d6-bf01-d4da63f304b6.png)
Is it normal behaviour for the `width=100%` to be followed, but not `height=50vh`? If I change `height=1px` it doesn't do anything either. The crop is also in the wrong location.

If I change it to something like:
```javascript
<Box width="100%" height="50vh">
    {validCrop ? <canvas ref={canvasRef} /> :
        <ReactCrop  style={{ maxWidth: "100%", maxHeight: "50vh" }} crop={crop} onChange={c => setCrop(c)}>
            <img alt="Highlight your cactus" src={imgSrc} />
        </ReactCrop>
    }
</Box>
```
Then it looks like:
![image](https://user-images.githubusercontent.com/7196594/158059143-57d18ea0-82c0-4fbd-b245-eb4c8627bdfc.png)
Where the image has just sort of been cut off, not scaled to the new size.

This is probably normal and expected behaviour, but how would I go about limiting the `<img>` and the `<ReactCrop>` to the given height and width, and have the image scale to that size? I'm not sure if this is just a lack of knowledge from me or something specific to how ReactCrop works.

**Comment by DominicTobias** [comment]
I see the issue, please upgrade to `10.0.0-beta.5` and try again

**Comment by matthew-jones-uk** [comment]
That works great, however the crop selection isn't set now. If I'm using pixel coordinates is it set according to new coordinates in the scaled image?

**Comment by DominicTobias** [comment]
Yep you’ll need to be aware of the size of the image to set an initial crop here’s an example: https://github.com/DominicTobias/react-image-crop#how-can-i-center-the-crop
