### ISSUE TITLE
ReactCrop V10.0.0 not triggering callbacks

### ISSUE THREAD

**Issue by YoramF** [DominicTobias/react-image-crop#478]
Hi,

I upgraded from v9.1.1 to 10.0.0 and all callback functions (props) are not triggered.

See my code:
********************************************
import React, { useState, useCallback, useRef} from 'react';
import PropTypes from 'prop-types';
import ReactCrop from 'react-image-crop';
import 'react-image-crop/dist/ReactCrop.css';

/**
 * 
 * @param {dataURI} inputImageUrl string of the input image
 * @param {string} imageStyle inline Style
 * @param {CallableFunction} setDataUrl
 */
const  ImgCropper = ({inputImageUrl, imageStyle, setDataUrl}) => {

  const imgRef = useRef(null);
  const previewCanvasRef = useRef(null);
  const [crop, setCrop] = useState({ unit: '%', width: 50,   height: 50, x: 25, y: 25, aspect: 3 / 4});

  const onLoad = useCallback((img) => {
    imgRef.current = img;
  }, []);

  const doneCrop = useCallback((crop) => {
    const image = imgRef.current;
    const canvas = previewCanvasRef.current;

    const scaleX = image.naturalWidth / image.width;
    const scaleY = image.naturalHeight / image.height;
    const ctx = canvas.getContext('2d');
    // const pixelRatio = window.devicePixelRatio;
    const pixelRatio = 1;

    canvas.width = crop.width * pixelRatio;
    canvas.height = crop.height * pixelRatio;

    ctx.setTransform(pixelRatio, 0, 0, pixelRatio, 0, 0);
    ctx.imageSmoothingQuality = 'high';

    ctx.drawImage(
      image,
      crop.x * scaleX,
      crop.y * scaleY,
      crop.width * scaleX,
      crop.height * scaleY,
      0,
      0,
      crop.width,
      crop.height
    );
    
    setDataUrl(canvas.toDataURL('image/jpeg', 1.0));
  }, [setDataUrl]);

  return (
	  <div>
        <ReactCrop
          src={inputImageUrl}
          onImageLoaded={onLoad}
          crop={crop}
          onChange={(c) => setCrop(c)}
          onComplete={doneCrop}
          imageStyle={imageStyle}
        />
        <canvas
          ref={previewCanvasRef}
          style={{display:'none'}}
        />
      </div>
  );
}

ImgCropper.propTypes = {
  inputImageUrl: PropTypes.string.isRequired,
  imageStyle: PropTypes.object.isRequired,
  setDataUrl: PropTypes.func.isRequired
  };

export default ImgCropper;
********************************************

Thanks,
Yoram.

**Comment by DominicTobias** [comment]
Hi what version are you using? My guess is that you upgraded to v10 but didn't update to fix breaking changes?

**Comment by YoramF** [comment]
Hi,

Correct, I upgraded to ,10.0.0 and did not change anything. Where can I read what needs to be changed once moving to V10.0.0?

Thanks

**Comment by YoramF** [comment]
Hi,

Thanks for the help. I did the required changes and everything works Hi,

Thanks for the help. I did the required changes and everything works perfectly.
Bellow is the updated module:

*********************
import React, { useState, useCallback, useRef} from 'react';
import PropTypes from 'prop-types';
import ReactCrop from 'react-image-crop'; // Version ^10.0.0
import 'react-image-crop/dist/ReactCrop.css';

/**
 * 
 * @param {dataURI} inputImageUrl string of the input image
 * @param {string} imageStyle inline Style
 * @param {CallableFunction} setDataUrl
 * 
 * use react-image-crop V10.0.0 and above
 */
const  ImgCropper = ({inputImageUrl, imageStyle, setDataUrl}) => {

  const imgRef = useRef(null);
  const previewCanvasRef = useRef(null);
  const [crop, setCrop] = useState({ unit: '%', width: 50,   height: 50, x: 25, y: 25});

  const doneCrop = useCallback((crop) => {
    const image = imgRef.current;
    const canvas = previewCanvasRef.current;

    const scaleX = image.naturalWidth / image.width;
    const scaleY = image.naturalHeight / image.height;
    const ctx = canvas.getContext('2d');

    // const pixelRatio = window.devicePixelRatio;
    const pixelRatio = 1;

    canvas.width = crop.width * pixelRatio;
    canvas.height = crop.height * pixelRatio;

    ctx.setTransform(pixelRatio, 0, 0, pixelRatio, 0, 0);
    ctx.imageSmoothingQuality = 'high';

    ctx.drawImage(
      image,
      crop.x * scaleX,
      crop.y * scaleY,
      crop.width * scaleX,
      crop.height * scaleY,
      0,
      0,
      crop.width,
      crop.height
    );
    
    setDataUrl(canvas.toDataURL('image/jpeg', 1.0));
  }, [setDataUrl]);

  return (
	  <div>
        <ReactCrop
          crop={crop}
          onChange={(c) => setCrop(c)}
          onComplete={doneCrop}
          aspect={3 / 4}>
            <img  ref={imgRef} src={inputImageUrl} style={imageStyle} alt=""/>
        </ReactCrop>

        <canvas
          ref={previewCanvasRef}
          style={{display:'none'}}
        />
      </div>
  );
}

ImgCropper.propTypes = {
  inputImageUrl: PropTypes.string.isRequired,
  imageStyle: PropTypes.object.isRequired,
  setDataUrl: PropTypes.func.isRequired
  };

export default ImgCropper;
*********************

Thanks again
Yoram..
