### ISSUE TITLE
Multi-selection feature

### ISSUE THREAD

**Issue by m8nli9ht** [DominicTobias/react-image-crop#479]
Hi Dominic,
 Thanks a lot for this great job. I'm using your tool inside an editor of annotations for manuscripts. I would like to know if you've already considered enabling the multi-selection feature which would be very useful in this editor.

BR,

Matthew

**Comment by DominicTobias** [comment]
Hey sorry I don't have plans to do this it would be a significant change, it might be possible to nest `<ReactCrop>` components but didn't try
