### ISSUE TITLE
In an iframe, if the component is rendered in a popup and the popup is mounted in window.top.document, user events don't work correctly

### ISSUE THREAD

**Issue by juilletVent** [DominicTobias/react-image-crop#482]
## Question Scene

The rendering position of the component is located in the iframe and used in the pop-up layer. The mounting position of the pop-up layer is located in window.top.document

## Reason

I have noticed that the binding and unbinding of user events are implemented in the bindDocMove and unbindDocMove methods. These methods use document.addEventListener and document.removeEventListener for event registration and deregistration. However, in iframe nested pages, if the clipping component is When applied to the pop-up layer and the mounting position of the pop-up layer is located in the top-level document, this implementation is invalid, and the corresponding user events cannot be monitored, because the operation layer is mounted to the top-level document object.

## Resolve

I temporarily changed document.addEventListener to window.top.document.addEventListener to solve this problem, hope you can fix it. thx!

**Comment by DominicTobias** [comment]
Hi, please update to `10.0.1`, then you can do this:

```ts
import ReactCrop, { ReactCropProps } from 'react-image-crop'

class IframeReactCrop extends ReactCrop {
  constructor(props: ReactCropProps) {
    super(props)
    this.document = window.top.document
  }
}
```

And use `<IframeReactCrop>` instead.

**Comment by juilletVent** [comment]
got it,thx ~
