### ISSUE TITLE
Document is not defined

### ISSUE THREAD

**Issue by Tenpi** [DominicTobias/react-image-crop#487]
Using this component with server-sided rendering gives the error "document is not defined", although it is an easy fix it would be nice if you handle this within the component so that I don't have to. 

You could just return null if the document isn't yet defined.

**Comment by DominicTobias** [comment]
Hm yeah I guess assigning document up front caused the issue in 10.0.1, will make a fix soon

**Comment by DominicTobias** [comment]
Fixed in [10.0.2](https://github.com/DominicTobias/react-image-crop/releases/tag/10.0.2)
