### ISSUE TITLE
centerCrop and centerAspectCrop not working correctly for vertical images

### ISSUE THREAD

**Issue by NathanC** [DominicTobias/react-image-crop#490]
I'm attempting to center a 1/1 aspect ratio crop as specified [here](https://www.npmjs.com/package/react-image-crop#how-can-i-center-the-crop).

# For horizontal images, it works correctly. See:
![image](https://user-images.githubusercontent.com/6182419/173204794-d130f439-0dfd-47ed-98fb-715d5ff8ecdd.png)

# However for vertical images, it doesn't take up the full width:
![image](https://user-images.githubusercontent.com/6182419/173204820-b1c88d3f-8fe6-425e-83cc-492c96555a4a.png)

The code I'm using to generate the crop is as follows:
```javascript
const crop = centerCrop(
   makeAspectCrop(
      {
         // You don't need to pass a complete crop into
         // makeAspectCrop or centerCrop.
         unit: '%',
         width: 90
      },
      1 / 1,
      image.width,
      image.height
   ),
   image.width,
   image.height
)
```

Am I doing something wrong, or is this a bug? Thanks in advance!

**Comment by DominicTobias** [comment]
Hi, change your width from 90 to 100%

**Comment by NathanC** [comment]
Ahhhh of course, makes perfect sense! Thank you.

Unrelated, but how would people feel about me adding a helper function to the library to generate a dataUrl from an image and crop? I made one for myself and it's pretty useful, but had to rework it for % units.
