### ISSUE TITLE
Tabbing causes crop to exceed image dimensions

### ISSUE THREAD

**Issue by NathanC** [DominicTobias/react-image-crop#491]
When I tab through my page and it iterates over the crop handles in my react-image-crop component, it **shifts the image past the image boundries**, when it highlights the crop handle. It only does this when the existing crop is flush with image border.

Here's a gif demonstrating this. Notice what happens when I tab to the third (bottom right) crop handle:

![image-crop-bug](https://user-images.githubusercontent.com/6182419/173311419-dc662c8c-5042-457d-98c9-b4dc9161cfec.gif)

Is there a way to avoid this?

**Comment by DominicTobias** [comment]
Hey, thanks for finding this. Please try 10.0.3

**Comment by NathanC** [comment]
That was quick!

10.0.3 **partially** works. The issue is no longer there for horizontal images, but it's still there for vertical ones:

![image](https://user-images.githubusercontent.com/6182419/173457929-b2f65898-ab43-4a6e-aa13-c1317813451d.png)

**Comment by NathanC** [comment]
No rush! Thanks for creating this library, it's extremely useful and clean.

**Comment by DominicTobias** [comment]
> No rush! Thanks for creating this library, it's extremely useful and clean.

Thanks! Please try 10.0.4

**Comment by venkat-naiduc360** [comment]
its not working

**Comment by venkat-naiduc360** [comment]
need preview
