### ISSUE TITLE
Using integer on crop

### ISSUE THREAD

**Issue by YoannBuzenet** [DominicTobias/react-image-crop#498]
Hello,

I'm using `sharp` library to resize the images I'm cropping with your library. However, Your library offers pixels as floats. Example :

```js
height: 173.25559997558594
unit: "px"
width: 346.5111999511719
 x: 139.39031982421875
 y: 37.63502502441406
```

How can pixels be a float ? It should only be integers, right ?

Would you have an advice on how to use it with sharp that only accept integers. I can parseInt when `SetCrop`, but I'm not sure it would be understanding well what's going on.

**Comment by DominicTobias** [comment]
Hey, many browsers do actually lay things out with sub pixel accuracy so I don't round down the numbers and leave them as accurate as possible and let the browser handle it. However it should be fine to do `Math.round` on them yourself (no need for `parseInt`.
