### ISSUE TITLE
Resizing crop can cause larger jump than intended

### ISSUE THREAD

**Issue by mskelton** [DominicTobias/react-image-crop#502]
When resizing a crop in v10, it can cause large jumps in the crop area when clicking on the outsides of the drag handles.  Doing some investigation, this seems to be due to the fact that the diffing logic of the current value of `clientX` and `startClientX` is incorrect due to `startClientX` being generated from the crop size and location, but the actual location where the pointer was pressed down is lost.  This results in an initial jump followed by smooth cropping.

## Example

I increased the drag handle size to make it easier to see the issue.  It's quite easy to reproduce by simply clicking the edge of a drag handle and moving ever so slightly after which the crop jumps.

https://user-images.githubusercontent.com/25914066/181614054-9bb0bd47-5128-4eb4-94fc-9bb459af7648.mov

**Comment by DominicTobias** [comment]
Thanks for the detailed issue, your analysis was correct. There might be a smarter way to do it but I just offset `startClientX/Y` from the distance to the corner. Fix is on master will publish soon (will see if I'll put any other fixes in too)

**Comment by DominicTobias** [comment]
Published in 10.0.5
