### ISSUE TITLE
How to set the completedCrop on onLoad called?

### ISSUE THREAD

**Issue by muneebejazz** [DominicTobias/react-image-crop#511]
hello, 

ReactCrop has onComplete  callback which is called when crop area is changed, what i am trying to achieve is i want to crop the selected Image from input file to "16/9" to crop the image 16/9 without changing /dragging /nudge crop area , because the onComplete is called when area is changed,

what i am successFull at : getting the copped image when crop area is changed /dragged
what i am un successful at:    getting the copped image when crop area is not changed/ means how i can call the onComplete callback  when image is loaded on onLoad in React

Please can you write the code in react in useEffect / or any other way you like without using useEffect but in Reactjs. thanks.

**Comment by NandoCanedo** [comment]
Got the same problem.
I can't get the image properly cropped with default crop positioning (without user dragging or resizing crop definitions).

**Comment by DominicTobias** [comment]
Sorry I'm not following? If you call `setCrop` in the `onLoad` of the image then `onComplete` gets called - you can see it action over here: https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o?file=/src/App.tsx

So maybe I misunderstood the issue? 🤔

**Comment by NandoCanedo** [comment]
In my case it was just a stupid bug in my code which was reseting the default crop. It is fine now

**Comment by muneebejazz** [comment]
What was the bug and how did you solve that?

**Comment by NandoCanedo** [comment]
not sure if my problem was the same as yours, but I was running a setCrop somewhere else in my code and spoiling my results

**Comment by muneebejazz** [comment]
Can you share your code please?

**Comment by NandoCanedo** [comment]
Something like this... Hope it helps.
`import React, { useRef } from 'react'
import {
  Avatar,
  Box,
  Button,
  Dialog,
  DialogActions,
  DialogTitle,
} from '@mui/material'
import CloudUploadIcon from '@mui/icons-material/CloudUpload'
import DeleteForeverIcon from '@mui/icons-material/DeleteForever'
import styled from 'styled-components'
import { grey } from '@mui/material/colors'
import servicePessoas from '../services/servicePessoas'
import utils from '../utils'
import ReactCrop, { centerCrop, makeAspectCrop } from 'react-image-crop'
import 'react-image-crop/dist/ReactCrop.css'

const CenteredContent = styled.div`
  text-align: center;
`

const BigAvatar = styled(Avatar)`
  width: 120px;
  height: 120px;
  margin: 0 auto;
  border: 1px solid ${grey[500]};
  box-shadow: 0 0 1px 0 ${grey[500]} inset, 0 0 1px 0 ${grey[500]};
`

const AvatarUpload = ({ nome, pessoa, setPessoa }) => {
  const [openCrop, setOpenCrop] = React.useState(false)
  const [completedCrop, setCompletedCrop] = React.useState()
  const [crop, setCrop] = React.useState()
  const [image, _setImage] = React.useState(utils.montaUrlFoto(pessoa.urlFoto))
  const imgRef = useRef(null)
  const inputFileRef = React.createRef(null)

  const cleanup = () => {
    URL.revokeObjectURL(image)
    inputFileRef.current.value = null
  }

  const setImage = (newImage) => {
    if (image) {
      cleanup()
    }
    _setImage(newImage)
  }

  function centerAspectCrop(mediaWidth, mediaHeight, aspect) {
    return centerCrop(
      makeAspectCrop(
        {
          unit: '%',
          width: 90,
        },
        aspect,
        mediaWidth,
        mediaHeight,
      ),
      mediaWidth,
      mediaHeight,
    )
  }

  function onImageLoad(e) {
    const { width, height } = e.currentTarget
    setCrop(centerAspectCrop(width, height, 1))
  }

  const onSelectFile = (event) => {
    const newImage = event.target?.files?.[0]
    if (newImage) {
      setCrop(undefined)
      let urlImage = URL.createObjectURL(newImage)
      setImage(urlImage)
      setOpenCrop(true)
    }
  }

  function dataURLtoFile(dataurl, filename) {
    let arr = dataurl.split(','),
      mime = arr[0].match(/:(.*?);/)[1],
      bstr = atob(arr[1]),
      n = bstr.length,
      u8arr = new Uint8Array(n)

    while (n--) {
      u8arr[n] = bstr.charCodeAt(n)
    }
    let croppedImage = new File([u8arr], filename, { type: mime })
    return croppedImage
  }

  function getCroppedImg(image, crop) {
    const canvas = document.createElement('canvas')
    const scaleX = image.naturalWidth / image.width
    const scaleY = image.naturalHeight / image.height
    canvas.width = crop.width
    canvas.height = crop.height
    const ctx = canvas.getContext('2d')

    const pixelRatio = window.devicePixelRatio
    canvas.width = crop.width * pixelRatio
    canvas.height = crop.height * pixelRatio
    ctx.setTransform(pixelRatio, 0, 0, pixelRatio, 0, 0)
    ctx.imageSmoothingQuality = 'high'

    ctx.drawImage(
      image,
      crop.x * scaleX,
      crop.y * scaleY,
      crop.width * scaleX,
      crop.height * scaleY,
      0,
      0,
      crop.width,
      crop.height,
    )

    const reader = new FileReader()
    canvas.toBlob((blob) => {
      reader.readAsDataURL(blob)
      reader.onloadend = () => {
        // setOutputImage(reader.result);
        uploadFoto(dataURLtoFile(reader.result))
      }
    })
  }

  function handleSalvaCrop(event) {
    getCroppedImg(imgRef.current, completedCrop)
  }

  function uploadFoto(newImage) {
    if (newImage) {
      servicePessoas.uploadFoto(pessoa.id, newImage).then((resp) => {
        let urlImage = URL.createObjectURL(newImage)
        setImage(urlImage)
        console.log(urlImage)
        setPessoa({ ...pessoa, urlFoto: urlImage })
        setOpenCrop(false)
      })
    }
  }

  const handleLimpaFoto = (event) => {
    event.preventDefault()
    if (image) {
      servicePessoas.excluiFoto(pessoa.id).then((resp) => {
        setImage(undefined)
        setPessoa({ ...pessoa, urlFoto: undefined })
      })
    }
  }

  return (
    <>
      <CenteredContent>
        <BigAvatar
          alt={nome}
          src={image || '/static/img/avatars/default-profile.svg'}
          imgProps={{
            style: {
              maxHeight: '100%',
              maxWidth: '100%',
              objectFit: 'cover',
            },
          }}
        />

        <Box m={1}>
          <Button
            component="label"
            size="small"
            variant="contained"
            color="inherit"
            onClick={image ? handleLimpaFoto : undefined}
            startIcon={
              image ? <DeleteForeverIcon mr={2} /> : <CloudUploadIcon mr={2} />
            }
          >
            {image ? 'Clean' : 'Upload'}
            <input
              ref={inputFileRef}
              accept="image/*"
              hidden
              id="avatar-image-upload"
              type="file"
              onChange={onSelectFile}
            />
          </Button>
        </Box>
      </CenteredContent>
      <Dialog open={openCrop} onClose={() => setOpenCrop(false)}>
        <DialogTitle>Ajuste o tamanho da imagem</DialogTitle>
        <ReactCrop
          keepSelection
          circularCrop
          aspect={1}
          crop={crop}
          onChange={(crop, percentCrop) => setCrop(percentCrop)}
          onComplete={(c) => setCompletedCrop(c)}
        >
          <img onLoad={onImageLoad} src={image} alt="imagem" ref={imgRef} />
        </ReactCrop>
        <DialogActions>
          <Button color="inherit" onClick={() => setOpenCrop(false)}>
            Cancelar
          </Button>
          <Button
            variant="contained"
            onClick={handleSalvaCrop}
            disabled={!Boolean(completedCrop)}
          >
            Salvar
          </Button>
        </DialogActions>
      </Dialog>
    </>
  )
}

export default AvatarUpload
`

**Comment by muneebejazz** [comment]
Ok thanks i will look into it 👍

**Comment by ARival** [comment]
Bumping.

I am using this library to select several crops on the same image. Every time I click save, I reset the crop with `setCrop` using the `centerAspectCrop` function from the example. The crop DOES reset properly, but `completedCrop` isn't updated until I interact with the resize rectangle with my mouse. I need to trigger `setCompletedCrop` with the reset crop for things to function properly.

You can see this behavior in this repo's example by toggling the aspectRatio, moving the rectangle, then toggling again. The crop preview doesn't update.

**Comment by DominicTobias** [comment]
When you update `crop` (via `setCrop`) it doesn't automatically call `onComplete ` because that would result in an infinite loop (since onComplete is where you're supposed to call `setCrop`). So if you manually call it somewhere else then call whatever function you call in `onComplete` manually too.
