### ISSUE TITLE
how to upload to the server?

### ISSUE THREAD

**Issue by Goowwy** [DominicTobias/react-image-crop#513]
how to get filelist?

**Comment by DominicTobias** [comment]
Your question is too incomplete to answer. It depends on your server, if you want to upload the original file and do the cropping on the server, or crop on the client and upload that. You can google for either way e.g.

https://betterprogramming.pub/a-complete-guide-of-file-uploading-in-javascript-2c29c61336f5

https://stackoverflow.com/questions/5587973/javascript-upload-file

https://levelup.gitconnected.com/crop-images-on-upload-in-your-react-app-with-react-image-crop-5f3cd0ad2b35
