### ISSUE TITLE
Fixing the Crop size but allowing the user to position the crop

### ISSUE THREAD

**Issue by kshitijbahul** [DominicTobias/react-image-crop#52]
Hello, I was having a look at this component and I was wondering if it would be possible to fix the size of the crop but allowing the user to position the crop anywhere on the image ? The `minHeight` and `minWidth` property allow us to do this in part but the user would still be able to increase the crop.

Will it be possible to achieve this in the current state of the component or would it need additional max height and Width props ?

**Comment by DominicTobias** [comment]
Hi, it may be possible to limit the width from the parent by modifying the values in onChange and re-rendering the component, however that sounds like a hack and might not work/be efficient. Having `maxWidth` and `maxHeight` props sounds reasonable though so I'll add them in the next week.

**Comment by DominicTobias** [comment]
Released in rc7

**Comment by kshitijbahul** [comment]
Thank you so much for this feature in the awesome plugin @DominicTobias  :+1:
