### ISSUE TITLE
How to implement animated crop select area as on example?

### ISSUE THREAD

**Issue by jdolinski1** [DominicTobias/react-image-crop#538]
Hello,

your demo example .gif in README shows "animated" selected area border
https://raw.githubusercontent.com/DominicTobias/react-image-crop/master/crop-demo.gif
but this library is not behaving this way out of the box.

Are any examples of how to implement this available?

Thanks

**Comment by DominicTobias** [comment]
Hi, this was removed some versions ago as it was a bit hacky and had issues in modern browsers. I just update it to add it back but a more standard way. Please try `10.1.4`
