### ISSUE TITLE
[bug] issue with the exports field in the react-image-crop package's package.json file

### ISSUE THREAD

**Issue by quyle92** [DominicTobias/react-image-crop#540]
Hi,
There is issue in package.json of react-image-crop in the latest version of the package, which prevents the `ReactCrop.css `from being imported.
Solution:
- adding `"./dist/ReactCrop.css": "./dist/ReactCrop.css" `to exports field located in the `node_modules/react-image-crop` directory.

**Comment by DominicTobias** [comment]
Thanks I'll add that, I thought it would fallback to the real path and find it without having to specify

**Comment by DominicTobias** [comment]
Published, could you try `10.1.1` please?
