### ISSUE TITLE
Can't compile on TypeScript because of no type definition file

### ISSUE THREAD

**Issue by KashEight** [DominicTobias/react-image-crop#541]
## Version
v10.1.0

## Environment
Node.js: v18.15.0
pnpm: v8.5.1

## What's happened?
When `react-image-crop` has updated, TypeScript Compiler (tsc) output the error:
```
error TS7016: Could not find a declaration file for module 'react-image-crop'. '/<project>/node_modules/react-image-crop/dist/index.js' implicitly has an 'any' type.
```
I followed the error and checked `node_modules/react-image-crop/dist/` directory, and I found no `index.d.ts` in that.

In Addiction, I cloned this project, self-built, and checked `dist/` directory.
So, this was the contents in `dist/`:
```
dist/
├─ index.js
├─ index.umd.cjs
└─ ReactCrop.css
```

---
**Edit:**
I checked `dist/` on v10.0.11 and this was the result:
```
dist/
├─ index.d.ts
├─ ReactCrop.css
├─ ReactCrop.d.ts
├─ ReactCrop.min.js
├─ types.d.ts
└─ utils.d.ts
```
---

This was caused to changed config on this commit: https://github.com/DominicTobias/react-image-crop/commit/2907c45caea81f69ca9a554ee9b7564c9ddc2d83
(Build tool was changed from Webpack to Vite, so I think this bug happens.)

Should I create PR about it?

**Comment by DominicTobias** [comment]
Thanks this should be fixed in `10.1.2`
