### ISSUE TITLE
Not working properly when parent container is rotated

### ISSUE THREAD

**Issue by david-babunashvili** [DominicTobias/react-image-crop#545]
When I'm trying to crop an image inside a rotated parent element it doesn't work well, any idea?

![CleanShot 2023-06-08 at 17 27 22](https://github.com/DominicTobias/react-image-crop/assets/91557703/80ea422f-3e82-4431-a786-1086a9d5424e)

**Comment by DominicTobias** [comment]
Hi sorry but this library doesn't support this kind of rotation, only rotating the image but not the crop like in the demo - https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o

I do wonder what the final image would look like in your case?

So you'll either have to use a different library, or use v9 of this one which had a `spin` prop - https://github.com/DominicTobias/react-image-crop/tree/9.1.1#spin-optional but I removed this as it was hardly used and difficult to maintain (involved some trigonometry maths and there was an issue I couldn't fix, though it worked for most cases)
