### ISSUE TITLE
marching-ants border animation obscured when using isCircularCrop prop

### ISSUE THREAD

**Issue by RwwL** [DominicTobias/react-image-crop#546]
![image](https://github.com/DominicTobias/react-image-crop/assets/340967/868f680a-f18d-4374-a70d-9df3595c94af)

I noticed this while getting started setting this up in my own app and verified that the same issue occurs on the [CodeSandboxDemo](https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o?file=/src/App.tsx) when you use the `isCircularCrop` prop.

Ideally (probably) the ants would march around the ellipse shown.

**Comment by DominicTobias** [comment]
Thanks, because it's still a rectangular div I think it would be too complex to try and do an animated one for it so I've switched to use static dashed border for circular crops

**Comment by RwwL** [comment]
@DominicTobias Yeah, I started researching whether this could be possible with CSS radial-gradients but very quickly questioned whether it was even possible, or if it'd be worth the effort.

Thanks for creating and maintaining this package, though, it's really very nice. Very impressed with the keyboard navigation options.
