### ISSUE TITLE
Overlay in Safari

### ISSUE THREAD

**Issue by thchia** [DominicTobias/react-image-crop#55]
Hi,

I'm having issues with the crop box not showing on Safari (9.1.2).

Functionality is fine; I can drag and the crop box will appear, but it does not auto appear on loading even though I have defined the crop settings.

No issues on Chrome so it's definitely a Safari issue.

**Comment by DominicTobias** [comment]
Thaks I'm able to replicate this and will look into it

**Comment by DominicTobias** [comment]
Actually I take that back - I'm unable to replicate this - are you sure you are passing a valid crop? What crop values are you using?

**Comment by DominicTobias** [comment]
@thchia can you post a link to the image (in original size) and also the values of this.state.x/y/width please?

**Comment by thchia** [comment]
The image is one uploaded from my local computer, it's not currently hosted anywhere. The issue is present with other uploaded images too.

The values are:

`this.state.x: 10,`
`this.state.y: 10,`
`this.state.width: 80`

**Comment by DominicTobias** [comment]
I still can't replicate this in OSX Safari 9.1.2 - here are my crop values:

```js
crop: {
  aspect: 1,
  x: 10,
  y: 10,
  width: 80,
}
```

Using this image: https://postimg.org/image/ffs255dpd/

Let me know if you are having the issue with those values and image. If so I'll need to see more code as the problem might be somewhere else.

**Comment by thchia** [comment]
Ok, the issue seems to be the way I'm setting the src prop.

What I'm trying to do is let the user upload an image (via an input file element), and crop it _before_ uploading the cropped image to the server. Because there is no access to the local file path from the web app, my workaround was to read the file as a DataURL and store the result in React state. Then I set the src prop as `this.state.imgDataURL`.

This seems to be the source of the problem though, as I cannot recreate the issue with images stored in the app's root dir. I guess the only way is to upload the original image first before performing the crop functions.

Thanks for the help.

**Comment by DominicTobias** [comment]
Hm interesting, sounds like possibly a browser bug, there were some similar
sounding issues with Safari I'll check it out

**Comment by DominicTobias** [comment]
Closing this as it seems quite niche, hope it worked out
