### ISSUE TITLE
Resizing crop from corners makes cropped area moves outside the cropping container area 

### ISSUE THREAD

**Issue by ochurae** [DominicTobias/react-image-crop#554]
NOTE: Such behaviour appears only when minWidth/minHeight props defined.

Here is an example:
![Screen recording](https://github.com/DominicTobias/react-image-crop/assets/143394596/3c143e4e-94ca-46e7-b516-d66ccade4ede)

React: v18.2.0
react-image-crop: v10.1.5

**Comment by DominicTobias** [comment]
Thanks for reporting this and the helpful .gif. Please try 10.1.6

**Comment by DominicTobias** [comment]
FYI I've introduced an issue when only minWidth or minHeight are set which I'll fix in next patch

**Comment by DominicTobias** [comment]
Fix publish to 10.1.7

**Comment by ochurae** [comment]
Nice, now works perfectly. Thank you for such fast fix :)
