### ISSUE TITLE
Select Box Fails to Appear when using ReactCrop.css?

### ISSUE THREAD

**Issue by JesseAbeyta** [DominicTobias/react-image-crop#557]
React Version: "^16.13.1"
"react-image-crop": "^10.1.8",

I was recently having an issue with this library where the selection box was not appearing even though I had a valid crop set up. Using element inspector, I found the crop selection area was below my image and had zero height. Using a percent crop instead of a pixel crop would cause an empty area to grow below the image. 

I had been using the css import from the example. 
`import 'react-image-crop/dist/ReactCrop.css'`
Changing it to
`import 'react-image-crop/src/ReactCrop.scss'`
Immediately fixed the issue.

The issue may be related to my webpack config.
```
      {
        test: /\.css$/,
        use: [
          { loader: "style-loader" },
          {
            loader: "css-loader",
            options: {
              modules: true,
            },
          },
        ],
      },
      {
        test: /\.s[ac]ss$/i,
        use: [
          // Creates `style` nodes from JS strings
          "style-loader",
          // Translates CSS into CommonJS
          "css-loader",
          // Compiles Sass to CSS
          "sass-loader",
        ],
      },
```

Hopefully this helps somebody else! Entirely possible the error is completely on my end.

**Comment by DominicTobias** [comment]
Hi, this is not an issues with the library but rather your setup of CSS here:

```
{
  loader: "css-loader",
  options: {
    modules: true,
  },
},
```

You are treating all css files as css modules which mangles the CSS classnames. You can do something like this instead:

```
{
  loader: "css-loader",
  options: {
    modules: {
      auto: /\.module\.css$/,
    },
  },
},
```

And then only css files which end in `.module.css` will be treated as CSS modules
