### ISSUE TITLE
Limit crop container element to max height

### ISSUE THREAD

**Issue by DvirH** [DominicTobias/react-image-crop#56]
I can limit the container div to max-width but no to max-height.
For example if my crop container has to be 300px * 300px, I want to be able to fit the image by its ratio. 

How can I  manage this?

**Comment by DominicTobias** [comment]
@DvirH not quite sure what you mean - can you post the props/crop you are using as well as a link to the image please?

**Comment by DvirH** [comment]
Partial solved with css
