### ISSUE TITLE
Setting unit % automatically changed to px after the crop

### ISSUE THREAD

**Issue by ceelsoin** [DominicTobias/react-image-crop#562]
Library version:    ` "react-image-crop": "^10.1.8",`
React version: `"react": "^17",`
React DOM version: `"react-dom": "^17",`

I did a crop component using this library that user start crop in defined position and can change it during the journey. I selected % unit to work in backend crop after image upload, but, if user change crop in component the unit automatically changes to px, but i need to keep in %.

The highlights of my configuration: 

```jsx
    const [crop, setCrop] = useState({
        unit: "%",
        x: 0,
        y: props.height / 2,
        width: 100,
        height: 45,
    })
```

```jsx
<ReactCrop unit="%" ruleOfThirds={true} crop={crop}  onChange={c => setCrop(c)}>
{    
   image.blob ? <img src={image.blob} width={'100%'} height={'100%'} /> : null
}
</ReactCrop>
```

On submite without change crop:
```json
{"unit":"%","x":0,"y":22.5,"width":"100","height":"45","aspect":2.2222222222222223}
```

On submite after changed crop:
```json
{"unit":"px","x":160.90911865234375,"y":41.477264404296875,"width":209.99993896484375,"height":189.99998474121094,"aspect":2.2222222222222223}
```

**Comment by DominicTobias** [comment]
You have to use the second param onChange/onChangeComplete I.e. onChange((_pixelCrop, percentCrop) => setCrop(percentCrop))

**Comment by ceelsoin** [comment]
Thanks, sorry for dummy issue, but yesterday i spent my day trying to fix this lol. Today i found #370 and it solved it. 

But i think the onChange callback maybe return in main parameter the unit setted value. This is just a suggestion.

Thanks for help
