### ISSUE TITLE
outline is not circled with circularCrop in safari browser

### ISSUE THREAD

**Issue by junzero741** [DominicTobias/react-image-crop#567]
google chrome (ideal)
![image](https://github.com/DominicTobias/react-image-crop/assets/71166372/528a3290-8645-48fc-beee-037ded918941)

safari 
![image](https://github.com/DominicTobias/react-image-crop/assets/71166372/f9d88949-500b-48e5-b5b7-534a86e2407f)

**Comment by DominicTobias** [comment]
Circular crop works for me in Safari 17 🤔
Try version 11 I am releasing today or tomorrow which has a new technique for this, and the shadow part works too

<img width="1542" alt="Screenshot 2023-12-01 at 00 12 08" src="https://github.com/DominicTobias/react-image-crop/assets/760314/0f10b9d6-51f1-47ae-8a4b-974fcf8d3eb9">
