### ISSUE TITLE
Need to rotate selected(croped) image

### ISSUE THREAD

**Issue by Ramin-Khodaie** [DominicTobias/react-image-crop#571]
In my scenario after croping image with the shape of square, I need to rotate it due to the logic of buisines. Is there any prop or solution for this subject?
I try `transform` property for style in ReactCrop but it rotate whole image including croped one.
All I want is when drawing square on image, I could rotate this square. Thats all I want.
I would happy if someone help me.

**Comment by DominicTobias** [comment]
There was a `spin` prop in v9 to help doing this, but I ended up removing it as it was a bit complicated and had a bug that I was unable to solve (#434 #436 #485)

I think you're better off using a lib that specifically supports that as it is non trivial to implement and the functionality isn't in this lib anymore.

**Comment by Ramin-Khodaie** [comment]
Thank you for your response. By the way I solve my issue using this package at least. I implement a logic to adjust the rotation of `.ReactCrop__crop-selection` css class, all I did was having a HOC to handle the rotate on my ReactCrop component.

**Comment by DominicTobias** [comment]
Interesting, all you did was CSS rotate?

**Comment by Ramin-Khodaie** [comment]
yes, I just applied css property `transform: rotate(${props.rotation}deg); ` to ` &&&.ReactCrop .ReactCrop__crop-selection` in my StyledComponent named StyledReactCrop.
