### ISSUE TITLE
Synchronization Issue Between Multiple Cropper Instances on the Same Page

### ISSUE THREAD

**Issue by kfs214** [DominicTobias/react-image-crop#572]
# Synchronization Issue Between Multiple Cropper Instances on the Same Page

## Environment

- **OS:** MacOS Ventura 13.4.1
- **Browsers:**
  - Safari: Functions correctly
  - Chrome: Encounters an issue

## Issue Description

On a single page of my application, there are multiple cropper instances, each intended to have its unique selection area. However, changes in the first instance unintentionally affect others.

## Problem Analysis

The issue originates from identical IDs assigned to the mask elements (`hole`). This causes all instances to refer to the same mask, disrupting their individual functionalities.

## CodeSandBox

- [View the issue demonstration in this CodeSandBox](https://codesandbox.io/p/sandbox/react-image-crop-demo-with-react-hooks-forked-whzrtr)

## Screenshots

- Safari (Functions correctly)
![Safari](https://github.com/DominicTobias/react-image-crop/assets/41105246/636380fe-c0ee-4424-b742-9ea6eefe4df8)

- chrome (Encounters an issue)
![chrome](https://github.com/DominicTobias/react-image-crop/assets/41105246/09867675-8a83-43c9-a126-35ba302e1381)

**Comment by DominicTobias** [comment]
Thanks for the detail and finding the cause 🙏 Please try 11.0.2

**Comment by kfs214** [comment]
Thank you for your quick response!
The problem has been resolved.

And I also appreciate this great repository. 🚀
