### ISSUE TITLE
Max height

### ISSUE THREAD

**Issue by nhagen** [DominicTobias/react-image-crop#6]
The responsive aspect of this is great, but I'm not seeing a way to limit height for tall images. Is there an easy path to doing this?

**Comment by DominicTobias** [comment]
Hi & thanks @nhagen, the css intentionally doesn't apply any rules to the dimensions, it will just grow up to the maximum width of the image. I recommend you apply css to it, or to the container such as `max-height`, Without knowing the layout that this will be used in, it's best to leave that up to the website using it. https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=css%20limit%20image%20height
