### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by riccardolorenzon** [DominicTobias/react-image-crop#62]
Hi,

Sometimes(i can't reproduce it though) i get a CORS exception while loading the image in the canvas, as result the image is rendered(with the crop) in a very small square area. 
All the images i use are loaded from a S3 bucket(i already added the CORS configuration to it). 

Am i the only one who is having this issue?

**Comment by DvirH** [comment]
I found a work around by loading the image to an element with ` image.setAttribute('crossOrigin', 'anonymous');` and blob it into the cropper.

**Comment by DominicTobias** [comment]
Thanks for the fix (merged), will hopefully publish v1.0.0 over the weekend with this fix in it

**Comment by springuper** [comment]
`crossorigin=""` not works in Chrome 54.0.2840.98. can you provide a option not to set this attribute?

**Comment by Grantlyk** [comment]
I'm currently having an issue with this, is anyone still having this issue?

**Comment by DominicTobias** [comment]
Interesting, were you also trying to map the image on to a canvas?

**Comment by Grantlyk** [comment]
Yeah, all that stuff is working fine though

**Comment by DominicTobias** [comment]
Cool, so sounds like undefined should be the default as it used to be

**Comment by Grantlyk** [comment]
Yup, that's what I was thinking -- Do you want to PR it or should I?

**Comment by DominicTobias** [comment]
If you want to do it then great! I prob won't get around to it until friday/weekend cheers

**Comment by DominicTobias** [comment]
Fixed in v2.0.0
