### ISSUE TITLE
Cropping output does not meet `aspect`

### ISSUE THREAD

**Issue by ouchxp** [DominicTobias/react-image-crop#71]
I'm trying to crop a relatively large image 2832 × 1602, and I set the aspect to `1/1`. But the `pixelCrop` I got after cropping is `Object {x: 0, y: 0, width: 1600, height: 1602}`.  Width and height are not consist with the `aspect` I set.

I checked the ReactCrop source code, seems `pixelCrop` is calculated from percentage values `width` and `height`, and the `width` and `height` are wrong as well.

I had to add the code below to make sure the cropping have correct size.

``` jsx
  handleOnChange(crop) {
    const { aspect, width, height } = crop;
    const newCrop = { ...crop };
    // ReactCrop is producing wrong ratio, fix the percentage according to aspect
    if (aspect) {
      // Adjust the smaller one to make sure we have enough size
      const { imageWidth, imageHeight } = this.state;
      if (width < height) {
        const newWidth = height * imageHeight * aspect / imageWidth;
        newCrop.width = newWidth > 100 ? 100 : newWidth;
      } else {
        const newHeight = width * imageWidth / aspect / imageHeight;
        newCrop.height = newHeight > 100 ? 100 : newHeight;
      }
    }
    this.setState({ crop: newCrop });
  }
```

**Comment by DominicTobias** [comment]
Thanks, I would have thought it was a floating point inaccuracy because I'm using percentages, but looks like from your fix you are making sure that the width and height doesn't exceed 100, I'm surprised because I thought I was already ensuring that!

**Comment by ouchxp** [comment]
You are right, you did ensure that. But my code is re-calculating width from height / height from width using aspect, did not use height or width from the parameter. So I have to add check for it.
