### ISSUE TITLE
Cannot pass styles props to images

### ISSUE THREAD

**Issue by stephenburgess8** [DominicTobias/react-image-crop#73]
I am looking to create a cropper which will be able to zoom an image via css while not scaling the selection marque. I would like to be able to pass a property of css styles which will be applied to the image behind the marque. Then, when the image is cropped, it will identify the correct portion of the image to crop and pass the updated pixel values in the callback. On first pass, I thought it may just be a matter of passing a style variable to be applied to the image. However now that I have thought this out, it seems as though the prop would need to be a value which would be included in calculations in the project to both calculate the scaling of the image as well as calculation of pixels based on the scale.

As we would like to use this library in our project, I am going to create a fork and start playing around with how to potentially solve this. It should be able to be done without making a breaking change by adding one or possibly two addition props to the root element allowing for scaling of the background image.

One other consideration would be about how to determine where the image is scaled (anchor).

I'd be curious to hear any thoughts you have on this topic.

**Comment by DominicTobias** [comment]
Hi is this zooming feature always zooming from the centre of the image? So if they clicked a [+] button for example the image zooms in and the edges disappear off view but equally on the left and right, and top and bottom?

**Comment by stephenburgess8** [comment]
Dominic, I am still trying to identify exactly what behavior I am looking for.

What I was hoping to do would be to apply a style to only the images to scale them while keeping the marquee size the same. The kind of behavior I'm trying to duplicate can be seen on Facebook or Twitter with avatar pictures. The marquee stays the same size while using a UI slider to increase zoom scales the image. Then, the user can grab and drag the image behind the selection marquee.

Looking closer at your code, the marquee size is calculated in relation to the image and the selected section overlay image. It seems like it would take a fairly substantial refactor to allow for scaling of the image to be independent of the marquee. Would you say that's right?

However, if you think it might be possible to scale with the image centered I would be curious to see if that is possible.

**Comment by DominicTobias** [comment]
I'd have to experiment, but I'd imagine you could keep the image centred and increase the dimensions so that the edges overflow out of the container. If you want to dynamically style the classes you can simple wrap the component in a div e.g. `<div classNames={myDymanicClasses}><ReactCtrop /></div>`

**Comment by DominicTobias** [comment]
Something like the techniques here (though many are background images) http://codepen.io/search/pens?q=image+zoom&limit=all&type=type-pens

**Comment by stephenburgess8** [comment]
I was able to scale everything at once - the entire container for ReactCrop. However what I'd like to do is scale the image only, but keep the selection marquee the same size. What I'd like to do is able to pan the image behind the crop area after zooming the image. I'd like to be able to select the crop area, zoom into the image, and reposition the image behind a fixed crop area. What I may end up doing is having a separate "mode" for zooming and panning.

**Comment by DominicTobias** [comment]
I don't see why it wouldn't be possible to just target the image with css but it's hard to know really without trying to do it!

**Comment by stephenburgess8** [comment]
On this line: https://github.com/DominicTobias/react-image-crop/blob/master/lib/ReactCrop.jsx#L777 is the first of the two images. Then following that is a div with the second overlay image as well as the crop marquee. When targeting the classnames `ReactCrop--image` and `ReactCrop--image-copy` (thank you for providing classnames on those, by the way) I am able to scale those, but the `ReactCrop--image-copy` is scaling out of proportion with the marquee and they no longer line up. I'd like to scale the image and dynamically change the selection by keeping the marquee the same size. So as the image gets larger, the selection of the image is smaller, but from the UI the selection marquee would stay the same size and in the same place. This may not be possible in the existing code.

**Comment by DominicTobias** [comment]
Yeah the crop is a percentage of the container (which is the size of the image). I guess you would have to transform the crop values in the parent relative to the expanded image dimensions so it gave the illusion of being in the same place (even if you just reduced the crop values). As for expanding the image itself I could look into using css transforms but I'm not sure if they can expand beyond their container without absolutely positioning.

Closing this as it's more of a discussion and something that won't be added to the code base but feel free to chat here.
