### ISSUE TITLE
onChange not called when passed updated prop `crop.aspect`

### ISSUE THREAD

**Issue by grrowl** [DominicTobias/react-image-crop#74]
In our application, we allow the user to set an aspect ratio. When we re-render the ImageCrop with the new aspect, the cropped area changes to match the new aspect ratio, but neither the `onComplete` or `onChange` callbacks fire (which is fair enough)

At the moment we can access the new crop using a reference to the component via `this._imageCropper.state.crop` in the `aspect` setState callback, but it'd be much nicer and less hacky if we had a `onAspectRatioChanged` or similar callback for when the crop changes due to a new aspect ratio making it invalid, or other prop changes.

We're updating the aspect ratio by doing a `this.setState({ aspect: newAspect })` in our component, and passing it down into ReactCrop like this:

``` jsx
<ReactCrop
  ref={ elem => { this._imageCropper = elem } }
  src={ src }
  crop={ {
    ...(meta && meta.crop),
    aspect,
  } }
  onChange={ (crop, pixelCrop) => {
    this.setState({ meta: { crop, pixelCrop } })
  } }
  onComplete={ (crop, pixelCrop) => {
    this.setState({ meta: { crop, pixelCrop } })
  } }
  />
```

**Comment by DominicTobias** [comment]
I'm trying to understand what you are trying to do - you want to know if the user changes the aspect ratio? Could you not do this in the component where they are modifying the aspect?

**Comment by grrowl** [comment]
If the user changes the aspect ratio outside of the component (and having this passed through to the component on a new render as a result of a setState call), I want to know if that new aspect ratio changes the dimensions of the crop. Hard to explain, hopefully this video clears it up:

![goat crop](https://cloud.githubusercontent.com/assets/907140/19911608/afc72df8-a0e8-11e6-956b-7ca479742afe.gif)

Notice the result of `onComplete` updates the state at the top, but only changes when a user interacts directly with the component. If we supply a new aspect, imageCrop's `componentWillReceiveProps` updates the crop area, but doesn't fire any callback.

I realise this is not ideal as it could lead to `setState (aspect) -> render -> (imageCrop.componentWillReceiveProps) -> onChange callback -> setState (crop) -> secondary render`, so I won't be bothered/surprised if such a callback is out of scope for `react-image-crop`. Here's how we're working around it in the meantime, which works well but is not ideal.

```jsx
setAspect(aspect) {
  this.setState({
    aspect: aspect,
  }, () => {
    // When we change the aspect ratio, the cropper re-renders with the correct
    // ratio, displaying the new crop dimensions to the user, but does not fire
    // onChange or onComplete callbacks. Therefore, we need to fetch/calculate
    // the new crop from within the component's state.
    this.setState({
      crop: this._imageCropper.state.crop,
      pixelCrop: this._imageCropper.getPixelCrop(this._imageCropper.state.crop),
    })
  })
}
```

**Comment by DominicTobias** [comment]
Sorry for the slow response - ah yeah I see what you mean as it's internally recalced. Yep I was also thinking about a potential double render, so as you originally suggested a new event might be the way forward. If you want to make a PR for `onAspectRatioChange` feel free to, I can't see it being a being a problem

**Comment by paweljedrzejczyk** [comment]
I added `onAspectRatioChange` callback in #76

**Comment by DominicTobias** [comment]
Thanks, publish @ 1.0.4
