### ISSUE TITLE
Css Animation of crop selection eats a lot of cpu

### ISSUE THREAD

**Issue by andi-dev** [DominicTobias/react-image-crop#77]
Hey there,

I noticed (running in chromium on ubuntu) that the 2 ReactCrop instances on my page are eating up around 20% of each of my 4 cpus.

Digging deeper I finally found out that it's the css-animation (marching ants) on the .ReactCrop--crop-selection element that is causing my machine to sweat.

I'm not sure if its an issue with my particular setup or a general issue. Disabling the animation is making fixing the problem for me. I can live without the animation, but am curious to any input on why such a simple animation is using up so much resources.

Thank you for your work, and best wishes,

Andreas

**Comment by DominicTobias** [comment]
That is interesting! I'll see if it is causing the same issues on my mac and if there is a way to optimise it

**Comment by DominicTobias** [comment]
Sorry for the delay - I can replicate this issue on Mac too - interesting, will dig deeper

**Comment by DominicTobias** [comment]
Fixed in v2.0.0

**Comment by DominicTobias** [comment]
Fixed in v2.0.0
