### ISSUE TITLE
svg clipPath refuses to repaint in webkit

### ISSUE THREAD

**Issue by shovemedia** [DominicTobias/react-image-crop#78]
My fix, hopefully temporary:

```
  /*
  Fix for webkit not re-rendering svg mask
  */
  componentDidUpdate(){
    var sel = this.imageCopyRef;

    sel.style.display='none';
    sel.offsetHeight; // no need to store this anywhere, the reference is enough
    sel.style.display='block';  
  }
```

**Comment by DominicTobias** [comment]
Hi is that mobile or desktop and what version? When I last checked this was working so it may be a regression or some specific combo I didn't check

**Comment by shovemedia** [comment]
Chrome and Safari on Mac. Firefox was fine. Didn't check mobile.

**Comment by DominicTobias** [comment]
@shovemedia Safari 9 or 10?

**Comment by DominicTobias** [comment]
Just tested and works fine on Safari 10 on Mac, I'm pretty sure on 9 too. If you clone this repo, run `npm i && npm start` and then open `demo/index.html` in Safari do you have the issue? If not it could be caused by your code.

**Comment by shovemedia** [comment]
My Safari is v9. Demo svg clippath works in both Chrome and Safari (although the programmatic state changes seem to throw JS errs?)

As it's clearly some kind of browser repaint bug, there's no telling what DOM-specifics are necessary to reliably reproduce the issue.

**Comment by DominicTobias** [comment]
I'm no longer using an SVG clipPath so this problem should be resolved

**Comment by omygodGIT** [comment]
What alternative did you use?

**Comment by DominicTobias** [comment]
@omygodGIT it's now using a large box-shadow - https://github.com/DominicTobias/react-image-crop/blame/master/lib/ReactCrop.scss#L53

Drawback of this method in this case is that the container needs `overflow: hidden` so the drag handles can't appear outside the container when dragged to the edges
