### ISSUE TITLE
Aspect

### ISSUE THREAD

**Issue by DPr00f** [DominicTobias/react-image-crop#8]
The latest changes broke the library.
If an aspect is set just moving the crop area around makes it disappear on mouse up.
Here's a gif explaining the problem.
![bug](https://cloud.githubusercontent.com/assets/989959/12380915/36f14266-bd76-11e5-8a36-ff1df73b5169.gif)
No errors on the console.
I've found the problem, will open a pull request soon with the fix.

**Comment by DominicTobias** [comment]
Ouch that's a bad bug thanks for bringing it up and making a PR @DPr00f! will take a look today

**Comment by DominicTobias** [comment]
@DPr00f interestingly I can't replicate this, what values are you passing as `crop` and what browser are you using?

**Comment by DPr00f** [comment]
I'm passing width: 100, aspect: 16/9, x:0, y:0

**Comment by DominicTobias** [comment]
Thanks for the fix, it was just published to npm as 0.0.13

**Comment by DPr00f** [comment]
Thanks for publishing it so quickly. :+1:

**Comment by DominicTobias** [comment]
@DPr00f do you know the use-case for merging in the current crop (`this.state ? this.state.crop : {}`) with `props.crop`? My concern is that the props.crop might be omitting some values on purpose and then the current crop will fill those in which might be unintended
