### ISSUE TITLE
Module not found: Error: Can't resolve './dist/ReactCrop'

### ISSUE THREAD

**Issue by babsonmatt** [DominicTobias/react-image-crop#85]
Getting ```Module not found: Error: Can't resolve './dist/ReactCrop'``` after upgrading to latest just now

**Comment by yury-dymov** [comment]
@DominicTobias, I installed the package and I can see that dist/ReactCrop.css is there and ReactCrop.js is missing. Seems you forgot to build the js according to the scripts section:

 ```JSON
"release-css": "node-sass lib/ReactCrop.scss dist/ReactCrop.css",
"release-js": "cross-env NODE_ENV=production webpack",
```

**Comment by DominicTobias** [comment]
Thanks, that's strange I ran the release - will make a patch version

**Comment by DominicTobias** [comment]
Released 2.0.2 - please let me know if that fixes your issue @babsonmatt

**Comment by yury-dymov** [comment]
@DominicTobias, I checked new release, works fine

**Comment by DominicTobias** [comment]
Cool tanks @yury-dymov

**Comment by babsonmatt** [comment]
@DominicTobias all good! thank you!
