### ISSUE TITLE
Crop selection window not sizing with highlighted area vertically

### ISSUE THREAD

**Issue by LPayyapilli** [DominicTobias/react-image-crop#86]
This is an awesome tool. It works really well. However, I am experiencing an issue where when the image is uploaded and the crop selection default is put on top of it, the boundaries of the selection and the highlight do not match up. I also noticed that when you shift the selection vertically, the top attribute changes but it doesn't match the crop selection. This mismatching looks wonky. 

crop: {height: 50, width: 50} is what I am setting, although I have tried using aspect and other combinations of the crop props as well.
![screen shot 2017-02-14 at 1 47 47 pm](https://cloud.githubusercontent.com/assets/10728027/22943634/3ac2fa52-f2bc-11e6-9fc1-d396f443707c.png)
^^ shows the first issue
![screen shot 2017-02-14 at 1 48 30 pm](https://cloud.githubusercontent.com/assets/10728027/22943646/4c8cb5de-f2bc-11e6-95b5-4b10429cdead.png)
![screen shot 2017-02-14 at 1 48 53 pm](https://cloud.githubusercontent.com/assets/10728027/22943658/59ef9dae-f2bc-11e6-91db-b349b29722a7.png)
^^shows the second issue (top not updating correctly with dotted selection)

@DominicTobias any guidance would be appreciated. Thanks for making this lib.

**Comment by DominicTobias** [comment]
Hi @LPayyapilli, thanks for the comments, could you upload that image somewhere and link it here? Just to be clear - this can be replicated without the uploading to server part?

**Comment by LPayyapilli** [comment]
http://www.imgbase.info/images/safe-wallpapers/photography/cityscape/12341_cityscape_skyline.jpg
^^ thats the image

Yes this is all on the client. I do not believe it is related to the server, as I am not manipulating the crop object anywhere except the client/display. 

On further investigation, this issue is limited to this size image. When I try smaller images, it seems to work fine. I'm not sure if that helps or not. It could be related to aspect ratio maybe? 

Just for completeness, this is the class in whole:

`class Customize extends React.Component {
    static contextTypes = {
        flux: React.PropTypes.object
    };

    static propTypes = {
        customizeProps: React.PropTypes.object.isRequired,
        dashboard: React.PropTypes.object
    };

    constructor(props) {
        super(props);

        this.state = {
            name: '',
            open: false,
            error: false,
            src: '',
            crop: {
                width: 50,
                height: 50
            }
        }
    }

    componentWillReceiveProps(props) {
        if (!this.state.open) {
            let name = (props.dashboard && props.customizeProps.edit) ? props.dashboard.name : '';
            let src = (props.dashboard && props.customizeProps.edit) ? props.dashboard.logo : '';

            this.setState({
                name: name,
                open: props.customizeProps.display == 'block',
                error: false,
                src: src,
                crop: {
                    width: 50,
                    height: 50
                }
            });
        }
    }

    onChangeName = (e) => {
        this.setState({ name: e.target.value });
    }

    onClose = () => {
        this.context.flux.getActions('dashboard-actions').toggleCustomize({ display: 'none'});
        document.getElementById('logo').value = '';
        document.getElementById('logo-upload').reset();

        this.setState({
            open: false,
            error: false
        });
    }

    uploadFile = () => {
        let self = this;
        let file = this.refs.logo.files[0];

        if (!file) {
            return false;
        } else if (VALID_LOGO_TYPES.indexOf(file.type) == -1) {
            alert(UPLOAD_FORMATS_TEXT);
            return false;
        } else {
            this.reader = new FileReader();
            this.reader.addEventListener("load", function () {
                self.setState({src: self.reader.result});
            }, false);

            if (file) {
                this.reader.readAsDataURL(file);
            }
        }
    }

    deleteLogo = () => {
        this.reader = null;
        this.refs.crop.src = "";
        this.setState({src: '', cropped: '', crop: {width: 50, height: 50}});
    }

    updateCrop = (crop) => {
        this.cropImage(this.state.src, crop);
    }

    cropImage = (src, crop) => {

        let loadedImg = new Image();
        loadedImg.src = src;
        let imageWidth = loadedImg.naturalWidth;
        let imageHeight = loadedImg.naturalHeight;
        let cropX = (crop.x / 100) * imageWidth;
        let cropY = (crop.y / 100) * imageHeight;
        let cropWidth = (crop.width / 100) * imageWidth;
        let cropHeight = (crop.height / 100) * imageHeight;
        let canvas = document.createElement('canvas');
            canvas.width = cropWidth;
            canvas.height = cropHeight;
        let ctx = canvas.getContext('2d');

        ctx.drawImage(loadedImg, cropX, cropY, cropWidth, cropHeight, 0, 0, cropWidth, cropHeight);

        this.setState({cropped: canvas.toDataURL('image/jpeg'), crop: crop});
    }


    editOrCreateDashboard = () => {
        let title = this.refs.name.value;

        if (title.trim() == '') {
            this.setState({
                name: 'Please name your dashboard',
                error: true
            });

            return false;
        }

        if (this.props.customizeProps && this.props.customizeProps.edit) {
            this.context.flux.getActions('dashboard-actions').editDashboard({
                id: this.props.dashboard.id,
                name: title.replace(/^[ ]+|[ ]+$/g,''),
                logo: this.state.cropped
            });
        } else {
            this.context.flux.getActions('dashboard-actions').createDashboard({
                name: title,
                logo: this.state.cropped
            });
        }

        this.setState({ error: false, crop: {height: 50, width: 50} });
        this.onClose();
    }

    render() {
        let top = window.scrollY + Y_POS_OFFSET + 'px';
        let inputClass = (this.state.error) ? "title error" : "title";

        let cover = null;
        if (this.props.customizeProps.cover) {
            cover = (<Cover onClick={this.onClose} style={{backgroundColor: '#000', opacity: '0.5', zIndex: '1500'}} />);
        }

        let cropper = (this.state.src) ? (<ReactCrop ref='crop' src={this.state.src} crop={this.state.crop} onComplete={this.updateCrop} onImageLoaded={this.updateCrop} />) : (<img src={this.state.src} id="preview" ref='preview' />);
        let deleteIcon = (this.state.src) ? (<i className="material-icons delete" onClick={this.deleteLogo}>delete</i>) : null;

        return (
            <div style={{display: this.props.customizeProps.display}}>
                <div id="customizeModal" style={{top: top}}>
                    <h1 className="header">{this.props.customizeProps.title}</h1>

                    <input ref="name" className={inputClass} maxLength="65" placeholder="Dashboard Title" value={this.state.name} onChange={this.onChangeName} />
                    <span id="required">*</span>

                    <div className="customize-options">
                        {/* Choose Logo button */}
                        <div className="choose-logo">Choose Logo</div>
                        <form id="logo-upload" ref="logoUpload" method="PUT" action="/ch/newdashboard" encType="multipart/form-data">
                            <input type="hidden" name="dashboardId" readOnly />
                            <input type="file"  name="logo" ref="logo" className="logo-input" id="logo" onChange={this.uploadFile} />
                        </form>

                        {/* Logo preview */}
                        {cropper}
                        {deleteIcon}

                        {/* Create/Update the dashboard */}
                        <button className="submit" onClick={this.editOrCreateDashboard}>{this.props.customizeProps.button}</button>
                    </div>
                </div>

                {cover}
            </div>
        );
    }
}

`
