### ISSUE TITLE
How to disable dimension of crop area and make available only dragging?

### ISSUE THREAD

**Issue by optimatex** [DominicTobias/react-image-crop#89]
Hi. Thanks for this repo.
I would like to use reac-image-crop for setting cover image. That means i need fixed crop size in pixel, let's say 500 x 300 px. So, i don't need ability to change crop width or height. User should only have ability to drag pre-defined crop area to capture certain part of image. 
How can i achive this? i know there is maxWidth prop, but it use percentage and hence it doesn't allow me to get immutable 500 x 300 crop zone. 
Is there any other solution for my case?  Thanks!

**Comment by DominicTobias** [comment]
Hi, you can only set the crop using percentages, you may find another cropping library which is based on pixels more useful to you - but if you know the width + height of the image you should be able to derive the percentage - e.g. if the crop image is 1500 wide, then you know that the % to use is 33.3333% (500/1500*100). If you set `disabled` to true then they won't be able to modify the crop, you might also want to hide the drag handles (the squares) with css.

**Comment by optimatex** [comment]
Thank u for ur response. I'll left the feedback if I get luck with resolving this issue
