### ISSUE TITLE
Displaying vertical images

### ISSUE THREAD

**Issue by anvk** [DominicTobias/react-image-crop#93]
It seems that `ReactCrop` displays vertical images preserving their original size. Is there a way to fit image inside the parent <div /> ?

Right out of the box, Cropper will make any landscape image to be adjusted to cropper's width and height. Basically image dimensions are adjusted so that they fit. Example:

<img width="761" alt="screen shot 2017-04-18 at 2 21 12 pm" src="https://cloud.githubusercontent.com/assets/686969/25146591/7116b622-2442-11e7-8e55-c7553eb81708.png">

Vertical images on the other hand would be shown in their full height.

My image: http://pngimg.com/uploads/tree/tree_PNG230.png

This is how it looks on a screen:
![screen shot 2017-04-12 at 1 33 25 pm](https://cloud.githubusercontent.com/assets/686969/24971081/b12649a2-1f84-11e7-87fc-33be93f84491.png)

Please let me know if I need to provide any other extra information.

**Comment by DominicTobias** [comment]
Delayed answer of the century, but this depends on how you've set up the css on your page - it's more of a general question on how to give an image a max-height. You can literally do it with the `max-height: 100%` like this: https://jsfiddle.net/njwhedr0/

If i didn't understand something please feel free to comment.
