### ISSUE TITLE
disable page scroll while cropping on small screens

### ISSUE THREAD

**Issue by jonathansp** [DominicTobias/react-image-crop#94]
how to avoid this behavior?

![crop-scroll](https://cloud.githubusercontent.com/assets/457972/25231630/f42bd8e0-25ae-11e7-8838-acee9913deb1.gif)

**Comment by jonathansp** [comment]
Hi @DominicTobias 

Please check if makes sense: https://github.com/DominicTobias/react-image-crop/pull/95
By having these callbacks we are able to add and remove CSS classes that will prevent this problem.

**Comment by DominicTobias** [comment]
Released in 2.0.4
