### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by paltman** [DominicTobias/react-image-crop#96]
React 15.5 has deprecated use of PropTypes from the React package.

```javascript
import PropTypes from 'prop-types';
```

instead of

```javascript
import React, { PropTypes } from 'react';
```

**Comment by lukaszgolder** [comment]
Are you planning to release this soon?

**Comment by DominicTobias** [comment]
I am but I'm away with only a phone until May 22, will release it in 1-2 days after I get back
